#pragma once


enum ConnectionStatus {
    CONNECTION_PROCEED, CONNECTION_ERROR,
    CONNECTION_SERVER_ERROR, CONNECTION_DISCONNECT, CONNECTION_UNEXPECTED_SERVER_DISCONNECT,
    CONNECTION_SUCCESS, STATUS_DUMMY_HACK};

enum ConnectionSubStatus {
    CONNECTION_ERROR_UNKNOWN_SCHAIN_ID, CONNECTION_ERROR_UNKNOWN_SERVER_ERROR,
    CONNECTION_ERROR_DONT_KNOW_THIS_NODE, CONNECTION_ERROR_INVALID_NODE_INDEX,
    CONNECTION_ERROR_INVALID_NODE_ID, CONNECTION_ERROR_TIME_STAMP_IN_THE_FUTURE,
    CONNECTION_ERROR_TIME_STAMP_EARLIER_THAN_COMMITTED,
    CONNECTION_BLOCK_PROPOSAL_TOO_LATE,
    CONNECTION_DONT_HAVE_BLOCK_YET,
    CONNECTION_DONT_HAVE_BLOCK,
    CONNECTION_INVALID_INDEX,
    CONNECTION_INVALID_HASH,
    CONNECTION_NO_NEW_BLOCKS,
    SUBSTATUS_DUMMY_HACK };


