syntax = "proto3";

package block_finalize;


service BlockService {
  rpc GetBlockFinalizeInfo(BlockFinalizeRequest) returns (BlockFinalizeResponse);
}

message BlockFinalizeRequest {
  uint64 schainID = 1;
  uint64 proposerIndex = 2;
  uint64 blockID = 3;
  uint64 nodeID = 4;
  bool needDAProof = 5;
  bool needDecryptionShares = 6;
  optional uint32 fragmentIndex = 7;
}

message BlockFinalizeResponse {
  oneof result {
    SuccessResponse success = 1;
    ErrorResponse error = 2;
  }
}

message SuccessResponse {
  string blockHash = 1;
  uint64 blockSize = 2;
  optional string daProofSig = 3;
  optional bytes fragment = 4;
}

message ErrorResponse {
  uint32 status = 1;
  uint32 substatus = 2;
  optional string message = 3;
}
