// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: block_finalize.proto
#ifndef GRPC_block_5ffinalize_2eproto__INCLUDED
#define GRPC_block_5ffinalize_2eproto__INCLUDED

#include "block_finalize.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace block_finalize {

class BlockService final {
 public:
  static constexpr char const* service_full_name() {
    return "block_finalize.BlockService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetBlockFinalizeInfo(::grpc::ClientContext* context, const ::block_finalize::BlockFinalizeRequest& request, ::block_finalize::BlockFinalizeResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::block_finalize::BlockFinalizeResponse>> AsyncGetBlockFinalizeInfo(::grpc::ClientContext* context, const ::block_finalize::BlockFinalizeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::block_finalize::BlockFinalizeResponse>>(AsyncGetBlockFinalizeInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::block_finalize::BlockFinalizeResponse>> PrepareAsyncGetBlockFinalizeInfo(::grpc::ClientContext* context, const ::block_finalize::BlockFinalizeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::block_finalize::BlockFinalizeResponse>>(PrepareAsyncGetBlockFinalizeInfoRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetBlockFinalizeInfo(::grpc::ClientContext* context, const ::block_finalize::BlockFinalizeRequest* request, ::block_finalize::BlockFinalizeResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetBlockFinalizeInfo(::grpc::ClientContext* context, const ::block_finalize::BlockFinalizeRequest* request, ::block_finalize::BlockFinalizeResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::block_finalize::BlockFinalizeResponse>* AsyncGetBlockFinalizeInfoRaw(::grpc::ClientContext* context, const ::block_finalize::BlockFinalizeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::block_finalize::BlockFinalizeResponse>* PrepareAsyncGetBlockFinalizeInfoRaw(::grpc::ClientContext* context, const ::block_finalize::BlockFinalizeRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetBlockFinalizeInfo(::grpc::ClientContext* context, const ::block_finalize::BlockFinalizeRequest& request, ::block_finalize::BlockFinalizeResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::block_finalize::BlockFinalizeResponse>> AsyncGetBlockFinalizeInfo(::grpc::ClientContext* context, const ::block_finalize::BlockFinalizeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::block_finalize::BlockFinalizeResponse>>(AsyncGetBlockFinalizeInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::block_finalize::BlockFinalizeResponse>> PrepareAsyncGetBlockFinalizeInfo(::grpc::ClientContext* context, const ::block_finalize::BlockFinalizeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::block_finalize::BlockFinalizeResponse>>(PrepareAsyncGetBlockFinalizeInfoRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetBlockFinalizeInfo(::grpc::ClientContext* context, const ::block_finalize::BlockFinalizeRequest* request, ::block_finalize::BlockFinalizeResponse* response, std::function<void(::grpc::Status)>) override;
      void GetBlockFinalizeInfo(::grpc::ClientContext* context, const ::block_finalize::BlockFinalizeRequest* request, ::block_finalize::BlockFinalizeResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::block_finalize::BlockFinalizeResponse>* AsyncGetBlockFinalizeInfoRaw(::grpc::ClientContext* context, const ::block_finalize::BlockFinalizeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::block_finalize::BlockFinalizeResponse>* PrepareAsyncGetBlockFinalizeInfoRaw(::grpc::ClientContext* context, const ::block_finalize::BlockFinalizeRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetBlockFinalizeInfo_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetBlockFinalizeInfo(::grpc::ServerContext* context, const ::block_finalize::BlockFinalizeRequest* request, ::block_finalize::BlockFinalizeResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetBlockFinalizeInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetBlockFinalizeInfo() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetBlockFinalizeInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBlockFinalizeInfo(::grpc::ServerContext* /*context*/, const ::block_finalize::BlockFinalizeRequest* /*request*/, ::block_finalize::BlockFinalizeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetBlockFinalizeInfo(::grpc::ServerContext* context, ::block_finalize::BlockFinalizeRequest* request, ::grpc::ServerAsyncResponseWriter< ::block_finalize::BlockFinalizeResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetBlockFinalizeInfo<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetBlockFinalizeInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetBlockFinalizeInfo() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::block_finalize::BlockFinalizeRequest, ::block_finalize::BlockFinalizeResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::block_finalize::BlockFinalizeRequest* request, ::block_finalize::BlockFinalizeResponse* response) { return this->GetBlockFinalizeInfo(context, request, response); }));}
    void SetMessageAllocatorFor_GetBlockFinalizeInfo(
        ::grpc::MessageAllocator< ::block_finalize::BlockFinalizeRequest, ::block_finalize::BlockFinalizeResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::block_finalize::BlockFinalizeRequest, ::block_finalize::BlockFinalizeResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetBlockFinalizeInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBlockFinalizeInfo(::grpc::ServerContext* /*context*/, const ::block_finalize::BlockFinalizeRequest* /*request*/, ::block_finalize::BlockFinalizeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetBlockFinalizeInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::block_finalize::BlockFinalizeRequest* /*request*/, ::block_finalize::BlockFinalizeResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetBlockFinalizeInfo<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetBlockFinalizeInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetBlockFinalizeInfo() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetBlockFinalizeInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBlockFinalizeInfo(::grpc::ServerContext* /*context*/, const ::block_finalize::BlockFinalizeRequest* /*request*/, ::block_finalize::BlockFinalizeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetBlockFinalizeInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetBlockFinalizeInfo() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetBlockFinalizeInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBlockFinalizeInfo(::grpc::ServerContext* /*context*/, const ::block_finalize::BlockFinalizeRequest* /*request*/, ::block_finalize::BlockFinalizeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetBlockFinalizeInfo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetBlockFinalizeInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetBlockFinalizeInfo() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetBlockFinalizeInfo(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetBlockFinalizeInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBlockFinalizeInfo(::grpc::ServerContext* /*context*/, const ::block_finalize::BlockFinalizeRequest* /*request*/, ::block_finalize::BlockFinalizeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetBlockFinalizeInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetBlockFinalizeInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetBlockFinalizeInfo() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::block_finalize::BlockFinalizeRequest, ::block_finalize::BlockFinalizeResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::block_finalize::BlockFinalizeRequest, ::block_finalize::BlockFinalizeResponse>* streamer) {
                       return this->StreamedGetBlockFinalizeInfo(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetBlockFinalizeInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetBlockFinalizeInfo(::grpc::ServerContext* /*context*/, const ::block_finalize::BlockFinalizeRequest* /*request*/, ::block_finalize::BlockFinalizeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetBlockFinalizeInfo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::block_finalize::BlockFinalizeRequest,::block_finalize::BlockFinalizeResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetBlockFinalizeInfo<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetBlockFinalizeInfo<Service > StreamedService;
};

}  // namespace block_finalize


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_block_5ffinalize_2eproto__INCLUDED
