// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: block_finalize.proto
// Protobuf C++ Version: 5.29.0

#ifndef block_5ffinalize_2eproto_2epb_2eh
#define block_5ffinalize_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_block_5ffinalize_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_block_5ffinalize_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_block_5ffinalize_2eproto;
namespace block_finalize {
class BlockFinalizeRequest;
struct BlockFinalizeRequestDefaultTypeInternal;
extern BlockFinalizeRequestDefaultTypeInternal _BlockFinalizeRequest_default_instance_;
class BlockFinalizeResponse;
struct BlockFinalizeResponseDefaultTypeInternal;
extern BlockFinalizeResponseDefaultTypeInternal _BlockFinalizeResponse_default_instance_;
class ErrorResponse;
struct ErrorResponseDefaultTypeInternal;
extern ErrorResponseDefaultTypeInternal _ErrorResponse_default_instance_;
class SuccessResponse;
struct SuccessResponseDefaultTypeInternal;
extern SuccessResponseDefaultTypeInternal _SuccessResponse_default_instance_;
}  // namespace block_finalize
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace block_finalize {

// ===================================================================


// -------------------------------------------------------------------

class SuccessResponse final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:block_finalize.SuccessResponse) */ {
 public:
  inline SuccessResponse() : SuccessResponse(nullptr) {}
  ~SuccessResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SuccessResponse* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SuccessResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SuccessResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline SuccessResponse(const SuccessResponse& from) : SuccessResponse(nullptr, from) {}
  inline SuccessResponse(SuccessResponse&& from) noexcept
      : SuccessResponse(nullptr, std::move(from)) {}
  inline SuccessResponse& operator=(const SuccessResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline SuccessResponse& operator=(SuccessResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SuccessResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const SuccessResponse* internal_default_instance() {
    return reinterpret_cast<const SuccessResponse*>(
        &_SuccessResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(SuccessResponse& a, SuccessResponse& b) { a.Swap(&b); }
  inline void Swap(SuccessResponse* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SuccessResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SuccessResponse* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SuccessResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SuccessResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SuccessResponse& from) { SuccessResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SuccessResponse* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "block_finalize.SuccessResponse"; }

 protected:
  explicit SuccessResponse(::google::protobuf::Arena* arena);
  SuccessResponse(::google::protobuf::Arena* arena, const SuccessResponse& from);
  SuccessResponse(::google::protobuf::Arena* arena, SuccessResponse&& from) noexcept
      : SuccessResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kBlockHashFieldNumber = 1,
    kDaProofSigFieldNumber = 3,
    kFragmentFieldNumber = 4,
    kBlockSizeFieldNumber = 2,
  };
  // string blockHash = 1;
  void clear_blockhash() ;
  const std::string& blockhash() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_blockhash(Arg_&& arg, Args_... args);
  std::string* mutable_blockhash();
  PROTOBUF_NODISCARD std::string* release_blockhash();
  void set_allocated_blockhash(std::string* value);

  private:
  const std::string& _internal_blockhash() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_blockhash(
      const std::string& value);
  std::string* _internal_mutable_blockhash();

  public:
  // optional string daProofSig = 3;
  bool has_daproofsig() const;
  void clear_daproofsig() ;
  const std::string& daproofsig() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_daproofsig(Arg_&& arg, Args_... args);
  std::string* mutable_daproofsig();
  PROTOBUF_NODISCARD std::string* release_daproofsig();
  void set_allocated_daproofsig(std::string* value);

  private:
  const std::string& _internal_daproofsig() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_daproofsig(
      const std::string& value);
  std::string* _internal_mutable_daproofsig();

  public:
  // optional bytes fragment = 4;
  bool has_fragment() const;
  void clear_fragment() ;
  const std::string& fragment() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_fragment(Arg_&& arg, Args_... args);
  std::string* mutable_fragment();
  PROTOBUF_NODISCARD std::string* release_fragment();
  void set_allocated_fragment(std::string* value);

  private:
  const std::string& _internal_fragment() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_fragment(
      const std::string& value);
  std::string* _internal_mutable_fragment();

  public:
  // uint64 blockSize = 2;
  void clear_blocksize() ;
  ::uint64_t blocksize() const;
  void set_blocksize(::uint64_t value);

  private:
  ::uint64_t _internal_blocksize() const;
  void _internal_set_blocksize(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:block_finalize.SuccessResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      58, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SuccessResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr blockhash_;
    ::google::protobuf::internal::ArenaStringPtr daproofsig_;
    ::google::protobuf::internal::ArenaStringPtr fragment_;
    ::uint64_t blocksize_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_block_5ffinalize_2eproto;
};
// -------------------------------------------------------------------

class ErrorResponse final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:block_finalize.ErrorResponse) */ {
 public:
  inline ErrorResponse() : ErrorResponse(nullptr) {}
  ~ErrorResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ErrorResponse* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ErrorResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ErrorResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline ErrorResponse(const ErrorResponse& from) : ErrorResponse(nullptr, from) {}
  inline ErrorResponse(ErrorResponse&& from) noexcept
      : ErrorResponse(nullptr, std::move(from)) {}
  inline ErrorResponse& operator=(const ErrorResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ErrorResponse& operator=(ErrorResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ErrorResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ErrorResponse* internal_default_instance() {
    return reinterpret_cast<const ErrorResponse*>(
        &_ErrorResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(ErrorResponse& a, ErrorResponse& b) { a.Swap(&b); }
  inline void Swap(ErrorResponse* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ErrorResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ErrorResponse* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ErrorResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ErrorResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ErrorResponse& from) { ErrorResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ErrorResponse* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "block_finalize.ErrorResponse"; }

 protected:
  explicit ErrorResponse(::google::protobuf::Arena* arena);
  ErrorResponse(::google::protobuf::Arena* arena, const ErrorResponse& from);
  ErrorResponse(::google::protobuf::Arena* arena, ErrorResponse&& from) noexcept
      : ErrorResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMessageFieldNumber = 3,
    kStatusFieldNumber = 1,
    kSubstatusFieldNumber = 2,
  };
  // optional string message = 3;
  bool has_message() const;
  void clear_message() ;
  const std::string& message() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_message(Arg_&& arg, Args_... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* value);

  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(
      const std::string& value);
  std::string* _internal_mutable_message();

  public:
  // uint32 status = 1;
  void clear_status() ;
  ::uint32_t status() const;
  void set_status(::uint32_t value);

  private:
  ::uint32_t _internal_status() const;
  void _internal_set_status(::uint32_t value);

  public:
  // uint32 substatus = 2;
  void clear_substatus() ;
  ::uint32_t substatus() const;
  void set_substatus(::uint32_t value);

  private:
  ::uint32_t _internal_substatus() const;
  void _internal_set_substatus(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:block_finalize.ErrorResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      44, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ErrorResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr message_;
    ::uint32_t status_;
    ::uint32_t substatus_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_block_5ffinalize_2eproto;
};
// -------------------------------------------------------------------

class BlockFinalizeRequest final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:block_finalize.BlockFinalizeRequest) */ {
 public:
  inline BlockFinalizeRequest() : BlockFinalizeRequest(nullptr) {}
  ~BlockFinalizeRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BlockFinalizeRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BlockFinalizeRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BlockFinalizeRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline BlockFinalizeRequest(const BlockFinalizeRequest& from) : BlockFinalizeRequest(nullptr, from) {}
  inline BlockFinalizeRequest(BlockFinalizeRequest&& from) noexcept
      : BlockFinalizeRequest(nullptr, std::move(from)) {}
  inline BlockFinalizeRequest& operator=(const BlockFinalizeRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline BlockFinalizeRequest& operator=(BlockFinalizeRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BlockFinalizeRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const BlockFinalizeRequest* internal_default_instance() {
    return reinterpret_cast<const BlockFinalizeRequest*>(
        &_BlockFinalizeRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(BlockFinalizeRequest& a, BlockFinalizeRequest& b) { a.Swap(&b); }
  inline void Swap(BlockFinalizeRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BlockFinalizeRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BlockFinalizeRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BlockFinalizeRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BlockFinalizeRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BlockFinalizeRequest& from) { BlockFinalizeRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BlockFinalizeRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "block_finalize.BlockFinalizeRequest"; }

 protected:
  explicit BlockFinalizeRequest(::google::protobuf::Arena* arena);
  BlockFinalizeRequest(::google::protobuf::Arena* arena, const BlockFinalizeRequest& from);
  BlockFinalizeRequest(::google::protobuf::Arena* arena, BlockFinalizeRequest&& from) noexcept
      : BlockFinalizeRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSchainIDFieldNumber = 1,
    kProposerIndexFieldNumber = 2,
    kBlockIDFieldNumber = 3,
    kNodeIDFieldNumber = 4,
    kNeedDAProofFieldNumber = 5,
    kNeedDecryptionSharesFieldNumber = 6,
    kFragmentIndexFieldNumber = 7,
  };
  // uint64 schainID = 1;
  void clear_schainid() ;
  ::uint64_t schainid() const;
  void set_schainid(::uint64_t value);

  private:
  ::uint64_t _internal_schainid() const;
  void _internal_set_schainid(::uint64_t value);

  public:
  // uint64 proposerIndex = 2;
  void clear_proposerindex() ;
  ::uint64_t proposerindex() const;
  void set_proposerindex(::uint64_t value);

  private:
  ::uint64_t _internal_proposerindex() const;
  void _internal_set_proposerindex(::uint64_t value);

  public:
  // uint64 blockID = 3;
  void clear_blockid() ;
  ::uint64_t blockid() const;
  void set_blockid(::uint64_t value);

  private:
  ::uint64_t _internal_blockid() const;
  void _internal_set_blockid(::uint64_t value);

  public:
  // uint64 nodeID = 4;
  void clear_nodeid() ;
  ::uint64_t nodeid() const;
  void set_nodeid(::uint64_t value);

  private:
  ::uint64_t _internal_nodeid() const;
  void _internal_set_nodeid(::uint64_t value);

  public:
  // bool needDAProof = 5;
  void clear_needdaproof() ;
  bool needdaproof() const;
  void set_needdaproof(bool value);

  private:
  bool _internal_needdaproof() const;
  void _internal_set_needdaproof(bool value);

  public:
  // bool needDecryptionShares = 6;
  void clear_needdecryptionshares() ;
  bool needdecryptionshares() const;
  void set_needdecryptionshares(bool value);

  private:
  bool _internal_needdecryptionshares() const;
  void _internal_set_needdecryptionshares(bool value);

  public:
  // optional uint32 fragmentIndex = 7;
  bool has_fragmentindex() const;
  void clear_fragmentindex() ;
  ::uint32_t fragmentindex() const;
  void set_fragmentindex(::uint32_t value);

  private:
  ::uint32_t _internal_fragmentindex() const;
  void _internal_set_fragmentindex(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:block_finalize.BlockFinalizeRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 7, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const BlockFinalizeRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint64_t schainid_;
    ::uint64_t proposerindex_;
    ::uint64_t blockid_;
    ::uint64_t nodeid_;
    bool needdaproof_;
    bool needdecryptionshares_;
    ::uint32_t fragmentindex_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_block_5ffinalize_2eproto;
};
// -------------------------------------------------------------------

class BlockFinalizeResponse final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:block_finalize.BlockFinalizeResponse) */ {
 public:
  inline BlockFinalizeResponse() : BlockFinalizeResponse(nullptr) {}
  ~BlockFinalizeResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BlockFinalizeResponse* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BlockFinalizeResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BlockFinalizeResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline BlockFinalizeResponse(const BlockFinalizeResponse& from) : BlockFinalizeResponse(nullptr, from) {}
  inline BlockFinalizeResponse(BlockFinalizeResponse&& from) noexcept
      : BlockFinalizeResponse(nullptr, std::move(from)) {}
  inline BlockFinalizeResponse& operator=(const BlockFinalizeResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline BlockFinalizeResponse& operator=(BlockFinalizeResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BlockFinalizeResponse& default_instance() {
    return *internal_default_instance();
  }
  enum ResultCase {
    kSuccess = 1,
    kError = 2,
    RESULT_NOT_SET = 0,
  };
  static inline const BlockFinalizeResponse* internal_default_instance() {
    return reinterpret_cast<const BlockFinalizeResponse*>(
        &_BlockFinalizeResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(BlockFinalizeResponse& a, BlockFinalizeResponse& b) { a.Swap(&b); }
  inline void Swap(BlockFinalizeResponse* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BlockFinalizeResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BlockFinalizeResponse* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BlockFinalizeResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BlockFinalizeResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BlockFinalizeResponse& from) { BlockFinalizeResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BlockFinalizeResponse* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "block_finalize.BlockFinalizeResponse"; }

 protected:
  explicit BlockFinalizeResponse(::google::protobuf::Arena* arena);
  BlockFinalizeResponse(::google::protobuf::Arena* arena, const BlockFinalizeResponse& from);
  BlockFinalizeResponse(::google::protobuf::Arena* arena, BlockFinalizeResponse&& from) noexcept
      : BlockFinalizeResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSuccessFieldNumber = 1,
    kErrorFieldNumber = 2,
  };
  // .block_finalize.SuccessResponse success = 1;
  bool has_success() const;
  private:
  bool _internal_has_success() const;

  public:
  void clear_success() ;
  const ::block_finalize::SuccessResponse& success() const;
  PROTOBUF_NODISCARD ::block_finalize::SuccessResponse* release_success();
  ::block_finalize::SuccessResponse* mutable_success();
  void set_allocated_success(::block_finalize::SuccessResponse* value);
  void unsafe_arena_set_allocated_success(::block_finalize::SuccessResponse* value);
  ::block_finalize::SuccessResponse* unsafe_arena_release_success();

  private:
  const ::block_finalize::SuccessResponse& _internal_success() const;
  ::block_finalize::SuccessResponse* _internal_mutable_success();

  public:
  // .block_finalize.ErrorResponse error = 2;
  bool has_error() const;
  private:
  bool _internal_has_error() const;

  public:
  void clear_error() ;
  const ::block_finalize::ErrorResponse& error() const;
  PROTOBUF_NODISCARD ::block_finalize::ErrorResponse* release_error();
  ::block_finalize::ErrorResponse* mutable_error();
  void set_allocated_error(::block_finalize::ErrorResponse* value);
  void unsafe_arena_set_allocated_error(::block_finalize::ErrorResponse* value);
  ::block_finalize::ErrorResponse* unsafe_arena_release_error();

  private:
  const ::block_finalize::ErrorResponse& _internal_error() const;
  ::block_finalize::ErrorResponse* _internal_mutable_error();

  public:
  void clear_result();
  ResultCase result_case() const;
  // @@protoc_insertion_point(class_scope:block_finalize.BlockFinalizeResponse)
 private:
  class _Internal;
  void set_has_success();
  void set_has_error();
  inline bool has_result() const;
  inline void clear_has_result();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 2, 2,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const BlockFinalizeResponse& from_msg);
    union ResultUnion {
      constexpr ResultUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::block_finalize::SuccessResponse* success_;
      ::block_finalize::ErrorResponse* error_;
    } result_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_block_5ffinalize_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// BlockFinalizeRequest

// uint64 schainID = 1;
inline void BlockFinalizeRequest::clear_schainid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.schainid_ = ::uint64_t{0u};
}
inline ::uint64_t BlockFinalizeRequest::schainid() const {
  // @@protoc_insertion_point(field_get:block_finalize.BlockFinalizeRequest.schainID)
  return _internal_schainid();
}
inline void BlockFinalizeRequest::set_schainid(::uint64_t value) {
  _internal_set_schainid(value);
  // @@protoc_insertion_point(field_set:block_finalize.BlockFinalizeRequest.schainID)
}
inline ::uint64_t BlockFinalizeRequest::_internal_schainid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.schainid_;
}
inline void BlockFinalizeRequest::_internal_set_schainid(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.schainid_ = value;
}

// uint64 proposerIndex = 2;
inline void BlockFinalizeRequest::clear_proposerindex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.proposerindex_ = ::uint64_t{0u};
}
inline ::uint64_t BlockFinalizeRequest::proposerindex() const {
  // @@protoc_insertion_point(field_get:block_finalize.BlockFinalizeRequest.proposerIndex)
  return _internal_proposerindex();
}
inline void BlockFinalizeRequest::set_proposerindex(::uint64_t value) {
  _internal_set_proposerindex(value);
  // @@protoc_insertion_point(field_set:block_finalize.BlockFinalizeRequest.proposerIndex)
}
inline ::uint64_t BlockFinalizeRequest::_internal_proposerindex() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.proposerindex_;
}
inline void BlockFinalizeRequest::_internal_set_proposerindex(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.proposerindex_ = value;
}

// uint64 blockID = 3;
inline void BlockFinalizeRequest::clear_blockid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.blockid_ = ::uint64_t{0u};
}
inline ::uint64_t BlockFinalizeRequest::blockid() const {
  // @@protoc_insertion_point(field_get:block_finalize.BlockFinalizeRequest.blockID)
  return _internal_blockid();
}
inline void BlockFinalizeRequest::set_blockid(::uint64_t value) {
  _internal_set_blockid(value);
  // @@protoc_insertion_point(field_set:block_finalize.BlockFinalizeRequest.blockID)
}
inline ::uint64_t BlockFinalizeRequest::_internal_blockid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.blockid_;
}
inline void BlockFinalizeRequest::_internal_set_blockid(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.blockid_ = value;
}

// uint64 nodeID = 4;
inline void BlockFinalizeRequest::clear_nodeid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nodeid_ = ::uint64_t{0u};
}
inline ::uint64_t BlockFinalizeRequest::nodeid() const {
  // @@protoc_insertion_point(field_get:block_finalize.BlockFinalizeRequest.nodeID)
  return _internal_nodeid();
}
inline void BlockFinalizeRequest::set_nodeid(::uint64_t value) {
  _internal_set_nodeid(value);
  // @@protoc_insertion_point(field_set:block_finalize.BlockFinalizeRequest.nodeID)
}
inline ::uint64_t BlockFinalizeRequest::_internal_nodeid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.nodeid_;
}
inline void BlockFinalizeRequest::_internal_set_nodeid(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nodeid_ = value;
}

// bool needDAProof = 5;
inline void BlockFinalizeRequest::clear_needdaproof() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.needdaproof_ = false;
}
inline bool BlockFinalizeRequest::needdaproof() const {
  // @@protoc_insertion_point(field_get:block_finalize.BlockFinalizeRequest.needDAProof)
  return _internal_needdaproof();
}
inline void BlockFinalizeRequest::set_needdaproof(bool value) {
  _internal_set_needdaproof(value);
  // @@protoc_insertion_point(field_set:block_finalize.BlockFinalizeRequest.needDAProof)
}
inline bool BlockFinalizeRequest::_internal_needdaproof() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.needdaproof_;
}
inline void BlockFinalizeRequest::_internal_set_needdaproof(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.needdaproof_ = value;
}

// bool needDecryptionShares = 6;
inline void BlockFinalizeRequest::clear_needdecryptionshares() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.needdecryptionshares_ = false;
}
inline bool BlockFinalizeRequest::needdecryptionshares() const {
  // @@protoc_insertion_point(field_get:block_finalize.BlockFinalizeRequest.needDecryptionShares)
  return _internal_needdecryptionshares();
}
inline void BlockFinalizeRequest::set_needdecryptionshares(bool value) {
  _internal_set_needdecryptionshares(value);
  // @@protoc_insertion_point(field_set:block_finalize.BlockFinalizeRequest.needDecryptionShares)
}
inline bool BlockFinalizeRequest::_internal_needdecryptionshares() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.needdecryptionshares_;
}
inline void BlockFinalizeRequest::_internal_set_needdecryptionshares(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.needdecryptionshares_ = value;
}

// optional uint32 fragmentIndex = 7;
inline bool BlockFinalizeRequest::has_fragmentindex() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void BlockFinalizeRequest::clear_fragmentindex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fragmentindex_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::uint32_t BlockFinalizeRequest::fragmentindex() const {
  // @@protoc_insertion_point(field_get:block_finalize.BlockFinalizeRequest.fragmentIndex)
  return _internal_fragmentindex();
}
inline void BlockFinalizeRequest::set_fragmentindex(::uint32_t value) {
  _internal_set_fragmentindex(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:block_finalize.BlockFinalizeRequest.fragmentIndex)
}
inline ::uint32_t BlockFinalizeRequest::_internal_fragmentindex() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fragmentindex_;
}
inline void BlockFinalizeRequest::_internal_set_fragmentindex(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fragmentindex_ = value;
}

// -------------------------------------------------------------------

// BlockFinalizeResponse

// .block_finalize.SuccessResponse success = 1;
inline bool BlockFinalizeResponse::has_success() const {
  return result_case() == kSuccess;
}
inline bool BlockFinalizeResponse::_internal_has_success() const {
  return result_case() == kSuccess;
}
inline void BlockFinalizeResponse::set_has_success() {
  _impl_._oneof_case_[0] = kSuccess;
}
inline void BlockFinalizeResponse::clear_success() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (result_case() == kSuccess) {
    if (GetArena() == nullptr) {
      delete _impl_.result_.success_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.result_.success_);
    }
    clear_has_result();
  }
}
inline ::block_finalize::SuccessResponse* BlockFinalizeResponse::release_success() {
  // @@protoc_insertion_point(field_release:block_finalize.BlockFinalizeResponse.success)
  if (result_case() == kSuccess) {
    clear_has_result();
    auto* temp = _impl_.result_.success_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.result_.success_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::block_finalize::SuccessResponse& BlockFinalizeResponse::_internal_success() const {
  return result_case() == kSuccess ? *_impl_.result_.success_ : reinterpret_cast<::block_finalize::SuccessResponse&>(::block_finalize::_SuccessResponse_default_instance_);
}
inline const ::block_finalize::SuccessResponse& BlockFinalizeResponse::success() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:block_finalize.BlockFinalizeResponse.success)
  return _internal_success();
}
inline ::block_finalize::SuccessResponse* BlockFinalizeResponse::unsafe_arena_release_success() {
  // @@protoc_insertion_point(field_unsafe_arena_release:block_finalize.BlockFinalizeResponse.success)
  if (result_case() == kSuccess) {
    clear_has_result();
    auto* temp = _impl_.result_.success_;
    _impl_.result_.success_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void BlockFinalizeResponse::unsafe_arena_set_allocated_success(::block_finalize::SuccessResponse* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_result();
  if (value) {
    set_has_success();
    _impl_.result_.success_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:block_finalize.BlockFinalizeResponse.success)
}
inline ::block_finalize::SuccessResponse* BlockFinalizeResponse::_internal_mutable_success() {
  if (result_case() != kSuccess) {
    clear_result();
    set_has_success();
    _impl_.result_.success_ =
        ::google::protobuf::Message::DefaultConstruct<::block_finalize::SuccessResponse>(GetArena());
  }
  return _impl_.result_.success_;
}
inline ::block_finalize::SuccessResponse* BlockFinalizeResponse::mutable_success() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::block_finalize::SuccessResponse* _msg = _internal_mutable_success();
  // @@protoc_insertion_point(field_mutable:block_finalize.BlockFinalizeResponse.success)
  return _msg;
}

// .block_finalize.ErrorResponse error = 2;
inline bool BlockFinalizeResponse::has_error() const {
  return result_case() == kError;
}
inline bool BlockFinalizeResponse::_internal_has_error() const {
  return result_case() == kError;
}
inline void BlockFinalizeResponse::set_has_error() {
  _impl_._oneof_case_[0] = kError;
}
inline void BlockFinalizeResponse::clear_error() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (result_case() == kError) {
    if (GetArena() == nullptr) {
      delete _impl_.result_.error_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.result_.error_);
    }
    clear_has_result();
  }
}
inline ::block_finalize::ErrorResponse* BlockFinalizeResponse::release_error() {
  // @@protoc_insertion_point(field_release:block_finalize.BlockFinalizeResponse.error)
  if (result_case() == kError) {
    clear_has_result();
    auto* temp = _impl_.result_.error_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.result_.error_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::block_finalize::ErrorResponse& BlockFinalizeResponse::_internal_error() const {
  return result_case() == kError ? *_impl_.result_.error_ : reinterpret_cast<::block_finalize::ErrorResponse&>(::block_finalize::_ErrorResponse_default_instance_);
}
inline const ::block_finalize::ErrorResponse& BlockFinalizeResponse::error() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:block_finalize.BlockFinalizeResponse.error)
  return _internal_error();
}
inline ::block_finalize::ErrorResponse* BlockFinalizeResponse::unsafe_arena_release_error() {
  // @@protoc_insertion_point(field_unsafe_arena_release:block_finalize.BlockFinalizeResponse.error)
  if (result_case() == kError) {
    clear_has_result();
    auto* temp = _impl_.result_.error_;
    _impl_.result_.error_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void BlockFinalizeResponse::unsafe_arena_set_allocated_error(::block_finalize::ErrorResponse* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_result();
  if (value) {
    set_has_error();
    _impl_.result_.error_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:block_finalize.BlockFinalizeResponse.error)
}
inline ::block_finalize::ErrorResponse* BlockFinalizeResponse::_internal_mutable_error() {
  if (result_case() != kError) {
    clear_result();
    set_has_error();
    _impl_.result_.error_ =
        ::google::protobuf::Message::DefaultConstruct<::block_finalize::ErrorResponse>(GetArena());
  }
  return _impl_.result_.error_;
}
inline ::block_finalize::ErrorResponse* BlockFinalizeResponse::mutable_error() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::block_finalize::ErrorResponse* _msg = _internal_mutable_error();
  // @@protoc_insertion_point(field_mutable:block_finalize.BlockFinalizeResponse.error)
  return _msg;
}

inline bool BlockFinalizeResponse::has_result() const {
  return result_case() != RESULT_NOT_SET;
}
inline void BlockFinalizeResponse::clear_has_result() {
  _impl_._oneof_case_[0] = RESULT_NOT_SET;
}
inline BlockFinalizeResponse::ResultCase BlockFinalizeResponse::result_case() const {
  return BlockFinalizeResponse::ResultCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// SuccessResponse

// string blockHash = 1;
inline void SuccessResponse::clear_blockhash() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.blockhash_.ClearToEmpty();
}
inline const std::string& SuccessResponse::blockhash() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:block_finalize.SuccessResponse.blockHash)
  return _internal_blockhash();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SuccessResponse::set_blockhash(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.blockhash_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:block_finalize.SuccessResponse.blockHash)
}
inline std::string* SuccessResponse::mutable_blockhash() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_blockhash();
  // @@protoc_insertion_point(field_mutable:block_finalize.SuccessResponse.blockHash)
  return _s;
}
inline const std::string& SuccessResponse::_internal_blockhash() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.blockhash_.Get();
}
inline void SuccessResponse::_internal_set_blockhash(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.blockhash_.Set(value, GetArena());
}
inline std::string* SuccessResponse::_internal_mutable_blockhash() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.blockhash_.Mutable( GetArena());
}
inline std::string* SuccessResponse::release_blockhash() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:block_finalize.SuccessResponse.blockHash)
  return _impl_.blockhash_.Release();
}
inline void SuccessResponse::set_allocated_blockhash(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.blockhash_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.blockhash_.IsDefault()) {
    _impl_.blockhash_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:block_finalize.SuccessResponse.blockHash)
}

// uint64 blockSize = 2;
inline void SuccessResponse::clear_blocksize() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.blocksize_ = ::uint64_t{0u};
}
inline ::uint64_t SuccessResponse::blocksize() const {
  // @@protoc_insertion_point(field_get:block_finalize.SuccessResponse.blockSize)
  return _internal_blocksize();
}
inline void SuccessResponse::set_blocksize(::uint64_t value) {
  _internal_set_blocksize(value);
  // @@protoc_insertion_point(field_set:block_finalize.SuccessResponse.blockSize)
}
inline ::uint64_t SuccessResponse::_internal_blocksize() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.blocksize_;
}
inline void SuccessResponse::_internal_set_blocksize(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.blocksize_ = value;
}

// optional string daProofSig = 3;
inline bool SuccessResponse::has_daproofsig() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void SuccessResponse::clear_daproofsig() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.daproofsig_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& SuccessResponse::daproofsig() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:block_finalize.SuccessResponse.daProofSig)
  return _internal_daproofsig();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SuccessResponse::set_daproofsig(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.daproofsig_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:block_finalize.SuccessResponse.daProofSig)
}
inline std::string* SuccessResponse::mutable_daproofsig() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_daproofsig();
  // @@protoc_insertion_point(field_mutable:block_finalize.SuccessResponse.daProofSig)
  return _s;
}
inline const std::string& SuccessResponse::_internal_daproofsig() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.daproofsig_.Get();
}
inline void SuccessResponse::_internal_set_daproofsig(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.daproofsig_.Set(value, GetArena());
}
inline std::string* SuccessResponse::_internal_mutable_daproofsig() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.daproofsig_.Mutable( GetArena());
}
inline std::string* SuccessResponse::release_daproofsig() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:block_finalize.SuccessResponse.daProofSig)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.daproofsig_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.daproofsig_.Set("", GetArena());
  }
  return released;
}
inline void SuccessResponse::set_allocated_daproofsig(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.daproofsig_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.daproofsig_.IsDefault()) {
    _impl_.daproofsig_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:block_finalize.SuccessResponse.daProofSig)
}

// optional bytes fragment = 4;
inline bool SuccessResponse::has_fragment() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void SuccessResponse::clear_fragment() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fragment_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& SuccessResponse::fragment() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:block_finalize.SuccessResponse.fragment)
  return _internal_fragment();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SuccessResponse::set_fragment(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.fragment_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:block_finalize.SuccessResponse.fragment)
}
inline std::string* SuccessResponse::mutable_fragment() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_fragment();
  // @@protoc_insertion_point(field_mutable:block_finalize.SuccessResponse.fragment)
  return _s;
}
inline const std::string& SuccessResponse::_internal_fragment() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fragment_.Get();
}
inline void SuccessResponse::_internal_set_fragment(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.fragment_.Set(value, GetArena());
}
inline std::string* SuccessResponse::_internal_mutable_fragment() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.fragment_.Mutable( GetArena());
}
inline std::string* SuccessResponse::release_fragment() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:block_finalize.SuccessResponse.fragment)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.fragment_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.fragment_.Set("", GetArena());
  }
  return released;
}
inline void SuccessResponse::set_allocated_fragment(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.fragment_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.fragment_.IsDefault()) {
    _impl_.fragment_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:block_finalize.SuccessResponse.fragment)
}

// -------------------------------------------------------------------

// ErrorResponse

// uint32 status = 1;
inline void ErrorResponse::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = 0u;
}
inline ::uint32_t ErrorResponse::status() const {
  // @@protoc_insertion_point(field_get:block_finalize.ErrorResponse.status)
  return _internal_status();
}
inline void ErrorResponse::set_status(::uint32_t value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:block_finalize.ErrorResponse.status)
}
inline ::uint32_t ErrorResponse::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.status_;
}
inline void ErrorResponse::_internal_set_status(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = value;
}

// uint32 substatus = 2;
inline void ErrorResponse::clear_substatus() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.substatus_ = 0u;
}
inline ::uint32_t ErrorResponse::substatus() const {
  // @@protoc_insertion_point(field_get:block_finalize.ErrorResponse.substatus)
  return _internal_substatus();
}
inline void ErrorResponse::set_substatus(::uint32_t value) {
  _internal_set_substatus(value);
  // @@protoc_insertion_point(field_set:block_finalize.ErrorResponse.substatus)
}
inline ::uint32_t ErrorResponse::_internal_substatus() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.substatus_;
}
inline void ErrorResponse::_internal_set_substatus(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.substatus_ = value;
}

// optional string message = 3;
inline bool ErrorResponse::has_message() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void ErrorResponse::clear_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ErrorResponse::message() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:block_finalize.ErrorResponse.message)
  return _internal_message();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ErrorResponse::set_message(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.message_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:block_finalize.ErrorResponse.message)
}
inline std::string* ErrorResponse::mutable_message() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:block_finalize.ErrorResponse.message)
  return _s;
}
inline const std::string& ErrorResponse::_internal_message() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.message_.Get();
}
inline void ErrorResponse::_internal_set_message(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.message_.Set(value, GetArena());
}
inline std::string* ErrorResponse::_internal_mutable_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.message_.Mutable( GetArena());
}
inline std::string* ErrorResponse::release_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:block_finalize.ErrorResponse.message)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.message_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.message_.Set("", GetArena());
  }
  return released;
}
inline void ErrorResponse::set_allocated_message(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.message_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:block_finalize.ErrorResponse.message)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace block_finalize


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // block_5ffinalize_2eproto_2epb_2eh
