// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_BLOCKFINALIZECOMMONSTRUCTURES_BLOCK_FINALIZE_H_
#define FLATBUFFERS_GENERATED_BLOCKFINALIZECOMMONSTRUCTURES_BLOCK_FINALIZE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace block_finalize {

struct Transaction;
struct TransactionBuilder;
struct TransactionT;

struct Hash;

struct TruncatedHash;

struct BlockHeader;

struct BlockFragment;
struct BlockFragmentBuilder;
struct BlockFragmentT;

struct DecryptionShare;
struct DecryptionShareBuilder;
struct DecryptionShareT;

struct ErrorResponse;
struct ErrorResponseBuilder;
struct ErrorResponseT;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(1) Hash FLATBUFFERS_FINAL_CLASS {
 private:
  uint8_t data_[32];

 public:
  Hash()
      : data_() {
  }
  Hash(::flatbuffers::span<const uint8_t, 32> _data) {
    ::flatbuffers::CastToArray(data_).CopyFromSpan(_data);
  }
  const ::flatbuffers::Array<uint8_t, 32> *data() const {
    return &::flatbuffers::CastToArray(data_);
  }
};
FLATBUFFERS_STRUCT_END(Hash, 32);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(1) TruncatedHash FLATBUFFERS_FINAL_CLASS {
 private:
  uint8_t data_[20];

 public:
  TruncatedHash()
      : data_() {
  }
  TruncatedHash(::flatbuffers::span<const uint8_t, 20> _data) {
    ::flatbuffers::CastToArray(data_).CopyFromSpan(_data);
  }
  const ::flatbuffers::Array<uint8_t, 20> *data() const {
    return &::flatbuffers::CastToArray(data_);
  }
};
FLATBUFFERS_STRUCT_END(TruncatedHash, 20);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) BlockHeader FLATBUFFERS_FINAL_CLASS {
 private:
  uint64_t schain_id_;
  uint64_t epoch_id_;
  uint64_t block_id_;
  uint64_t proposer_index_;
  uint64_t transaction_count_;
  uint64_t time_stamp_s_;
  uint64_t time_stamp_ms_;
  block_finalize::Hash transactions_merkle_root_;
  block_finalize::Hash parent_hash_;
  uint8_t extra_data_[32];

 public:
  BlockHeader()
      : schain_id_(0),
        epoch_id_(0),
        block_id_(0),
        proposer_index_(0),
        transaction_count_(0),
        time_stamp_s_(0),
        time_stamp_ms_(0),
        transactions_merkle_root_(),
        parent_hash_(),
        extra_data_() {
  }
  BlockHeader(uint64_t _schain_id, uint64_t _epoch_id, uint64_t _block_id, uint64_t _proposer_index, uint64_t _transaction_count, uint64_t _time_stamp_s, uint64_t _time_stamp_ms, const block_finalize::Hash &_transactions_merkle_root, const block_finalize::Hash &_parent_hash)
      : schain_id_(::flatbuffers::EndianScalar(_schain_id)),
        epoch_id_(::flatbuffers::EndianScalar(_epoch_id)),
        block_id_(::flatbuffers::EndianScalar(_block_id)),
        proposer_index_(::flatbuffers::EndianScalar(_proposer_index)),
        transaction_count_(::flatbuffers::EndianScalar(_transaction_count)),
        time_stamp_s_(::flatbuffers::EndianScalar(_time_stamp_s)),
        time_stamp_ms_(::flatbuffers::EndianScalar(_time_stamp_ms)),
        transactions_merkle_root_(_transactions_merkle_root),
        parent_hash_(_parent_hash),
        extra_data_() {
  }
  BlockHeader(uint64_t _schain_id, uint64_t _epoch_id, uint64_t _block_id, uint64_t _proposer_index, uint64_t _transaction_count, uint64_t _time_stamp_s, uint64_t _time_stamp_ms, const block_finalize::Hash &_transactions_merkle_root, const block_finalize::Hash &_parent_hash, ::flatbuffers::span<const uint8_t, 32> _extra_data)
      : schain_id_(::flatbuffers::EndianScalar(_schain_id)),
        epoch_id_(::flatbuffers::EndianScalar(_epoch_id)),
        block_id_(::flatbuffers::EndianScalar(_block_id)),
        proposer_index_(::flatbuffers::EndianScalar(_proposer_index)),
        transaction_count_(::flatbuffers::EndianScalar(_transaction_count)),
        time_stamp_s_(::flatbuffers::EndianScalar(_time_stamp_s)),
        time_stamp_ms_(::flatbuffers::EndianScalar(_time_stamp_ms)),
        transactions_merkle_root_(_transactions_merkle_root),
        parent_hash_(_parent_hash) {
    ::flatbuffers::CastToArray(extra_data_).CopyFromSpan(_extra_data);
  }
  uint64_t schain_id() const {
    return ::flatbuffers::EndianScalar(schain_id_);
  }
  uint64_t epoch_id() const {
    return ::flatbuffers::EndianScalar(epoch_id_);
  }
  uint64_t block_id() const {
    return ::flatbuffers::EndianScalar(block_id_);
  }
  uint64_t proposer_index() const {
    return ::flatbuffers::EndianScalar(proposer_index_);
  }
  uint64_t transaction_count() const {
    return ::flatbuffers::EndianScalar(transaction_count_);
  }
  uint64_t time_stamp_s() const {
    return ::flatbuffers::EndianScalar(time_stamp_s_);
  }
  uint64_t time_stamp_ms() const {
    return ::flatbuffers::EndianScalar(time_stamp_ms_);
  }
  const block_finalize::Hash &transactions_merkle_root() const {
    return transactions_merkle_root_;
  }
  const block_finalize::Hash &parent_hash() const {
    return parent_hash_;
  }
  const ::flatbuffers::Array<uint8_t, 32> *extra_data() const {
    return &::flatbuffers::CastToArray(extra_data_);
  }
};
FLATBUFFERS_STRUCT_END(BlockHeader, 152);

struct TransactionT : public ::flatbuffers::NativeTable {
  typedef Transaction TableType;
  std::vector<uint8_t> data{};
};

struct Transaction FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TransactionT NativeTableType;
  typedef TransactionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DATA = 4
  };
  const ::flatbuffers::Vector<uint8_t> *data() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_DATA);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           verifier.EndTable();
  }
  TransactionT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(TransactionT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Transaction> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const TransactionT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct TransactionBuilder {
  typedef Transaction Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_data(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data) {
    fbb_.AddOffset(Transaction::VT_DATA, data);
  }
  explicit TransactionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Transaction> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Transaction>(end);
    fbb_.Required(o, Transaction::VT_DATA);
    return o;
  }
};

inline ::flatbuffers::Offset<Transaction> CreateTransaction(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data = 0) {
  TransactionBuilder builder_(_fbb);
  builder_.add_data(data);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Transaction> CreateTransactionDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *data = nullptr) {
  auto data__ = data ? _fbb.CreateVector<uint8_t>(*data) : 0;
  return block_finalize::CreateTransaction(
      _fbb,
      data__);
}

::flatbuffers::Offset<Transaction> CreateTransaction(::flatbuffers::FlatBufferBuilder &_fbb, const TransactionT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct BlockFragmentT : public ::flatbuffers::NativeTable {
  typedef BlockFragment TableType;
  uint64_t index = 0;
  std::vector<block_finalize::TruncatedHash> tx_truncated_hashes{};
  std::vector<block_finalize::Hash> left_proof{};
  std::vector<block_finalize::Hash> right_proof{};
};

struct BlockFragment FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BlockFragmentT NativeTableType;
  typedef BlockFragmentBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_INDEX = 4,
    VT_TX_TRUNCATED_HASHES = 6,
    VT_LEFT_PROOF = 8,
    VT_RIGHT_PROOF = 10
  };
  uint64_t index() const {
    return GetField<uint64_t>(VT_INDEX, 0);
  }
  const ::flatbuffers::Vector<const block_finalize::TruncatedHash *> *tx_truncated_hashes() const {
    return GetPointer<const ::flatbuffers::Vector<const block_finalize::TruncatedHash *> *>(VT_TX_TRUNCATED_HASHES);
  }
  const ::flatbuffers::Vector<const block_finalize::Hash *> *left_proof() const {
    return GetPointer<const ::flatbuffers::Vector<const block_finalize::Hash *> *>(VT_LEFT_PROOF);
  }
  const ::flatbuffers::Vector<const block_finalize::Hash *> *right_proof() const {
    return GetPointer<const ::flatbuffers::Vector<const block_finalize::Hash *> *>(VT_RIGHT_PROOF);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_INDEX, 8) &&
           VerifyOffsetRequired(verifier, VT_TX_TRUNCATED_HASHES) &&
           verifier.VerifyVector(tx_truncated_hashes()) &&
           VerifyOffsetRequired(verifier, VT_LEFT_PROOF) &&
           verifier.VerifyVector(left_proof()) &&
           VerifyOffsetRequired(verifier, VT_RIGHT_PROOF) &&
           verifier.VerifyVector(right_proof()) &&
           verifier.EndTable();
  }
  BlockFragmentT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(BlockFragmentT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<BlockFragment> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BlockFragmentT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct BlockFragmentBuilder {
  typedef BlockFragment Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_index(uint64_t index) {
    fbb_.AddElement<uint64_t>(BlockFragment::VT_INDEX, index, 0);
  }
  void add_tx_truncated_hashes(::flatbuffers::Offset<::flatbuffers::Vector<const block_finalize::TruncatedHash *>> tx_truncated_hashes) {
    fbb_.AddOffset(BlockFragment::VT_TX_TRUNCATED_HASHES, tx_truncated_hashes);
  }
  void add_left_proof(::flatbuffers::Offset<::flatbuffers::Vector<const block_finalize::Hash *>> left_proof) {
    fbb_.AddOffset(BlockFragment::VT_LEFT_PROOF, left_proof);
  }
  void add_right_proof(::flatbuffers::Offset<::flatbuffers::Vector<const block_finalize::Hash *>> right_proof) {
    fbb_.AddOffset(BlockFragment::VT_RIGHT_PROOF, right_proof);
  }
  explicit BlockFragmentBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BlockFragment> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BlockFragment>(end);
    fbb_.Required(o, BlockFragment::VT_TX_TRUNCATED_HASHES);
    fbb_.Required(o, BlockFragment::VT_LEFT_PROOF);
    fbb_.Required(o, BlockFragment::VT_RIGHT_PROOF);
    return o;
  }
};

inline ::flatbuffers::Offset<BlockFragment> CreateBlockFragment(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t index = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const block_finalize::TruncatedHash *>> tx_truncated_hashes = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const block_finalize::Hash *>> left_proof = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const block_finalize::Hash *>> right_proof = 0) {
  BlockFragmentBuilder builder_(_fbb);
  builder_.add_index(index);
  builder_.add_right_proof(right_proof);
  builder_.add_left_proof(left_proof);
  builder_.add_tx_truncated_hashes(tx_truncated_hashes);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<BlockFragment> CreateBlockFragmentDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t index = 0,
    const std::vector<block_finalize::TruncatedHash> *tx_truncated_hashes = nullptr,
    const std::vector<block_finalize::Hash> *left_proof = nullptr,
    const std::vector<block_finalize::Hash> *right_proof = nullptr) {
  auto tx_truncated_hashes__ = tx_truncated_hashes ? _fbb.CreateVectorOfStructs<block_finalize::TruncatedHash>(*tx_truncated_hashes) : 0;
  auto left_proof__ = left_proof ? _fbb.CreateVectorOfStructs<block_finalize::Hash>(*left_proof) : 0;
  auto right_proof__ = right_proof ? _fbb.CreateVectorOfStructs<block_finalize::Hash>(*right_proof) : 0;
  return block_finalize::CreateBlockFragment(
      _fbb,
      index,
      tx_truncated_hashes__,
      left_proof__,
      right_proof__);
}

::flatbuffers::Offset<BlockFragment> CreateBlockFragment(::flatbuffers::FlatBufferBuilder &_fbb, const BlockFragmentT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct DecryptionShareT : public ::flatbuffers::NativeTable {
  typedef DecryptionShare TableType;
  uint64_t transaction_index = 0;
  std::vector<uint8_t> data{};
};

struct DecryptionShare FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DecryptionShareT NativeTableType;
  typedef DecryptionShareBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TRANSACTION_INDEX = 4,
    VT_DATA = 6
  };
  uint64_t transaction_index() const {
    return GetField<uint64_t>(VT_TRANSACTION_INDEX, 0);
  }
  const ::flatbuffers::Vector<uint8_t> *data() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_DATA);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_TRANSACTION_INDEX, 8) &&
           VerifyOffsetRequired(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           verifier.EndTable();
  }
  DecryptionShareT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(DecryptionShareT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<DecryptionShare> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DecryptionShareT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct DecryptionShareBuilder {
  typedef DecryptionShare Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_transaction_index(uint64_t transaction_index) {
    fbb_.AddElement<uint64_t>(DecryptionShare::VT_TRANSACTION_INDEX, transaction_index, 0);
  }
  void add_data(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data) {
    fbb_.AddOffset(DecryptionShare::VT_DATA, data);
  }
  explicit DecryptionShareBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DecryptionShare> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DecryptionShare>(end);
    fbb_.Required(o, DecryptionShare::VT_DATA);
    return o;
  }
};

inline ::flatbuffers::Offset<DecryptionShare> CreateDecryptionShare(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t transaction_index = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data = 0) {
  DecryptionShareBuilder builder_(_fbb);
  builder_.add_transaction_index(transaction_index);
  builder_.add_data(data);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DecryptionShare> CreateDecryptionShareDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t transaction_index = 0,
    const std::vector<uint8_t> *data = nullptr) {
  auto data__ = data ? _fbb.CreateVector<uint8_t>(*data) : 0;
  return block_finalize::CreateDecryptionShare(
      _fbb,
      transaction_index,
      data__);
}

::flatbuffers::Offset<DecryptionShare> CreateDecryptionShare(::flatbuffers::FlatBufferBuilder &_fbb, const DecryptionShareT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ErrorResponseT : public ::flatbuffers::NativeTable {
  typedef ErrorResponse TableType;
  uint32_t status = 0;
  uint32_t substatus = 0;
  std::string message{};
};

struct ErrorResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ErrorResponseT NativeTableType;
  typedef ErrorResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_STATUS = 4,
    VT_SUBSTATUS = 6,
    VT_MESSAGE = 8
  };
  uint32_t status() const {
    return GetField<uint32_t>(VT_STATUS, 0);
  }
  uint32_t substatus() const {
    return GetField<uint32_t>(VT_SUBSTATUS, 0);
  }
  const ::flatbuffers::String *message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MESSAGE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_STATUS, 4) &&
           VerifyField<uint32_t>(verifier, VT_SUBSTATUS, 4) &&
           VerifyOffsetRequired(verifier, VT_MESSAGE) &&
           verifier.VerifyString(message()) &&
           verifier.EndTable();
  }
  ErrorResponseT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ErrorResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ErrorResponse> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ErrorResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ErrorResponseBuilder {
  typedef ErrorResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_status(uint32_t status) {
    fbb_.AddElement<uint32_t>(ErrorResponse::VT_STATUS, status, 0);
  }
  void add_substatus(uint32_t substatus) {
    fbb_.AddElement<uint32_t>(ErrorResponse::VT_SUBSTATUS, substatus, 0);
  }
  void add_message(::flatbuffers::Offset<::flatbuffers::String> message) {
    fbb_.AddOffset(ErrorResponse::VT_MESSAGE, message);
  }
  explicit ErrorResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ErrorResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ErrorResponse>(end);
    fbb_.Required(o, ErrorResponse::VT_MESSAGE);
    return o;
  }
};

inline ::flatbuffers::Offset<ErrorResponse> CreateErrorResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t status = 0,
    uint32_t substatus = 0,
    ::flatbuffers::Offset<::flatbuffers::String> message = 0) {
  ErrorResponseBuilder builder_(_fbb);
  builder_.add_message(message);
  builder_.add_substatus(substatus);
  builder_.add_status(status);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ErrorResponse> CreateErrorResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t status = 0,
    uint32_t substatus = 0,
    const char *message = nullptr) {
  auto message__ = message ? _fbb.CreateString(message) : 0;
  return block_finalize::CreateErrorResponse(
      _fbb,
      status,
      substatus,
      message__);
}

::flatbuffers::Offset<ErrorResponse> CreateErrorResponse(::flatbuffers::FlatBufferBuilder &_fbb, const ErrorResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline TransactionT *Transaction::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<TransactionT>(new TransactionT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Transaction::UnPackTo(TransactionT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = data(); if (_e) { _o->data.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->data.begin()); } }
}

inline ::flatbuffers::Offset<Transaction> Transaction::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const TransactionT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateTransaction(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Transaction> CreateTransaction(::flatbuffers::FlatBufferBuilder &_fbb, const TransactionT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const TransactionT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _data = _fbb.CreateVector(_o->data);
  return block_finalize::CreateTransaction(
      _fbb,
      _data);
}

inline BlockFragmentT *BlockFragment::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<BlockFragmentT>(new BlockFragmentT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void BlockFragment::UnPackTo(BlockFragmentT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = index(); _o->index = _e; }
  { auto _e = tx_truncated_hashes(); if (_e) { _o->tx_truncated_hashes.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->tx_truncated_hashes[_i] = *_e->Get(_i); } } else { _o->tx_truncated_hashes.resize(0); } }
  { auto _e = left_proof(); if (_e) { _o->left_proof.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->left_proof[_i] = *_e->Get(_i); } } else { _o->left_proof.resize(0); } }
  { auto _e = right_proof(); if (_e) { _o->right_proof.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->right_proof[_i] = *_e->Get(_i); } } else { _o->right_proof.resize(0); } }
}

inline ::flatbuffers::Offset<BlockFragment> BlockFragment::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BlockFragmentT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateBlockFragment(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<BlockFragment> CreateBlockFragment(::flatbuffers::FlatBufferBuilder &_fbb, const BlockFragmentT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const BlockFragmentT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _index = _o->index;
  auto _tx_truncated_hashes = _fbb.CreateVectorOfStructs(_o->tx_truncated_hashes);
  auto _left_proof = _fbb.CreateVectorOfStructs(_o->left_proof);
  auto _right_proof = _fbb.CreateVectorOfStructs(_o->right_proof);
  return block_finalize::CreateBlockFragment(
      _fbb,
      _index,
      _tx_truncated_hashes,
      _left_proof,
      _right_proof);
}

inline DecryptionShareT *DecryptionShare::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<DecryptionShareT>(new DecryptionShareT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void DecryptionShare::UnPackTo(DecryptionShareT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = transaction_index(); _o->transaction_index = _e; }
  { auto _e = data(); if (_e) { _o->data.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->data.begin()); } }
}

inline ::flatbuffers::Offset<DecryptionShare> DecryptionShare::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DecryptionShareT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateDecryptionShare(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<DecryptionShare> CreateDecryptionShare(::flatbuffers::FlatBufferBuilder &_fbb, const DecryptionShareT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const DecryptionShareT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _transaction_index = _o->transaction_index;
  auto _data = _fbb.CreateVector(_o->data);
  return block_finalize::CreateDecryptionShare(
      _fbb,
      _transaction_index,
      _data);
}

inline ErrorResponseT *ErrorResponse::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ErrorResponseT>(new ErrorResponseT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ErrorResponse::UnPackTo(ErrorResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = status(); _o->status = _e; }
  { auto _e = substatus(); _o->substatus = _e; }
  { auto _e = message(); if (_e) _o->message = _e->str(); }
}

inline ::flatbuffers::Offset<ErrorResponse> ErrorResponse::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ErrorResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateErrorResponse(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ErrorResponse> CreateErrorResponse(::flatbuffers::FlatBufferBuilder &_fbb, const ErrorResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ErrorResponseT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _status = _o->status;
  auto _substatus = _o->substatus;
  auto _message = _fbb.CreateString(_o->message);
  return block_finalize::CreateErrorResponse(
      _fbb,
      _status,
      _substatus,
      _message);
}

}  // namespace block_finalize

#endif  // FLATBUFFERS_GENERATED_BLOCKFINALIZECOMMONSTRUCTURES_BLOCK_FINALIZE_H_
