// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_BLOCKTRANSACTIONSRESPONSE_BLOCK_FINALIZE_H_
#define FLATBUFFERS_GENERATED_BLOCKTRANSACTIONSRESPONSE_BLOCK_FINALIZE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "block_finalize_common_structures_generated.h"

namespace block_finalize {

struct BlockTransactionsSuccessResponse;
struct BlockTransactionsSuccessResponseBuilder;
struct BlockTransactionsSuccessResponseT;

struct BlockTransactionsResponse;
struct BlockTransactionsResponseBuilder;
struct BlockTransactionsResponseT;

enum BlockTransactionsResult : uint8_t {
  BlockTransactionsResult_NONE = 0,
  BlockTransactionsResult_BlockTransactionsSuccessResponse = 1,
  BlockTransactionsResult_ErrorResponse = 2,
  BlockTransactionsResult_MIN = BlockTransactionsResult_NONE,
  BlockTransactionsResult_MAX = BlockTransactionsResult_ErrorResponse
};

inline const BlockTransactionsResult (&EnumValuesBlockTransactionsResult())[3] {
  static const BlockTransactionsResult values[] = {
    BlockTransactionsResult_NONE,
    BlockTransactionsResult_BlockTransactionsSuccessResponse,
    BlockTransactionsResult_ErrorResponse
  };
  return values;
}

inline const char * const *EnumNamesBlockTransactionsResult() {
  static const char * const names[4] = {
    "NONE",
    "BlockTransactionsSuccessResponse",
    "ErrorResponse",
    nullptr
  };
  return names;
}

inline const char *EnumNameBlockTransactionsResult(BlockTransactionsResult e) {
  if (::flatbuffers::IsOutRange(e, BlockTransactionsResult_NONE, BlockTransactionsResult_ErrorResponse)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesBlockTransactionsResult()[index];
}

template<typename T> struct BlockTransactionsResultTraits {
  static const BlockTransactionsResult enum_value = BlockTransactionsResult_NONE;
};

template<> struct BlockTransactionsResultTraits<block_finalize::BlockTransactionsSuccessResponse> {
  static const BlockTransactionsResult enum_value = BlockTransactionsResult_BlockTransactionsSuccessResponse;
};

template<> struct BlockTransactionsResultTraits<block_finalize::ErrorResponse> {
  static const BlockTransactionsResult enum_value = BlockTransactionsResult_ErrorResponse;
};

template<typename T> struct BlockTransactionsResultUnionTraits {
  static const BlockTransactionsResult enum_value = BlockTransactionsResult_NONE;
};

template<> struct BlockTransactionsResultUnionTraits<block_finalize::BlockTransactionsSuccessResponseT> {
  static const BlockTransactionsResult enum_value = BlockTransactionsResult_BlockTransactionsSuccessResponse;
};

template<> struct BlockTransactionsResultUnionTraits<block_finalize::ErrorResponseT> {
  static const BlockTransactionsResult enum_value = BlockTransactionsResult_ErrorResponse;
};

struct BlockTransactionsResultUnion {
  BlockTransactionsResult type;
  void *value;

  BlockTransactionsResultUnion() : type(BlockTransactionsResult_NONE), value(nullptr) {}
  BlockTransactionsResultUnion(BlockTransactionsResultUnion&& u) FLATBUFFERS_NOEXCEPT :
    type(BlockTransactionsResult_NONE), value(nullptr)
    { std::swap(type, u.type); std::swap(value, u.value); }
  BlockTransactionsResultUnion(const BlockTransactionsResultUnion &);
  BlockTransactionsResultUnion &operator=(const BlockTransactionsResultUnion &u)
    { BlockTransactionsResultUnion t(u); std::swap(type, t.type); std::swap(value, t.value); return *this; }
  BlockTransactionsResultUnion &operator=(BlockTransactionsResultUnion &&u) FLATBUFFERS_NOEXCEPT
    { std::swap(type, u.type); std::swap(value, u.value); return *this; }
  ~BlockTransactionsResultUnion() { Reset(); }

  void Reset();

  template <typename T>
  void Set(T&& val) {
    typedef typename std::remove_reference<T>::type RT;
    Reset();
    type = BlockTransactionsResultUnionTraits<RT>::enum_value;
    if (type != BlockTransactionsResult_NONE) {
      value = new RT(std::forward<T>(val));
    }
  }

  static void *UnPack(const void *obj, BlockTransactionsResult type, const ::flatbuffers::resolver_function_t *resolver);
  ::flatbuffers::Offset<void> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr) const;

  block_finalize::BlockTransactionsSuccessResponseT *AsBlockTransactionsSuccessResponse() {
    return type == BlockTransactionsResult_BlockTransactionsSuccessResponse ?
      reinterpret_cast<block_finalize::BlockTransactionsSuccessResponseT *>(value) : nullptr;
  }
  const block_finalize::BlockTransactionsSuccessResponseT *AsBlockTransactionsSuccessResponse() const {
    return type == BlockTransactionsResult_BlockTransactionsSuccessResponse ?
      reinterpret_cast<const block_finalize::BlockTransactionsSuccessResponseT *>(value) : nullptr;
  }
  block_finalize::ErrorResponseT *AsErrorResponse() {
    return type == BlockTransactionsResult_ErrorResponse ?
      reinterpret_cast<block_finalize::ErrorResponseT *>(value) : nullptr;
  }
  const block_finalize::ErrorResponseT *AsErrorResponse() const {
    return type == BlockTransactionsResult_ErrorResponse ?
      reinterpret_cast<const block_finalize::ErrorResponseT *>(value) : nullptr;
  }
};

bool VerifyBlockTransactionsResult(::flatbuffers::Verifier &verifier, const void *obj, BlockTransactionsResult type);
bool VerifyBlockTransactionsResultVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct BlockTransactionsSuccessResponseT : public ::flatbuffers::NativeTable {
  typedef BlockTransactionsSuccessResponse TableType;
  std::vector<std::unique_ptr<block_finalize::TransactionT>> transactions{};
  BlockTransactionsSuccessResponseT() = default;
  BlockTransactionsSuccessResponseT(const BlockTransactionsSuccessResponseT &o);
  BlockTransactionsSuccessResponseT(BlockTransactionsSuccessResponseT&&) FLATBUFFERS_NOEXCEPT = default;
  BlockTransactionsSuccessResponseT &operator=(BlockTransactionsSuccessResponseT o) FLATBUFFERS_NOEXCEPT;
};

struct BlockTransactionsSuccessResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BlockTransactionsSuccessResponseT NativeTableType;
  typedef BlockTransactionsSuccessResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TRANSACTIONS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<block_finalize::Transaction>> *transactions() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<block_finalize::Transaction>> *>(VT_TRANSACTIONS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TRANSACTIONS) &&
           verifier.VerifyVector(transactions()) &&
           verifier.VerifyVectorOfTables(transactions()) &&
           verifier.EndTable();
  }
  BlockTransactionsSuccessResponseT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(BlockTransactionsSuccessResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<BlockTransactionsSuccessResponse> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BlockTransactionsSuccessResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct BlockTransactionsSuccessResponseBuilder {
  typedef BlockTransactionsSuccessResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_transactions(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<block_finalize::Transaction>>> transactions) {
    fbb_.AddOffset(BlockTransactionsSuccessResponse::VT_TRANSACTIONS, transactions);
  }
  explicit BlockTransactionsSuccessResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BlockTransactionsSuccessResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BlockTransactionsSuccessResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BlockTransactionsSuccessResponse> CreateBlockTransactionsSuccessResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<block_finalize::Transaction>>> transactions = 0) {
  BlockTransactionsSuccessResponseBuilder builder_(_fbb);
  builder_.add_transactions(transactions);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<BlockTransactionsSuccessResponse> CreateBlockTransactionsSuccessResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<block_finalize::Transaction>> *transactions = nullptr) {
  auto transactions__ = transactions ? _fbb.CreateVector<::flatbuffers::Offset<block_finalize::Transaction>>(*transactions) : 0;
  return block_finalize::CreateBlockTransactionsSuccessResponse(
      _fbb,
      transactions__);
}

::flatbuffers::Offset<BlockTransactionsSuccessResponse> CreateBlockTransactionsSuccessResponse(::flatbuffers::FlatBufferBuilder &_fbb, const BlockTransactionsSuccessResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct BlockTransactionsResponseT : public ::flatbuffers::NativeTable {
  typedef BlockTransactionsResponse TableType;
  block_finalize::BlockTransactionsResultUnion result{};
};

struct BlockTransactionsResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BlockTransactionsResponseT NativeTableType;
  typedef BlockTransactionsResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RESULT_TYPE = 4,
    VT_RESULT = 6
  };
  block_finalize::BlockTransactionsResult result_type() const {
    return static_cast<block_finalize::BlockTransactionsResult>(GetField<uint8_t>(VT_RESULT_TYPE, 0));
  }
  const void *result() const {
    return GetPointer<const void *>(VT_RESULT);
  }
  template<typename T> const T *result_as() const;
  const block_finalize::BlockTransactionsSuccessResponse *result_as_BlockTransactionsSuccessResponse() const {
    return result_type() == block_finalize::BlockTransactionsResult_BlockTransactionsSuccessResponse ? static_cast<const block_finalize::BlockTransactionsSuccessResponse *>(result()) : nullptr;
  }
  const block_finalize::ErrorResponse *result_as_ErrorResponse() const {
    return result_type() == block_finalize::BlockTransactionsResult_ErrorResponse ? static_cast<const block_finalize::ErrorResponse *>(result()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_RESULT_TYPE, 1) &&
           VerifyOffset(verifier, VT_RESULT) &&
           VerifyBlockTransactionsResult(verifier, result(), result_type()) &&
           verifier.EndTable();
  }
  BlockTransactionsResponseT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(BlockTransactionsResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<BlockTransactionsResponse> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BlockTransactionsResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

template<> inline const block_finalize::BlockTransactionsSuccessResponse *BlockTransactionsResponse::result_as<block_finalize::BlockTransactionsSuccessResponse>() const {
  return result_as_BlockTransactionsSuccessResponse();
}

template<> inline const block_finalize::ErrorResponse *BlockTransactionsResponse::result_as<block_finalize::ErrorResponse>() const {
  return result_as_ErrorResponse();
}

struct BlockTransactionsResponseBuilder {
  typedef BlockTransactionsResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_result_type(block_finalize::BlockTransactionsResult result_type) {
    fbb_.AddElement<uint8_t>(BlockTransactionsResponse::VT_RESULT_TYPE, static_cast<uint8_t>(result_type), 0);
  }
  void add_result(::flatbuffers::Offset<void> result) {
    fbb_.AddOffset(BlockTransactionsResponse::VT_RESULT, result);
  }
  explicit BlockTransactionsResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BlockTransactionsResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BlockTransactionsResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BlockTransactionsResponse> CreateBlockTransactionsResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    block_finalize::BlockTransactionsResult result_type = block_finalize::BlockTransactionsResult_NONE,
    ::flatbuffers::Offset<void> result = 0) {
  BlockTransactionsResponseBuilder builder_(_fbb);
  builder_.add_result(result);
  builder_.add_result_type(result_type);
  return builder_.Finish();
}

::flatbuffers::Offset<BlockTransactionsResponse> CreateBlockTransactionsResponse(::flatbuffers::FlatBufferBuilder &_fbb, const BlockTransactionsResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline BlockTransactionsSuccessResponseT::BlockTransactionsSuccessResponseT(const BlockTransactionsSuccessResponseT &o) {
  transactions.reserve(o.transactions.size());
  for (const auto &transactions_ : o.transactions) { transactions.emplace_back((transactions_) ? new block_finalize::TransactionT(*transactions_) : nullptr); }
}

inline BlockTransactionsSuccessResponseT &BlockTransactionsSuccessResponseT::operator=(BlockTransactionsSuccessResponseT o) FLATBUFFERS_NOEXCEPT {
  std::swap(transactions, o.transactions);
  return *this;
}

inline BlockTransactionsSuccessResponseT *BlockTransactionsSuccessResponse::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<BlockTransactionsSuccessResponseT>(new BlockTransactionsSuccessResponseT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void BlockTransactionsSuccessResponse::UnPackTo(BlockTransactionsSuccessResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = transactions(); if (_e) { _o->transactions.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->transactions[_i]) { _e->Get(_i)->UnPackTo(_o->transactions[_i].get(), _resolver); } else { _o->transactions[_i] = std::unique_ptr<block_finalize::TransactionT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->transactions.resize(0); } }
}

inline ::flatbuffers::Offset<BlockTransactionsSuccessResponse> BlockTransactionsSuccessResponse::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BlockTransactionsSuccessResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateBlockTransactionsSuccessResponse(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<BlockTransactionsSuccessResponse> CreateBlockTransactionsSuccessResponse(::flatbuffers::FlatBufferBuilder &_fbb, const BlockTransactionsSuccessResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const BlockTransactionsSuccessResponseT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _transactions = _o->transactions.size() ? _fbb.CreateVector<::flatbuffers::Offset<block_finalize::Transaction>> (_o->transactions.size(), [](size_t i, _VectorArgs *__va) { return CreateTransaction(*__va->__fbb, __va->__o->transactions[i].get(), __va->__rehasher); }, &_va ) : 0;
  return block_finalize::CreateBlockTransactionsSuccessResponse(
      _fbb,
      _transactions);
}

inline BlockTransactionsResponseT *BlockTransactionsResponse::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<BlockTransactionsResponseT>(new BlockTransactionsResponseT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void BlockTransactionsResponse::UnPackTo(BlockTransactionsResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = result_type(); _o->result.type = _e; }
  { auto _e = result(); if (_e) _o->result.value = block_finalize::BlockTransactionsResultUnion::UnPack(_e, result_type(), _resolver); }
}

inline ::flatbuffers::Offset<BlockTransactionsResponse> BlockTransactionsResponse::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BlockTransactionsResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateBlockTransactionsResponse(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<BlockTransactionsResponse> CreateBlockTransactionsResponse(::flatbuffers::FlatBufferBuilder &_fbb, const BlockTransactionsResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const BlockTransactionsResponseT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _result_type = _o->result.type;
  auto _result = _o->result.Pack(_fbb);
  return block_finalize::CreateBlockTransactionsResponse(
      _fbb,
      _result_type,
      _result);
}

inline bool VerifyBlockTransactionsResult(::flatbuffers::Verifier &verifier, const void *obj, BlockTransactionsResult type) {
  switch (type) {
    case BlockTransactionsResult_NONE: {
      return true;
    }
    case BlockTransactionsResult_BlockTransactionsSuccessResponse: {
      auto ptr = reinterpret_cast<const block_finalize::BlockTransactionsSuccessResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case BlockTransactionsResult_ErrorResponse: {
      auto ptr = reinterpret_cast<const block_finalize::ErrorResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyBlockTransactionsResultVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyBlockTransactionsResult(
        verifier,  values->Get(i), types->GetEnum<BlockTransactionsResult>(i))) {
      return false;
    }
  }
  return true;
}

inline void *BlockTransactionsResultUnion::UnPack(const void *obj, BlockTransactionsResult type, const ::flatbuffers::resolver_function_t *resolver) {
  (void)resolver;
  switch (type) {
    case BlockTransactionsResult_BlockTransactionsSuccessResponse: {
      auto ptr = reinterpret_cast<const block_finalize::BlockTransactionsSuccessResponse *>(obj);
      return ptr->UnPack(resolver);
    }
    case BlockTransactionsResult_ErrorResponse: {
      auto ptr = reinterpret_cast<const block_finalize::ErrorResponse *>(obj);
      return ptr->UnPack(resolver);
    }
    default: return nullptr;
  }
}

inline ::flatbuffers::Offset<void> BlockTransactionsResultUnion::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher) const {
  (void)_rehasher;
  switch (type) {
    case BlockTransactionsResult_BlockTransactionsSuccessResponse: {
      auto ptr = reinterpret_cast<const block_finalize::BlockTransactionsSuccessResponseT *>(value);
      return CreateBlockTransactionsSuccessResponse(_fbb, ptr, _rehasher).Union();
    }
    case BlockTransactionsResult_ErrorResponse: {
      auto ptr = reinterpret_cast<const block_finalize::ErrorResponseT *>(value);
      return CreateErrorResponse(_fbb, ptr, _rehasher).Union();
    }
    default: return 0;
  }
}

inline BlockTransactionsResultUnion::BlockTransactionsResultUnion(const BlockTransactionsResultUnion &u) : type(u.type), value(nullptr) {
  switch (type) {
    case BlockTransactionsResult_BlockTransactionsSuccessResponse: {
      value = new block_finalize::BlockTransactionsSuccessResponseT(*reinterpret_cast<block_finalize::BlockTransactionsSuccessResponseT *>(u.value));
      break;
    }
    case BlockTransactionsResult_ErrorResponse: {
      value = new block_finalize::ErrorResponseT(*reinterpret_cast<block_finalize::ErrorResponseT *>(u.value));
      break;
    }
    default:
      break;
  }
}

inline void BlockTransactionsResultUnion::Reset() {
  switch (type) {
    case BlockTransactionsResult_BlockTransactionsSuccessResponse: {
      auto ptr = reinterpret_cast<block_finalize::BlockTransactionsSuccessResponseT *>(value);
      delete ptr;
      break;
    }
    case BlockTransactionsResult_ErrorResponse: {
      auto ptr = reinterpret_cast<block_finalize::ErrorResponseT *>(value);
      delete ptr;
      break;
    }
    default: break;
  }
  value = nullptr;
  type = BlockTransactionsResult_NONE;
}

inline const block_finalize::BlockTransactionsResponse *GetBlockTransactionsResponse(const void *buf) {
  return ::flatbuffers::GetRoot<block_finalize::BlockTransactionsResponse>(buf);
}

inline const block_finalize::BlockTransactionsResponse *GetSizePrefixedBlockTransactionsResponse(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<block_finalize::BlockTransactionsResponse>(buf);
}

inline bool VerifyBlockTransactionsResponseBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<block_finalize::BlockTransactionsResponse>(nullptr);
}

inline bool VerifySizePrefixedBlockTransactionsResponseBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<block_finalize::BlockTransactionsResponse>(nullptr);
}

inline void FinishBlockTransactionsResponseBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<block_finalize::BlockTransactionsResponse> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedBlockTransactionsResponseBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<block_finalize::BlockTransactionsResponse> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<block_finalize::BlockTransactionsResponseT> UnPackBlockTransactionsResponse(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<block_finalize::BlockTransactionsResponseT>(GetBlockTransactionsResponse(buf)->UnPack(res));
}

inline std::unique_ptr<block_finalize::BlockTransactionsResponseT> UnPackSizePrefixedBlockTransactionsResponse(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<block_finalize::BlockTransactionsResponseT>(GetSizePrefixedBlockTransactionsResponse(buf)->UnPack(res));
}

}  // namespace block_finalize

#endif  // FLATBUFFERS_GENERATED_BLOCKTRANSACTIONSRESPONSE_BLOCK_FINALIZE_H_
