namespace block_finalize;

// BlockFinalizeRequest
// Represents a request to finalize a block

table BlockFinalizeRequest {
  schain_id: uint64;
  epoch_id: uint64;
  block_id: uint64;
  node_id: uint64;
  proposer_index: uint64;
  need_da_proof: bool;
  need_decryption_shares: bool;
  fragment_index: uint64;
}


struct TruncatedHash {
    data: [ubyte:20] ;
}



table MerkleProof {
    data: [ubyte] (required);
}



table BlockFragment {
    index: uint64;
    data: [ubyte] (required);
    merkle_proof: [MerkleProof] (required);
}


table DAProof {
    data: [ubyte] (required);
}


table DecryptionShare {
    transaction_index : uint64;
    data: [ubyte] (required);
}

// SuccessResponse
// Represents a successful block finalization

table SuccessResponse {
  block_hash: [ubyte];
  block_size: uint64;
  da_proof:  DAProof;
  block_fragment: BlockFragment;
}

// ErrorResponse
// Represents an error response

table ErrorResponse {
  status: uint;
  substatus: uint;
  message: string (required);
}

// BlockFinalizeResponse
// Contains either a success or an error response

table BlockFinalizeResponse {
  success: SuccessResponse;
  error: ErrorResponse;
}

// Root Service Request and Response
table BlockFinalizeService {
  request: BlockFinalizeRequest;
  response: BlockFinalizeResponse;
}

root_type BlockFinalizeService;