// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: block_finalize.proto
// Protobuf C++ Version: 5.29.0

#include "block_finalize.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace block_finalize {

inline constexpr SuccessResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        blockhash_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        daproofsig_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        fragment_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        blocksize_{::uint64_t{0u}} {}

template <typename>
PROTOBUF_CONSTEXPR SuccessResponse::SuccessResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SuccessResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SuccessResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SuccessResponseDefaultTypeInternal() {}
  union {
    SuccessResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SuccessResponseDefaultTypeInternal _SuccessResponse_default_instance_;

inline constexpr ErrorResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        status_{0u},
        substatus_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR ErrorResponse::ErrorResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ErrorResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ErrorResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ErrorResponseDefaultTypeInternal() {}
  union {
    ErrorResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ErrorResponseDefaultTypeInternal _ErrorResponse_default_instance_;

inline constexpr BlockFinalizeRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        schainid_{::uint64_t{0u}},
        proposerindex_{::uint64_t{0u}},
        blockid_{::uint64_t{0u}},
        nodeid_{::uint64_t{0u}},
        needdaproof_{false},
        needdecryptionshares_{false},
        fragmentindex_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR BlockFinalizeRequest::BlockFinalizeRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct BlockFinalizeRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BlockFinalizeRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BlockFinalizeRequestDefaultTypeInternal() {}
  union {
    BlockFinalizeRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BlockFinalizeRequestDefaultTypeInternal _BlockFinalizeRequest_default_instance_;

inline constexpr BlockFinalizeResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : result_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR BlockFinalizeResponse::BlockFinalizeResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct BlockFinalizeResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BlockFinalizeResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BlockFinalizeResponseDefaultTypeInternal() {}
  union {
    BlockFinalizeResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BlockFinalizeResponseDefaultTypeInternal _BlockFinalizeResponse_default_instance_;
}  // namespace block_finalize
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_block_5ffinalize_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_block_5ffinalize_2eproto = nullptr;
const ::uint32_t
    TableStruct_block_5ffinalize_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::block_finalize::BlockFinalizeRequest, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::block_finalize::BlockFinalizeRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::block_finalize::BlockFinalizeRequest, _impl_.schainid_),
        PROTOBUF_FIELD_OFFSET(::block_finalize::BlockFinalizeRequest, _impl_.proposerindex_),
        PROTOBUF_FIELD_OFFSET(::block_finalize::BlockFinalizeRequest, _impl_.blockid_),
        PROTOBUF_FIELD_OFFSET(::block_finalize::BlockFinalizeRequest, _impl_.nodeid_),
        PROTOBUF_FIELD_OFFSET(::block_finalize::BlockFinalizeRequest, _impl_.needdaproof_),
        PROTOBUF_FIELD_OFFSET(::block_finalize::BlockFinalizeRequest, _impl_.needdecryptionshares_),
        PROTOBUF_FIELD_OFFSET(::block_finalize::BlockFinalizeRequest, _impl_.fragmentindex_),
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        0,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::block_finalize::BlockFinalizeResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        PROTOBUF_FIELD_OFFSET(::block_finalize::BlockFinalizeResponse, _impl_._oneof_case_[0]),
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        PROTOBUF_FIELD_OFFSET(::block_finalize::BlockFinalizeResponse, _impl_.result_),
        PROTOBUF_FIELD_OFFSET(::block_finalize::SuccessResponse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::block_finalize::SuccessResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::block_finalize::SuccessResponse, _impl_.blockhash_),
        PROTOBUF_FIELD_OFFSET(::block_finalize::SuccessResponse, _impl_.blocksize_),
        PROTOBUF_FIELD_OFFSET(::block_finalize::SuccessResponse, _impl_.daproofsig_),
        PROTOBUF_FIELD_OFFSET(::block_finalize::SuccessResponse, _impl_.fragment_),
        ~0u,
        ~0u,
        0,
        1,
        PROTOBUF_FIELD_OFFSET(::block_finalize::ErrorResponse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::block_finalize::ErrorResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::block_finalize::ErrorResponse, _impl_.status_),
        PROTOBUF_FIELD_OFFSET(::block_finalize::ErrorResponse, _impl_.substatus_),
        PROTOBUF_FIELD_OFFSET(::block_finalize::ErrorResponse, _impl_.message_),
        ~0u,
        ~0u,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 15, -1, sizeof(::block_finalize::BlockFinalizeRequest)},
        {22, -1, -1, sizeof(::block_finalize::BlockFinalizeResponse)},
        {33, 45, -1, sizeof(::block_finalize::SuccessResponse)},
        {49, 60, -1, sizeof(::block_finalize::ErrorResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::block_finalize::_BlockFinalizeRequest_default_instance_._instance,
    &::block_finalize::_BlockFinalizeResponse_default_instance_._instance,
    &::block_finalize::_SuccessResponse_default_instance_._instance,
    &::block_finalize::_ErrorResponse_default_instance_._instance,
};
const char descriptor_table_protodef_block_5ffinalize_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\024block_finalize.proto\022\016block_finalize\"\301"
    "\001\n\024BlockFinalizeRequest\022\020\n\010schainID\030\001 \001("
    "\004\022\025\n\rproposerIndex\030\002 \001(\004\022\017\n\007blockID\030\003 \001("
    "\004\022\016\n\006nodeID\030\004 \001(\004\022\023\n\013needDAProof\030\005 \001(\010\022\034"
    "\n\024needDecryptionShares\030\006 \001(\010\022\032\n\rfragment"
    "Index\030\007 \001(\rH\000\210\001\001B\020\n\016_fragmentIndex\"\205\001\n\025B"
    "lockFinalizeResponse\0222\n\007success\030\001 \001(\0132\037."
    "block_finalize.SuccessResponseH\000\022.\n\005erro"
    "r\030\002 \001(\0132\035.block_finalize.ErrorResponseH\000"
    "B\010\n\006result\"\203\001\n\017SuccessResponse\022\021\n\tblockH"
    "ash\030\001 \001(\t\022\021\n\tblockSize\030\002 \001(\004\022\027\n\ndaProofS"
    "ig\030\003 \001(\tH\000\210\001\001\022\025\n\010fragment\030\004 \001(\014H\001\210\001\001B\r\n\013"
    "_daProofSigB\013\n\t_fragment\"T\n\rErrorRespons"
    "e\022\016\n\006status\030\001 \001(\r\022\021\n\tsubstatus\030\002 \001(\r\022\024\n\007"
    "message\030\003 \001(\tH\000\210\001\001B\n\n\010_message2s\n\014BlockS"
    "ervice\022c\n\024GetBlockFinalizeInfo\022$.block_f"
    "inalize.BlockFinalizeRequest\032%.block_fin"
    "alize.BlockFinalizeResponseb\006proto3"
};
static ::absl::once_flag descriptor_table_block_5ffinalize_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_block_5ffinalize_2eproto = {
    false,
    false,
    715,
    descriptor_table_protodef_block_5ffinalize_2eproto,
    "block_finalize.proto",
    &descriptor_table_block_5ffinalize_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_block_5ffinalize_2eproto::offsets,
    file_level_enum_descriptors_block_5ffinalize_2eproto,
    file_level_service_descriptors_block_5ffinalize_2eproto,
};
namespace block_finalize {
// ===================================================================

class BlockFinalizeRequest::_Internal {
 public:
  using HasBits =
      decltype(std::declval<BlockFinalizeRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(BlockFinalizeRequest, _impl_._has_bits_);
};

BlockFinalizeRequest::BlockFinalizeRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:block_finalize.BlockFinalizeRequest)
}
BlockFinalizeRequest::BlockFinalizeRequest(
    ::google::protobuf::Arena* arena, const BlockFinalizeRequest& from)
    : BlockFinalizeRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE BlockFinalizeRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void BlockFinalizeRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, schainid_),
           0,
           offsetof(Impl_, fragmentindex_) -
               offsetof(Impl_, schainid_) +
               sizeof(Impl_::fragmentindex_));
}
BlockFinalizeRequest::~BlockFinalizeRequest() {
  // @@protoc_insertion_point(destructor:block_finalize.BlockFinalizeRequest)
  SharedDtor(*this);
}
inline void BlockFinalizeRequest::SharedDtor(MessageLite& self) {
  BlockFinalizeRequest& this_ = static_cast<BlockFinalizeRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* BlockFinalizeRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) BlockFinalizeRequest(arena);
}
constexpr auto BlockFinalizeRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(BlockFinalizeRequest),
                                            alignof(BlockFinalizeRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull BlockFinalizeRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_BlockFinalizeRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &BlockFinalizeRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<BlockFinalizeRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &BlockFinalizeRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<BlockFinalizeRequest>(), &BlockFinalizeRequest::ByteSizeLong,
            &BlockFinalizeRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(BlockFinalizeRequest, _impl_._cached_size_),
        false,
    },
    &BlockFinalizeRequest::kDescriptorMethods,
    &descriptor_table_block_5ffinalize_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* BlockFinalizeRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 7, 0, 0, 2> BlockFinalizeRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(BlockFinalizeRequest, _impl_._has_bits_),
    0, // no _extensions_
    7, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967168,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::block_finalize::BlockFinalizeRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint64 schainID = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(BlockFinalizeRequest, _impl_.schainid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(BlockFinalizeRequest, _impl_.schainid_)}},
    // uint64 proposerIndex = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(BlockFinalizeRequest, _impl_.proposerindex_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(BlockFinalizeRequest, _impl_.proposerindex_)}},
    // uint64 blockID = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(BlockFinalizeRequest, _impl_.blockid_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(BlockFinalizeRequest, _impl_.blockid_)}},
    // uint64 nodeID = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(BlockFinalizeRequest, _impl_.nodeid_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(BlockFinalizeRequest, _impl_.nodeid_)}},
    // bool needDAProof = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(BlockFinalizeRequest, _impl_.needdaproof_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(BlockFinalizeRequest, _impl_.needdaproof_)}},
    // bool needDecryptionShares = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(BlockFinalizeRequest, _impl_.needdecryptionshares_), 63>(),
     {48, 63, 0, PROTOBUF_FIELD_OFFSET(BlockFinalizeRequest, _impl_.needdecryptionshares_)}},
    // optional uint32 fragmentIndex = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BlockFinalizeRequest, _impl_.fragmentindex_), 0>(),
     {56, 0, 0, PROTOBUF_FIELD_OFFSET(BlockFinalizeRequest, _impl_.fragmentindex_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 schainID = 1;
    {PROTOBUF_FIELD_OFFSET(BlockFinalizeRequest, _impl_.schainid_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // uint64 proposerIndex = 2;
    {PROTOBUF_FIELD_OFFSET(BlockFinalizeRequest, _impl_.proposerindex_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // uint64 blockID = 3;
    {PROTOBUF_FIELD_OFFSET(BlockFinalizeRequest, _impl_.blockid_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // uint64 nodeID = 4;
    {PROTOBUF_FIELD_OFFSET(BlockFinalizeRequest, _impl_.nodeid_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // bool needDAProof = 5;
    {PROTOBUF_FIELD_OFFSET(BlockFinalizeRequest, _impl_.needdaproof_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool needDecryptionShares = 6;
    {PROTOBUF_FIELD_OFFSET(BlockFinalizeRequest, _impl_.needdecryptionshares_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // optional uint32 fragmentIndex = 7;
    {PROTOBUF_FIELD_OFFSET(BlockFinalizeRequest, _impl_.fragmentindex_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void BlockFinalizeRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:block_finalize.BlockFinalizeRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.schainid_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.needdecryptionshares_) -
      reinterpret_cast<char*>(&_impl_.schainid_)) + sizeof(_impl_.needdecryptionshares_));
  _impl_.fragmentindex_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* BlockFinalizeRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const BlockFinalizeRequest& this_ = static_cast<const BlockFinalizeRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* BlockFinalizeRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const BlockFinalizeRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:block_finalize.BlockFinalizeRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint64 schainID = 1;
          if (this_._internal_schainid() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                1, this_._internal_schainid(), target);
          }

          // uint64 proposerIndex = 2;
          if (this_._internal_proposerindex() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                2, this_._internal_proposerindex(), target);
          }

          // uint64 blockID = 3;
          if (this_._internal_blockid() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                3, this_._internal_blockid(), target);
          }

          // uint64 nodeID = 4;
          if (this_._internal_nodeid() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                4, this_._internal_nodeid(), target);
          }

          // bool needDAProof = 5;
          if (this_._internal_needdaproof() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                5, this_._internal_needdaproof(), target);
          }

          // bool needDecryptionShares = 6;
          if (this_._internal_needdecryptionshares() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                6, this_._internal_needdecryptionshares(), target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional uint32 fragmentIndex = 7;
          if (cached_has_bits & 0x00000001u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                7, this_._internal_fragmentindex(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:block_finalize.BlockFinalizeRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t BlockFinalizeRequest::ByteSizeLong(const MessageLite& base) {
          const BlockFinalizeRequest& this_ = static_cast<const BlockFinalizeRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t BlockFinalizeRequest::ByteSizeLong() const {
          const BlockFinalizeRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:block_finalize.BlockFinalizeRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // uint64 schainID = 1;
            if (this_._internal_schainid() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_schainid());
            }
            // uint64 proposerIndex = 2;
            if (this_._internal_proposerindex() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_proposerindex());
            }
            // uint64 blockID = 3;
            if (this_._internal_blockid() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_blockid());
            }
            // uint64 nodeID = 4;
            if (this_._internal_nodeid() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_nodeid());
            }
            // bool needDAProof = 5;
            if (this_._internal_needdaproof() != 0) {
              total_size += 2;
            }
            // bool needDecryptionShares = 6;
            if (this_._internal_needdecryptionshares() != 0) {
              total_size += 2;
            }
          }
           {
            // optional uint32 fragmentIndex = 7;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_fragmentindex());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void BlockFinalizeRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<BlockFinalizeRequest*>(&to_msg);
  auto& from = static_cast<const BlockFinalizeRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:block_finalize.BlockFinalizeRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_schainid() != 0) {
    _this->_impl_.schainid_ = from._impl_.schainid_;
  }
  if (from._internal_proposerindex() != 0) {
    _this->_impl_.proposerindex_ = from._impl_.proposerindex_;
  }
  if (from._internal_blockid() != 0) {
    _this->_impl_.blockid_ = from._impl_.blockid_;
  }
  if (from._internal_nodeid() != 0) {
    _this->_impl_.nodeid_ = from._impl_.nodeid_;
  }
  if (from._internal_needdaproof() != 0) {
    _this->_impl_.needdaproof_ = from._impl_.needdaproof_;
  }
  if (from._internal_needdecryptionshares() != 0) {
    _this->_impl_.needdecryptionshares_ = from._impl_.needdecryptionshares_;
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _this->_impl_.fragmentindex_ = from._impl_.fragmentindex_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void BlockFinalizeRequest::CopyFrom(const BlockFinalizeRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:block_finalize.BlockFinalizeRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void BlockFinalizeRequest::InternalSwap(BlockFinalizeRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(BlockFinalizeRequest, _impl_.fragmentindex_)
      + sizeof(BlockFinalizeRequest::_impl_.fragmentindex_)
      - PROTOBUF_FIELD_OFFSET(BlockFinalizeRequest, _impl_.schainid_)>(
          reinterpret_cast<char*>(&_impl_.schainid_),
          reinterpret_cast<char*>(&other->_impl_.schainid_));
}

::google::protobuf::Metadata BlockFinalizeRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class BlockFinalizeResponse::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::block_finalize::BlockFinalizeResponse, _impl_._oneof_case_);
};

void BlockFinalizeResponse::set_allocated_success(::block_finalize::SuccessResponse* success) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_result();
  if (success) {
    ::google::protobuf::Arena* submessage_arena = success->GetArena();
    if (message_arena != submessage_arena) {
      success = ::google::protobuf::internal::GetOwnedMessage(message_arena, success, submessage_arena);
    }
    set_has_success();
    _impl_.result_.success_ = success;
  }
  // @@protoc_insertion_point(field_set_allocated:block_finalize.BlockFinalizeResponse.success)
}
void BlockFinalizeResponse::set_allocated_error(::block_finalize::ErrorResponse* error) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_result();
  if (error) {
    ::google::protobuf::Arena* submessage_arena = error->GetArena();
    if (message_arena != submessage_arena) {
      error = ::google::protobuf::internal::GetOwnedMessage(message_arena, error, submessage_arena);
    }
    set_has_error();
    _impl_.result_.error_ = error;
  }
  // @@protoc_insertion_point(field_set_allocated:block_finalize.BlockFinalizeResponse.error)
}
BlockFinalizeResponse::BlockFinalizeResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:block_finalize.BlockFinalizeResponse)
}
inline PROTOBUF_NDEBUG_INLINE BlockFinalizeResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::block_finalize::BlockFinalizeResponse& from_msg)
      : result_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

BlockFinalizeResponse::BlockFinalizeResponse(
    ::google::protobuf::Arena* arena,
    const BlockFinalizeResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  BlockFinalizeResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  switch (result_case()) {
    case RESULT_NOT_SET:
      break;
      case kSuccess:
        _impl_.result_.success_ = ::google::protobuf::Message::CopyConstruct<::block_finalize::SuccessResponse>(arena, *from._impl_.result_.success_);
        break;
      case kError:
        _impl_.result_.error_ = ::google::protobuf::Message::CopyConstruct<::block_finalize::ErrorResponse>(arena, *from._impl_.result_.error_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:block_finalize.BlockFinalizeResponse)
}
inline PROTOBUF_NDEBUG_INLINE BlockFinalizeResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : result_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void BlockFinalizeResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
BlockFinalizeResponse::~BlockFinalizeResponse() {
  // @@protoc_insertion_point(destructor:block_finalize.BlockFinalizeResponse)
  SharedDtor(*this);
}
inline void BlockFinalizeResponse::SharedDtor(MessageLite& self) {
  BlockFinalizeResponse& this_ = static_cast<BlockFinalizeResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  if (this_.has_result()) {
    this_.clear_result();
  }
  this_._impl_.~Impl_();
}

void BlockFinalizeResponse::clear_result() {
// @@protoc_insertion_point(one_of_clear_start:block_finalize.BlockFinalizeResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (result_case()) {
    case kSuccess: {
      if (GetArena() == nullptr) {
        delete _impl_.result_.success_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.result_.success_);
      }
      break;
    }
    case kError: {
      if (GetArena() == nullptr) {
        delete _impl_.result_.error_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.result_.error_);
      }
      break;
    }
    case RESULT_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = RESULT_NOT_SET;
}


inline void* BlockFinalizeResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) BlockFinalizeResponse(arena);
}
constexpr auto BlockFinalizeResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(BlockFinalizeResponse),
                                            alignof(BlockFinalizeResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull BlockFinalizeResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_BlockFinalizeResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &BlockFinalizeResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<BlockFinalizeResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &BlockFinalizeResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<BlockFinalizeResponse>(), &BlockFinalizeResponse::ByteSizeLong,
            &BlockFinalizeResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(BlockFinalizeResponse, _impl_._cached_size_),
        false,
    },
    &BlockFinalizeResponse::kDescriptorMethods,
    &descriptor_table_block_5ffinalize_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* BlockFinalizeResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 2, 2, 0, 2> BlockFinalizeResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::block_finalize::BlockFinalizeResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .block_finalize.SuccessResponse success = 1;
    {PROTOBUF_FIELD_OFFSET(BlockFinalizeResponse, _impl_.result_.success_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .block_finalize.ErrorResponse error = 2;
    {PROTOBUF_FIELD_OFFSET(BlockFinalizeResponse, _impl_.result_.error_), _Internal::kOneofCaseOffset + 0, 1,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::block_finalize::SuccessResponse>()},
    {::_pbi::TcParser::GetTable<::block_finalize::ErrorResponse>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void BlockFinalizeResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:block_finalize.BlockFinalizeResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_result();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* BlockFinalizeResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const BlockFinalizeResponse& this_ = static_cast<const BlockFinalizeResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* BlockFinalizeResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const BlockFinalizeResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:block_finalize.BlockFinalizeResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          switch (this_.result_case()) {
            case kSuccess: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  1, *this_._impl_.result_.success_, this_._impl_.result_.success_->GetCachedSize(), target,
                  stream);
              break;
            }
            case kError: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  2, *this_._impl_.result_.error_, this_._impl_.result_.error_->GetCachedSize(), target,
                  stream);
              break;
            }
            default:
              break;
          }
          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:block_finalize.BlockFinalizeResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t BlockFinalizeResponse::ByteSizeLong(const MessageLite& base) {
          const BlockFinalizeResponse& this_ = static_cast<const BlockFinalizeResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t BlockFinalizeResponse::ByteSizeLong() const {
          const BlockFinalizeResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:block_finalize.BlockFinalizeResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          switch (this_.result_case()) {
            // .block_finalize.SuccessResponse success = 1;
            case kSuccess: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.result_.success_);
              break;
            }
            // .block_finalize.ErrorResponse error = 2;
            case kError: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.result_.error_);
              break;
            }
            case RESULT_NOT_SET: {
              break;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void BlockFinalizeResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<BlockFinalizeResponse*>(&to_msg);
  auto& from = static_cast<const BlockFinalizeResponse&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:block_finalize.BlockFinalizeResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_result();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kSuccess: {
        if (oneof_needs_init) {
          _this->_impl_.result_.success_ =
              ::google::protobuf::Message::CopyConstruct<::block_finalize::SuccessResponse>(arena, *from._impl_.result_.success_);
        } else {
          _this->_impl_.result_.success_->MergeFrom(from._internal_success());
        }
        break;
      }
      case kError: {
        if (oneof_needs_init) {
          _this->_impl_.result_.error_ =
              ::google::protobuf::Message::CopyConstruct<::block_finalize::ErrorResponse>(arena, *from._impl_.result_.error_);
        } else {
          _this->_impl_.result_.error_->MergeFrom(from._internal_error());
        }
        break;
      }
      case RESULT_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void BlockFinalizeResponse::CopyFrom(const BlockFinalizeResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:block_finalize.BlockFinalizeResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void BlockFinalizeResponse::InternalSwap(BlockFinalizeResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.result_, other->_impl_.result_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata BlockFinalizeResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SuccessResponse::_Internal {
 public:
  using HasBits =
      decltype(std::declval<SuccessResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SuccessResponse, _impl_._has_bits_);
};

SuccessResponse::SuccessResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:block_finalize.SuccessResponse)
}
inline PROTOBUF_NDEBUG_INLINE SuccessResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::block_finalize::SuccessResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        blockhash_(arena, from.blockhash_),
        daproofsig_(arena, from.daproofsig_),
        fragment_(arena, from.fragment_) {}

SuccessResponse::SuccessResponse(
    ::google::protobuf::Arena* arena,
    const SuccessResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SuccessResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.blocksize_ = from._impl_.blocksize_;

  // @@protoc_insertion_point(copy_constructor:block_finalize.SuccessResponse)
}
inline PROTOBUF_NDEBUG_INLINE SuccessResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        blockhash_(arena),
        daproofsig_(arena),
        fragment_(arena) {}

inline void SuccessResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.blocksize_ = {};
}
SuccessResponse::~SuccessResponse() {
  // @@protoc_insertion_point(destructor:block_finalize.SuccessResponse)
  SharedDtor(*this);
}
inline void SuccessResponse::SharedDtor(MessageLite& self) {
  SuccessResponse& this_ = static_cast<SuccessResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.blockhash_.Destroy();
  this_._impl_.daproofsig_.Destroy();
  this_._impl_.fragment_.Destroy();
  this_._impl_.~Impl_();
}

inline void* SuccessResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SuccessResponse(arena);
}
constexpr auto SuccessResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(SuccessResponse),
                                            alignof(SuccessResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SuccessResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SuccessResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &SuccessResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<SuccessResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SuccessResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<SuccessResponse>(), &SuccessResponse::ByteSizeLong,
            &SuccessResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SuccessResponse, _impl_._cached_size_),
        false,
    },
    &SuccessResponse::kDescriptorMethods,
    &descriptor_table_block_5ffinalize_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SuccessResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 58, 2> SuccessResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SuccessResponse, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::block_finalize::SuccessResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional bytes fragment = 4;
    {::_pbi::TcParser::FastBS1,
     {34, 1, 0, PROTOBUF_FIELD_OFFSET(SuccessResponse, _impl_.fragment_)}},
    // string blockHash = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(SuccessResponse, _impl_.blockhash_)}},
    // uint64 blockSize = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(SuccessResponse, _impl_.blocksize_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(SuccessResponse, _impl_.blocksize_)}},
    // optional string daProofSig = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(SuccessResponse, _impl_.daproofsig_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string blockHash = 1;
    {PROTOBUF_FIELD_OFFSET(SuccessResponse, _impl_.blockhash_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint64 blockSize = 2;
    {PROTOBUF_FIELD_OFFSET(SuccessResponse, _impl_.blocksize_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // optional string daProofSig = 3;
    {PROTOBUF_FIELD_OFFSET(SuccessResponse, _impl_.daproofsig_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional bytes fragment = 4;
    {PROTOBUF_FIELD_OFFSET(SuccessResponse, _impl_.fragment_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\36\11\0\12\0\0\0\0"
    "block_finalize.SuccessResponse"
    "blockHash"
    "daProofSig"
  }},
};

PROTOBUF_NOINLINE void SuccessResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:block_finalize.SuccessResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.blockhash_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.daproofsig_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.fragment_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.blocksize_ = ::uint64_t{0u};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* SuccessResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const SuccessResponse& this_ = static_cast<const SuccessResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* SuccessResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const SuccessResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:block_finalize.SuccessResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string blockHash = 1;
          if (!this_._internal_blockhash().empty()) {
            const std::string& _s = this_._internal_blockhash();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "block_finalize.SuccessResponse.blockHash");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // uint64 blockSize = 2;
          if (this_._internal_blocksize() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                2, this_._internal_blocksize(), target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional string daProofSig = 3;
          if (cached_has_bits & 0x00000001u) {
            const std::string& _s = this_._internal_daproofsig();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "block_finalize.SuccessResponse.daProofSig");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          // optional bytes fragment = 4;
          if (cached_has_bits & 0x00000002u) {
            const std::string& _s = this_._internal_fragment();
            target = stream->WriteBytesMaybeAliased(4, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:block_finalize.SuccessResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t SuccessResponse::ByteSizeLong(const MessageLite& base) {
          const SuccessResponse& this_ = static_cast<const SuccessResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t SuccessResponse::ByteSizeLong() const {
          const SuccessResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:block_finalize.SuccessResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string blockHash = 1;
            if (!this_._internal_blockhash().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_blockhash());
            }
          }
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000003u) {
            // optional string daProofSig = 3;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_daproofsig());
            }
            // optional bytes fragment = 4;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_fragment());
            }
          }
           {
            // uint64 blockSize = 2;
            if (this_._internal_blocksize() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_blocksize());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void SuccessResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SuccessResponse*>(&to_msg);
  auto& from = static_cast<const SuccessResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:block_finalize.SuccessResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_blockhash().empty()) {
    _this->_internal_set_blockhash(from._internal_blockhash());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_daproofsig(from._internal_daproofsig());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_fragment(from._internal_fragment());
    }
  }
  if (from._internal_blocksize() != 0) {
    _this->_impl_.blocksize_ = from._impl_.blocksize_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SuccessResponse::CopyFrom(const SuccessResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:block_finalize.SuccessResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SuccessResponse::InternalSwap(SuccessResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.blockhash_, &other->_impl_.blockhash_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.daproofsig_, &other->_impl_.daproofsig_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.fragment_, &other->_impl_.fragment_, arena);
        swap(_impl_.blocksize_, other->_impl_.blocksize_);
}

::google::protobuf::Metadata SuccessResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ErrorResponse::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ErrorResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ErrorResponse, _impl_._has_bits_);
};

ErrorResponse::ErrorResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:block_finalize.ErrorResponse)
}
inline PROTOBUF_NDEBUG_INLINE ErrorResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::block_finalize::ErrorResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        message_(arena, from.message_) {}

ErrorResponse::ErrorResponse(
    ::google::protobuf::Arena* arena,
    const ErrorResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ErrorResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, status_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, status_),
           offsetof(Impl_, substatus_) -
               offsetof(Impl_, status_) +
               sizeof(Impl_::substatus_));

  // @@protoc_insertion_point(copy_constructor:block_finalize.ErrorResponse)
}
inline PROTOBUF_NDEBUG_INLINE ErrorResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        message_(arena) {}

inline void ErrorResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, status_),
           0,
           offsetof(Impl_, substatus_) -
               offsetof(Impl_, status_) +
               sizeof(Impl_::substatus_));
}
ErrorResponse::~ErrorResponse() {
  // @@protoc_insertion_point(destructor:block_finalize.ErrorResponse)
  SharedDtor(*this);
}
inline void ErrorResponse::SharedDtor(MessageLite& self) {
  ErrorResponse& this_ = static_cast<ErrorResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.message_.Destroy();
  this_._impl_.~Impl_();
}

inline void* ErrorResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ErrorResponse(arena);
}
constexpr auto ErrorResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ErrorResponse),
                                            alignof(ErrorResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ErrorResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ErrorResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ErrorResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ErrorResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ErrorResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ErrorResponse>(), &ErrorResponse::ByteSizeLong,
            &ErrorResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ErrorResponse, _impl_._cached_size_),
        false,
    },
    &ErrorResponse::kDescriptorMethods,
    &descriptor_table_block_5ffinalize_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ErrorResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 44, 2> ErrorResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ErrorResponse, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::block_finalize::ErrorResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint32 status = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ErrorResponse, _impl_.status_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ErrorResponse, _impl_.status_)}},
    // uint32 substatus = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ErrorResponse, _impl_.substatus_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ErrorResponse, _impl_.substatus_)}},
    // optional string message = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(ErrorResponse, _impl_.message_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 status = 1;
    {PROTOBUF_FIELD_OFFSET(ErrorResponse, _impl_.status_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 substatus = 2;
    {PROTOBUF_FIELD_OFFSET(ErrorResponse, _impl_.substatus_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // optional string message = 3;
    {PROTOBUF_FIELD_OFFSET(ErrorResponse, _impl_.message_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\34\0\0\7\0\0\0\0"
    "block_finalize.ErrorResponse"
    "message"
  }},
};

PROTOBUF_NOINLINE void ErrorResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:block_finalize.ErrorResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.message_.ClearNonDefaultToEmpty();
  }
  ::memset(&_impl_.status_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.substatus_) -
      reinterpret_cast<char*>(&_impl_.status_)) + sizeof(_impl_.substatus_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ErrorResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ErrorResponse& this_ = static_cast<const ErrorResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ErrorResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ErrorResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:block_finalize.ErrorResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint32 status = 1;
          if (this_._internal_status() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                1, this_._internal_status(), target);
          }

          // uint32 substatus = 2;
          if (this_._internal_substatus() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                2, this_._internal_substatus(), target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional string message = 3;
          if (cached_has_bits & 0x00000001u) {
            const std::string& _s = this_._internal_message();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "block_finalize.ErrorResponse.message");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:block_finalize.ErrorResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ErrorResponse::ByteSizeLong(const MessageLite& base) {
          const ErrorResponse& this_ = static_cast<const ErrorResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ErrorResponse::ByteSizeLong() const {
          const ErrorResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:block_finalize.ErrorResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // optional string message = 3;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_message());
            }
          }
           {
            // uint32 status = 1;
            if (this_._internal_status() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_status());
            }
            // uint32 substatus = 2;
            if (this_._internal_substatus() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_substatus());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ErrorResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ErrorResponse*>(&to_msg);
  auto& from = static_cast<const ErrorResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:block_finalize.ErrorResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_status() != 0) {
    _this->_impl_.status_ = from._impl_.status_;
  }
  if (from._internal_substatus() != 0) {
    _this->_impl_.substatus_ = from._impl_.substatus_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ErrorResponse::CopyFrom(const ErrorResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:block_finalize.ErrorResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ErrorResponse::InternalSwap(ErrorResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ErrorResponse, _impl_.substatus_)
      + sizeof(ErrorResponse::_impl_.substatus_)
      - PROTOBUF_FIELD_OFFSET(ErrorResponse, _impl_.status_)>(
          reinterpret_cast<char*>(&_impl_.status_),
          reinterpret_cast<char*>(&other->_impl_.status_));
}

::google::protobuf::Metadata ErrorResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace block_finalize
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_block_5ffinalize_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
