// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: block_finalize.proto

#include "block_finalize.pb.h"
#include "block_finalize.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace block_finalize {

static const char* BlockFinalizeService_method_names[] = {
  "/block_finalize.BlockFinalizeService/GetBlockFinalizeInfo",
};

std::unique_ptr< BlockFinalizeService::Stub> BlockFinalizeService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< BlockFinalizeService::Stub> stub(new BlockFinalizeService::Stub(channel, options));
  return stub;
}

BlockFinalizeService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetBlockFinalizeInfo_(BlockFinalizeService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status BlockFinalizeService::Stub::GetBlockFinalizeInfo(::grpc::ClientContext* context, const ::block_finalize::BlockFinalizeRequest& request, ::block_finalize::BlockFinalizeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::block_finalize::BlockFinalizeRequest, ::block_finalize::BlockFinalizeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetBlockFinalizeInfo_, context, request, response);
}

void BlockFinalizeService::Stub::async::GetBlockFinalizeInfo(::grpc::ClientContext* context, const ::block_finalize::BlockFinalizeRequest* request, ::block_finalize::BlockFinalizeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::block_finalize::BlockFinalizeRequest, ::block_finalize::BlockFinalizeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetBlockFinalizeInfo_, context, request, response, std::move(f));
}

void BlockFinalizeService::Stub::async::GetBlockFinalizeInfo(::grpc::ClientContext* context, const ::block_finalize::BlockFinalizeRequest* request, ::block_finalize::BlockFinalizeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetBlockFinalizeInfo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::block_finalize::BlockFinalizeResponse>* BlockFinalizeService::Stub::PrepareAsyncGetBlockFinalizeInfoRaw(::grpc::ClientContext* context, const ::block_finalize::BlockFinalizeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::block_finalize::BlockFinalizeResponse, ::block_finalize::BlockFinalizeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetBlockFinalizeInfo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::block_finalize::BlockFinalizeResponse>* BlockFinalizeService::Stub::AsyncGetBlockFinalizeInfoRaw(::grpc::ClientContext* context, const ::block_finalize::BlockFinalizeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetBlockFinalizeInfoRaw(context, request, cq);
  result->StartCall();
  return result;
}

BlockFinalizeService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BlockFinalizeService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BlockFinalizeService::Service, ::block_finalize::BlockFinalizeRequest, ::block_finalize::BlockFinalizeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BlockFinalizeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::block_finalize::BlockFinalizeRequest* req,
             ::block_finalize::BlockFinalizeResponse* resp) {
               return service->GetBlockFinalizeInfo(ctx, req, resp);
             }, this)));
}

BlockFinalizeService::Service::~Service() {
}

::grpc::Status BlockFinalizeService::Service::GetBlockFinalizeInfo(::grpc::ServerContext* context, const ::block_finalize::BlockFinalizeRequest* request, ::block_finalize::BlockFinalizeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace block_finalize

