
include "block_finalize_common_structures.fbs";

namespace block_finalize;


// Flattened SuccessResponse
table BlockFinalizeSuccessResponse {
    block_header: BlockHeader (required);
    block_sig: [ubyte] (required);
    da_proof_sig: [ubyte];
    block_fragment: BlockFragment; // Directly included
}


// Define a union for SuccessResponse and ErrorResponse
union BlockFinalizeResult { BlockFinalizeSuccessResponse, ErrorResponse }

// BlockFinalizeResponse now only has a union for efficiency
table BlockFinalizeResponse {
    result: BlockFinalizeResult;
}

root_type BlockFinalizeResponse;
