WORKDIR /consensust
COPY ENGINE_VERSION ./
COPY .clang-format ./
COPY *.yml ./
COPY *.cmake ./
COPY *.cpp ./
COPY *.h ./
COPY *.txt ./
COPY *.c ./
COPY *.am ./
COPY *.hpp ./
COPY *.sh ./
COPY *.m4 ./
COPY *.gmp ./
COPY *.ac ./
COPY *.json ./
COPY abstracttcpclient ./abstracttcpclient
COPY abstracttcpserver ./abstracttcpserver
COPY  blockfinalize ./blockfinalize
COPY blockproposal ./blockproposal
COPY catchup ./catchup
COPY cget ./cget
COPY chains ./chains
COPY cmake ./cmake
COPY crypto ./crypto
COPY datastructures ./datastructures
COPY db ./db
COPY exceptions ./exceptions
COPY headers ./headers
COPY json ./json
COPY libBLS ./libBLS
COPY messages ./messages
COPY monitoring ./monitoring
COPY network ./network
COPY node ./node
COPY pendingqueue ./pendingqueue
COPY pricing ./pricing
COPY protocols ./protocols
COPY scripts ./scripts
COPY test ./test
COPY thirdparty ./thirdparty
COPY threads ./threads
COPY utils ./utils