//
// Created by skale on 14.12.21.
//

#ifndef SKALED_ORACLEERRORS_H
#define SKALED_ORACLEERRORS_H

#define ORACLE_SUCCESS  0
#define ORACLE_UNKNOWN_RECEIPT  1
#define ORACLE_TIMEOUT 2
#define ORACLE_NO_CONSENSUS  3
#define ORACLE_UNKNOWN_ERROR  4
#define ORACLE_RESULT_NOT_READY 5
#define ORACLE_DUPLICATE_REQUEST 6
#define ORACLE_COULD_NOT_CONNECT_TO_ENDPOINT 7
#define ORACLE_INVALID_JSON_RESPONSE 8





#endif //SKALED_ORACLEERRORS_H
