//
// Created by skale on 14.12.21.
//

#ifndef SKALED_ORACLEERRORS_H
#define SKALED_ORACLEERRORS_H

#define ORACLE_SUCCESS  0
#define ORACLE_TIMEOUT 1
#define ORACLE_NO_CONSENSUS  2
#define ORACLE_UNKNOWN_ERROR  3
#define ORACLE_DUPLICATE_REQUEST 4

#endif //SKALED_ORACLEERRORS_H
