// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_BLOCKFINALIZECOMMONSTRUCTURES_BLOCK_FINALIZE_H_
#define FLATBUFFERS_GENERATED_BLOCKFINALIZECOMMONSTRUCTURES_BLOCK_FINALIZE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace block_finalize {

struct Transaction;
struct TransactionBuilder;
struct TransactionT;

struct Hash;

struct ExtraData;

struct TruncatedHash;

struct BlockHeader;
struct BlockHeaderBuilder;
struct BlockHeaderT;

struct BlockFragment;
struct BlockFragmentBuilder;
struct BlockFragmentT;

struct DecryptionShare;
struct DecryptionShareBuilder;
struct DecryptionShareT;

struct ErrorResponse;
struct ErrorResponseBuilder;
struct ErrorResponseT;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(1) Hash FLATBUFFERS_FINAL_CLASS {
 private:
  uint8_t data_[32];

 public:
  Hash()
      : data_() {
  }
  Hash(::flatbuffers::span<const uint8_t, 32> _data) {
    ::flatbuffers::CastToArray(data_).CopyFromSpan(_data);
  }
  const ::flatbuffers::Array<uint8_t, 32> *data() const {
    return &::flatbuffers::CastToArray(data_);
  }
};
FLATBUFFERS_STRUCT_END(Hash, 32);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(1) ExtraData FLATBUFFERS_FINAL_CLASS {
 private:
  uint8_t data_[32];

 public:
  ExtraData()
      : data_() {
  }
  ExtraData(::flatbuffers::span<const uint8_t, 32> _data) {
    ::flatbuffers::CastToArray(data_).CopyFromSpan(_data);
  }
  const ::flatbuffers::Array<uint8_t, 32> *data() const {
    return &::flatbuffers::CastToArray(data_);
  }
};
FLATBUFFERS_STRUCT_END(ExtraData, 32);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(1) TruncatedHash FLATBUFFERS_FINAL_CLASS {
 private:
  uint8_t data_[8];

 public:
  TruncatedHash()
      : data_() {
  }
  TruncatedHash(::flatbuffers::span<const uint8_t, 8> _data) {
    ::flatbuffers::CastToArray(data_).CopyFromSpan(_data);
  }
  const ::flatbuffers::Array<uint8_t, 8> *data() const {
    return &::flatbuffers::CastToArray(data_);
  }
};
FLATBUFFERS_STRUCT_END(TruncatedHash, 8);

struct TransactionT : public ::flatbuffers::NativeTable {
  typedef Transaction TableType;
  std::vector<uint8_t> data{};
};

struct Transaction FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TransactionT NativeTableType;
  typedef TransactionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DATA = 4
  };
  const ::flatbuffers::Vector<uint8_t> *data() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_DATA);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           verifier.EndTable();
  }
  TransactionT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(TransactionT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Transaction> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const TransactionT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct TransactionBuilder {
  typedef Transaction Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_data(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data) {
    fbb_.AddOffset(Transaction::VT_DATA, data);
  }
  explicit TransactionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Transaction> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Transaction>(end);
    fbb_.Required(o, Transaction::VT_DATA);
    return o;
  }
};

inline ::flatbuffers::Offset<Transaction> CreateTransaction(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data = 0) {
  TransactionBuilder builder_(_fbb);
  builder_.add_data(data);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Transaction> CreateTransactionDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *data = nullptr) {
  auto data__ = data ? _fbb.CreateVector<uint8_t>(*data) : 0;
  return block_finalize::CreateTransaction(
      _fbb,
      data__);
}

::flatbuffers::Offset<Transaction> CreateTransaction(::flatbuffers::FlatBufferBuilder &_fbb, const TransactionT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct BlockHeaderT : public ::flatbuffers::NativeTable {
  typedef BlockHeader TableType;
  uint64_t schain_id = 0;
  uint64_t epoch_id = 0;
  uint64_t block_id = 0;
  uint64_t proposer_index = 0;
  uint64_t transaction_count = 0;
  uint64_t time_stamp_s = 0;
  uint64_t time_stamp_ms = 0;
  std::unique_ptr<block_finalize::Hash> transactions_merkle_root{};
  std::unique_ptr<block_finalize::Hash> parent_hash{};
  std::unique_ptr<block_finalize::ExtraData> extra_data{};
  std::vector<block_finalize::Hash> committee_hash{};
  std::vector<block_finalize::Hash> public_key_hash{};
  std::vector<uint16_t> encrypted_transaction_indices{};
  BlockHeaderT() = default;
  BlockHeaderT(const BlockHeaderT &o);
  BlockHeaderT(BlockHeaderT&&) FLATBUFFERS_NOEXCEPT = default;
  BlockHeaderT &operator=(BlockHeaderT o) FLATBUFFERS_NOEXCEPT;
};

struct BlockHeader FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BlockHeaderT NativeTableType;
  typedef BlockHeaderBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SCHAIN_ID = 4,
    VT_EPOCH_ID = 6,
    VT_BLOCK_ID = 8,
    VT_PROPOSER_INDEX = 10,
    VT_TRANSACTION_COUNT = 12,
    VT_TIME_STAMP_S = 14,
    VT_TIME_STAMP_MS = 16,
    VT_TRANSACTIONS_MERKLE_ROOT = 18,
    VT_PARENT_HASH = 20,
    VT_EXTRA_DATA = 22,
    VT_COMMITTEE_HASH = 24,
    VT_PUBLIC_KEY_HASH = 26,
    VT_ENCRYPTED_TRANSACTION_INDICES = 28
  };
  uint64_t schain_id() const {
    return GetField<uint64_t>(VT_SCHAIN_ID, 0);
  }
  uint64_t epoch_id() const {
    return GetField<uint64_t>(VT_EPOCH_ID, 0);
  }
  uint64_t block_id() const {
    return GetField<uint64_t>(VT_BLOCK_ID, 0);
  }
  uint64_t proposer_index() const {
    return GetField<uint64_t>(VT_PROPOSER_INDEX, 0);
  }
  uint64_t transaction_count() const {
    return GetField<uint64_t>(VT_TRANSACTION_COUNT, 0);
  }
  uint64_t time_stamp_s() const {
    return GetField<uint64_t>(VT_TIME_STAMP_S, 0);
  }
  uint64_t time_stamp_ms() const {
    return GetField<uint64_t>(VT_TIME_STAMP_MS, 0);
  }
  const block_finalize::Hash *transactions_merkle_root() const {
    return GetStruct<const block_finalize::Hash *>(VT_TRANSACTIONS_MERKLE_ROOT);
  }
  const block_finalize::Hash *parent_hash() const {
    return GetStruct<const block_finalize::Hash *>(VT_PARENT_HASH);
  }
  const block_finalize::ExtraData *extra_data() const {
    return GetStruct<const block_finalize::ExtraData *>(VT_EXTRA_DATA);
  }
  const ::flatbuffers::Vector<const block_finalize::Hash *> *committee_hash() const {
    return GetPointer<const ::flatbuffers::Vector<const block_finalize::Hash *> *>(VT_COMMITTEE_HASH);
  }
  const ::flatbuffers::Vector<const block_finalize::Hash *> *public_key_hash() const {
    return GetPointer<const ::flatbuffers::Vector<const block_finalize::Hash *> *>(VT_PUBLIC_KEY_HASH);
  }
  const ::flatbuffers::Vector<uint16_t> *encrypted_transaction_indices() const {
    return GetPointer<const ::flatbuffers::Vector<uint16_t> *>(VT_ENCRYPTED_TRANSACTION_INDICES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_SCHAIN_ID, 8) &&
           VerifyField<uint64_t>(verifier, VT_EPOCH_ID, 8) &&
           VerifyField<uint64_t>(verifier, VT_BLOCK_ID, 8) &&
           VerifyField<uint64_t>(verifier, VT_PROPOSER_INDEX, 8) &&
           VerifyField<uint64_t>(verifier, VT_TRANSACTION_COUNT, 8) &&
           VerifyField<uint64_t>(verifier, VT_TIME_STAMP_S, 8) &&
           VerifyField<uint64_t>(verifier, VT_TIME_STAMP_MS, 8) &&
           VerifyFieldRequired<block_finalize::Hash>(verifier, VT_TRANSACTIONS_MERKLE_ROOT, 1) &&
           VerifyFieldRequired<block_finalize::Hash>(verifier, VT_PARENT_HASH, 1) &&
           VerifyFieldRequired<block_finalize::ExtraData>(verifier, VT_EXTRA_DATA, 1) &&
           VerifyOffsetRequired(verifier, VT_COMMITTEE_HASH) &&
           verifier.VerifyVector(committee_hash()) &&
           VerifyOffsetRequired(verifier, VT_PUBLIC_KEY_HASH) &&
           verifier.VerifyVector(public_key_hash()) &&
           VerifyOffsetRequired(verifier, VT_ENCRYPTED_TRANSACTION_INDICES) &&
           verifier.VerifyVector(encrypted_transaction_indices()) &&
           verifier.EndTable();
  }
  BlockHeaderT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(BlockHeaderT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<BlockHeader> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BlockHeaderT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct BlockHeaderBuilder {
  typedef BlockHeader Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_schain_id(uint64_t schain_id) {
    fbb_.AddElement<uint64_t>(BlockHeader::VT_SCHAIN_ID, schain_id, 0);
  }
  void add_epoch_id(uint64_t epoch_id) {
    fbb_.AddElement<uint64_t>(BlockHeader::VT_EPOCH_ID, epoch_id, 0);
  }
  void add_block_id(uint64_t block_id) {
    fbb_.AddElement<uint64_t>(BlockHeader::VT_BLOCK_ID, block_id, 0);
  }
  void add_proposer_index(uint64_t proposer_index) {
    fbb_.AddElement<uint64_t>(BlockHeader::VT_PROPOSER_INDEX, proposer_index, 0);
  }
  void add_transaction_count(uint64_t transaction_count) {
    fbb_.AddElement<uint64_t>(BlockHeader::VT_TRANSACTION_COUNT, transaction_count, 0);
  }
  void add_time_stamp_s(uint64_t time_stamp_s) {
    fbb_.AddElement<uint64_t>(BlockHeader::VT_TIME_STAMP_S, time_stamp_s, 0);
  }
  void add_time_stamp_ms(uint64_t time_stamp_ms) {
    fbb_.AddElement<uint64_t>(BlockHeader::VT_TIME_STAMP_MS, time_stamp_ms, 0);
  }
  void add_transactions_merkle_root(const block_finalize::Hash *transactions_merkle_root) {
    fbb_.AddStruct(BlockHeader::VT_TRANSACTIONS_MERKLE_ROOT, transactions_merkle_root);
  }
  void add_parent_hash(const block_finalize::Hash *parent_hash) {
    fbb_.AddStruct(BlockHeader::VT_PARENT_HASH, parent_hash);
  }
  void add_extra_data(const block_finalize::ExtraData *extra_data) {
    fbb_.AddStruct(BlockHeader::VT_EXTRA_DATA, extra_data);
  }
  void add_committee_hash(::flatbuffers::Offset<::flatbuffers::Vector<const block_finalize::Hash *>> committee_hash) {
    fbb_.AddOffset(BlockHeader::VT_COMMITTEE_HASH, committee_hash);
  }
  void add_public_key_hash(::flatbuffers::Offset<::flatbuffers::Vector<const block_finalize::Hash *>> public_key_hash) {
    fbb_.AddOffset(BlockHeader::VT_PUBLIC_KEY_HASH, public_key_hash);
  }
  void add_encrypted_transaction_indices(::flatbuffers::Offset<::flatbuffers::Vector<uint16_t>> encrypted_transaction_indices) {
    fbb_.AddOffset(BlockHeader::VT_ENCRYPTED_TRANSACTION_INDICES, encrypted_transaction_indices);
  }
  explicit BlockHeaderBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BlockHeader> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BlockHeader>(end);
    fbb_.Required(o, BlockHeader::VT_TRANSACTIONS_MERKLE_ROOT);
    fbb_.Required(o, BlockHeader::VT_PARENT_HASH);
    fbb_.Required(o, BlockHeader::VT_EXTRA_DATA);
    fbb_.Required(o, BlockHeader::VT_COMMITTEE_HASH);
    fbb_.Required(o, BlockHeader::VT_PUBLIC_KEY_HASH);
    fbb_.Required(o, BlockHeader::VT_ENCRYPTED_TRANSACTION_INDICES);
    return o;
  }
};

inline ::flatbuffers::Offset<BlockHeader> CreateBlockHeader(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t schain_id = 0,
    uint64_t epoch_id = 0,
    uint64_t block_id = 0,
    uint64_t proposer_index = 0,
    uint64_t transaction_count = 0,
    uint64_t time_stamp_s = 0,
    uint64_t time_stamp_ms = 0,
    const block_finalize::Hash *transactions_merkle_root = nullptr,
    const block_finalize::Hash *parent_hash = nullptr,
    const block_finalize::ExtraData *extra_data = nullptr,
    ::flatbuffers::Offset<::flatbuffers::Vector<const block_finalize::Hash *>> committee_hash = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const block_finalize::Hash *>> public_key_hash = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint16_t>> encrypted_transaction_indices = 0) {
  BlockHeaderBuilder builder_(_fbb);
  builder_.add_time_stamp_ms(time_stamp_ms);
  builder_.add_time_stamp_s(time_stamp_s);
  builder_.add_transaction_count(transaction_count);
  builder_.add_proposer_index(proposer_index);
  builder_.add_block_id(block_id);
  builder_.add_epoch_id(epoch_id);
  builder_.add_schain_id(schain_id);
  builder_.add_encrypted_transaction_indices(encrypted_transaction_indices);
  builder_.add_public_key_hash(public_key_hash);
  builder_.add_committee_hash(committee_hash);
  builder_.add_extra_data(extra_data);
  builder_.add_parent_hash(parent_hash);
  builder_.add_transactions_merkle_root(transactions_merkle_root);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<BlockHeader> CreateBlockHeaderDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t schain_id = 0,
    uint64_t epoch_id = 0,
    uint64_t block_id = 0,
    uint64_t proposer_index = 0,
    uint64_t transaction_count = 0,
    uint64_t time_stamp_s = 0,
    uint64_t time_stamp_ms = 0,
    const block_finalize::Hash *transactions_merkle_root = nullptr,
    const block_finalize::Hash *parent_hash = nullptr,
    const block_finalize::ExtraData *extra_data = nullptr,
    const std::vector<block_finalize::Hash> *committee_hash = nullptr,
    const std::vector<block_finalize::Hash> *public_key_hash = nullptr,
    const std::vector<uint16_t> *encrypted_transaction_indices = nullptr) {
  auto committee_hash__ = committee_hash ? _fbb.CreateVectorOfStructs<block_finalize::Hash>(*committee_hash) : 0;
  auto public_key_hash__ = public_key_hash ? _fbb.CreateVectorOfStructs<block_finalize::Hash>(*public_key_hash) : 0;
  auto encrypted_transaction_indices__ = encrypted_transaction_indices ? _fbb.CreateVector<uint16_t>(*encrypted_transaction_indices) : 0;
  return block_finalize::CreateBlockHeader(
      _fbb,
      schain_id,
      epoch_id,
      block_id,
      proposer_index,
      transaction_count,
      time_stamp_s,
      time_stamp_ms,
      transactions_merkle_root,
      parent_hash,
      extra_data,
      committee_hash__,
      public_key_hash__,
      encrypted_transaction_indices__);
}

::flatbuffers::Offset<BlockHeader> CreateBlockHeader(::flatbuffers::FlatBufferBuilder &_fbb, const BlockHeaderT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct BlockFragmentT : public ::flatbuffers::NativeTable {
  typedef BlockFragment TableType;
  uint16_t index = 0;
  std::vector<block_finalize::TruncatedHash> tx_truncated_hashes{};
  std::vector<block_finalize::Hash> left_proof{};
  std::vector<block_finalize::Hash> right_proof{};
};

struct BlockFragment FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BlockFragmentT NativeTableType;
  typedef BlockFragmentBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_INDEX = 4,
    VT_TX_TRUNCATED_HASHES = 6,
    VT_LEFT_PROOF = 8,
    VT_RIGHT_PROOF = 10
  };
  uint16_t index() const {
    return GetField<uint16_t>(VT_INDEX, 0);
  }
  const ::flatbuffers::Vector<const block_finalize::TruncatedHash *> *tx_truncated_hashes() const {
    return GetPointer<const ::flatbuffers::Vector<const block_finalize::TruncatedHash *> *>(VT_TX_TRUNCATED_HASHES);
  }
  const ::flatbuffers::Vector<const block_finalize::Hash *> *left_proof() const {
    return GetPointer<const ::flatbuffers::Vector<const block_finalize::Hash *> *>(VT_LEFT_PROOF);
  }
  const ::flatbuffers::Vector<const block_finalize::Hash *> *right_proof() const {
    return GetPointer<const ::flatbuffers::Vector<const block_finalize::Hash *> *>(VT_RIGHT_PROOF);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_INDEX, 2) &&
           VerifyOffsetRequired(verifier, VT_TX_TRUNCATED_HASHES) &&
           verifier.VerifyVector(tx_truncated_hashes()) &&
           VerifyOffsetRequired(verifier, VT_LEFT_PROOF) &&
           verifier.VerifyVector(left_proof()) &&
           VerifyOffsetRequired(verifier, VT_RIGHT_PROOF) &&
           verifier.VerifyVector(right_proof()) &&
           verifier.EndTable();
  }
  BlockFragmentT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(BlockFragmentT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<BlockFragment> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BlockFragmentT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct BlockFragmentBuilder {
  typedef BlockFragment Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_index(uint16_t index) {
    fbb_.AddElement<uint16_t>(BlockFragment::VT_INDEX, index, 0);
  }
  void add_tx_truncated_hashes(::flatbuffers::Offset<::flatbuffers::Vector<const block_finalize::TruncatedHash *>> tx_truncated_hashes) {
    fbb_.AddOffset(BlockFragment::VT_TX_TRUNCATED_HASHES, tx_truncated_hashes);
  }
  void add_left_proof(::flatbuffers::Offset<::flatbuffers::Vector<const block_finalize::Hash *>> left_proof) {
    fbb_.AddOffset(BlockFragment::VT_LEFT_PROOF, left_proof);
  }
  void add_right_proof(::flatbuffers::Offset<::flatbuffers::Vector<const block_finalize::Hash *>> right_proof) {
    fbb_.AddOffset(BlockFragment::VT_RIGHT_PROOF, right_proof);
  }
  explicit BlockFragmentBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BlockFragment> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BlockFragment>(end);
    fbb_.Required(o, BlockFragment::VT_TX_TRUNCATED_HASHES);
    fbb_.Required(o, BlockFragment::VT_LEFT_PROOF);
    fbb_.Required(o, BlockFragment::VT_RIGHT_PROOF);
    return o;
  }
};

inline ::flatbuffers::Offset<BlockFragment> CreateBlockFragment(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t index = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const block_finalize::TruncatedHash *>> tx_truncated_hashes = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const block_finalize::Hash *>> left_proof = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const block_finalize::Hash *>> right_proof = 0) {
  BlockFragmentBuilder builder_(_fbb);
  builder_.add_right_proof(right_proof);
  builder_.add_left_proof(left_proof);
  builder_.add_tx_truncated_hashes(tx_truncated_hashes);
  builder_.add_index(index);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<BlockFragment> CreateBlockFragmentDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t index = 0,
    const std::vector<block_finalize::TruncatedHash> *tx_truncated_hashes = nullptr,
    const std::vector<block_finalize::Hash> *left_proof = nullptr,
    const std::vector<block_finalize::Hash> *right_proof = nullptr) {
  auto tx_truncated_hashes__ = tx_truncated_hashes ? _fbb.CreateVectorOfStructs<block_finalize::TruncatedHash>(*tx_truncated_hashes) : 0;
  auto left_proof__ = left_proof ? _fbb.CreateVectorOfStructs<block_finalize::Hash>(*left_proof) : 0;
  auto right_proof__ = right_proof ? _fbb.CreateVectorOfStructs<block_finalize::Hash>(*right_proof) : 0;
  return block_finalize::CreateBlockFragment(
      _fbb,
      index,
      tx_truncated_hashes__,
      left_proof__,
      right_proof__);
}

::flatbuffers::Offset<BlockFragment> CreateBlockFragment(::flatbuffers::FlatBufferBuilder &_fbb, const BlockFragmentT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct DecryptionShareT : public ::flatbuffers::NativeTable {
  typedef DecryptionShare TableType;
  uint16_t transaction_index = 0;
  std::vector<uint8_t> data{};
};

struct DecryptionShare FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DecryptionShareT NativeTableType;
  typedef DecryptionShareBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TRANSACTION_INDEX = 4,
    VT_DATA = 6
  };
  uint16_t transaction_index() const {
    return GetField<uint16_t>(VT_TRANSACTION_INDEX, 0);
  }
  const ::flatbuffers::Vector<uint8_t> *data() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_DATA);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_TRANSACTION_INDEX, 2) &&
           VerifyOffsetRequired(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           verifier.EndTable();
  }
  DecryptionShareT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(DecryptionShareT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<DecryptionShare> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DecryptionShareT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct DecryptionShareBuilder {
  typedef DecryptionShare Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_transaction_index(uint16_t transaction_index) {
    fbb_.AddElement<uint16_t>(DecryptionShare::VT_TRANSACTION_INDEX, transaction_index, 0);
  }
  void add_data(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data) {
    fbb_.AddOffset(DecryptionShare::VT_DATA, data);
  }
  explicit DecryptionShareBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DecryptionShare> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DecryptionShare>(end);
    fbb_.Required(o, DecryptionShare::VT_DATA);
    return o;
  }
};

inline ::flatbuffers::Offset<DecryptionShare> CreateDecryptionShare(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t transaction_index = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data = 0) {
  DecryptionShareBuilder builder_(_fbb);
  builder_.add_data(data);
  builder_.add_transaction_index(transaction_index);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DecryptionShare> CreateDecryptionShareDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t transaction_index = 0,
    const std::vector<uint8_t> *data = nullptr) {
  auto data__ = data ? _fbb.CreateVector<uint8_t>(*data) : 0;
  return block_finalize::CreateDecryptionShare(
      _fbb,
      transaction_index,
      data__);
}

::flatbuffers::Offset<DecryptionShare> CreateDecryptionShare(::flatbuffers::FlatBufferBuilder &_fbb, const DecryptionShareT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ErrorResponseT : public ::flatbuffers::NativeTable {
  typedef ErrorResponse TableType;
  uint32_t status = 0;
  uint32_t substatus = 0;
  uint64_t last_block = 0;
  uint64_t last_block_timestamp_s = 0;
  uint64_t last_block_timestamp_ms = 0;
  std::string message{};
};

struct ErrorResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ErrorResponseT NativeTableType;
  typedef ErrorResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_STATUS = 4,
    VT_SUBSTATUS = 6,
    VT_LAST_BLOCK = 8,
    VT_LAST_BLOCK_TIMESTAMP_S = 10,
    VT_LAST_BLOCK_TIMESTAMP_MS = 12,
    VT_MESSAGE = 14
  };
  uint32_t status() const {
    return GetField<uint32_t>(VT_STATUS, 0);
  }
  uint32_t substatus() const {
    return GetField<uint32_t>(VT_SUBSTATUS, 0);
  }
  uint64_t last_block() const {
    return GetField<uint64_t>(VT_LAST_BLOCK, 0);
  }
  uint64_t last_block_timestamp_s() const {
    return GetField<uint64_t>(VT_LAST_BLOCK_TIMESTAMP_S, 0);
  }
  uint64_t last_block_timestamp_ms() const {
    return GetField<uint64_t>(VT_LAST_BLOCK_TIMESTAMP_MS, 0);
  }
  const ::flatbuffers::String *message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MESSAGE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_STATUS, 4) &&
           VerifyField<uint32_t>(verifier, VT_SUBSTATUS, 4) &&
           VerifyField<uint64_t>(verifier, VT_LAST_BLOCK, 8) &&
           VerifyField<uint64_t>(verifier, VT_LAST_BLOCK_TIMESTAMP_S, 8) &&
           VerifyField<uint64_t>(verifier, VT_LAST_BLOCK_TIMESTAMP_MS, 8) &&
           VerifyOffsetRequired(verifier, VT_MESSAGE) &&
           verifier.VerifyString(message()) &&
           verifier.EndTable();
  }
  ErrorResponseT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ErrorResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ErrorResponse> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ErrorResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ErrorResponseBuilder {
  typedef ErrorResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_status(uint32_t status) {
    fbb_.AddElement<uint32_t>(ErrorResponse::VT_STATUS, status, 0);
  }
  void add_substatus(uint32_t substatus) {
    fbb_.AddElement<uint32_t>(ErrorResponse::VT_SUBSTATUS, substatus, 0);
  }
  void add_last_block(uint64_t last_block) {
    fbb_.AddElement<uint64_t>(ErrorResponse::VT_LAST_BLOCK, last_block, 0);
  }
  void add_last_block_timestamp_s(uint64_t last_block_timestamp_s) {
    fbb_.AddElement<uint64_t>(ErrorResponse::VT_LAST_BLOCK_TIMESTAMP_S, last_block_timestamp_s, 0);
  }
  void add_last_block_timestamp_ms(uint64_t last_block_timestamp_ms) {
    fbb_.AddElement<uint64_t>(ErrorResponse::VT_LAST_BLOCK_TIMESTAMP_MS, last_block_timestamp_ms, 0);
  }
  void add_message(::flatbuffers::Offset<::flatbuffers::String> message) {
    fbb_.AddOffset(ErrorResponse::VT_MESSAGE, message);
  }
  explicit ErrorResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ErrorResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ErrorResponse>(end);
    fbb_.Required(o, ErrorResponse::VT_MESSAGE);
    return o;
  }
};

inline ::flatbuffers::Offset<ErrorResponse> CreateErrorResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t status = 0,
    uint32_t substatus = 0,
    uint64_t last_block = 0,
    uint64_t last_block_timestamp_s = 0,
    uint64_t last_block_timestamp_ms = 0,
    ::flatbuffers::Offset<::flatbuffers::String> message = 0) {
  ErrorResponseBuilder builder_(_fbb);
  builder_.add_last_block_timestamp_ms(last_block_timestamp_ms);
  builder_.add_last_block_timestamp_s(last_block_timestamp_s);
  builder_.add_last_block(last_block);
  builder_.add_message(message);
  builder_.add_substatus(substatus);
  builder_.add_status(status);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ErrorResponse> CreateErrorResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t status = 0,
    uint32_t substatus = 0,
    uint64_t last_block = 0,
    uint64_t last_block_timestamp_s = 0,
    uint64_t last_block_timestamp_ms = 0,
    const char *message = nullptr) {
  auto message__ = message ? _fbb.CreateString(message) : 0;
  return block_finalize::CreateErrorResponse(
      _fbb,
      status,
      substatus,
      last_block,
      last_block_timestamp_s,
      last_block_timestamp_ms,
      message__);
}

::flatbuffers::Offset<ErrorResponse> CreateErrorResponse(::flatbuffers::FlatBufferBuilder &_fbb, const ErrorResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline TransactionT *Transaction::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<TransactionT>(new TransactionT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Transaction::UnPackTo(TransactionT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = data(); if (_e) { _o->data.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->data.begin()); } }
}

inline ::flatbuffers::Offset<Transaction> Transaction::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const TransactionT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateTransaction(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Transaction> CreateTransaction(::flatbuffers::FlatBufferBuilder &_fbb, const TransactionT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const TransactionT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _data = _fbb.CreateVector(_o->data);
  return block_finalize::CreateTransaction(
      _fbb,
      _data);
}

inline BlockHeaderT::BlockHeaderT(const BlockHeaderT &o)
      : schain_id(o.schain_id),
        epoch_id(o.epoch_id),
        block_id(o.block_id),
        proposer_index(o.proposer_index),
        transaction_count(o.transaction_count),
        time_stamp_s(o.time_stamp_s),
        time_stamp_ms(o.time_stamp_ms),
        transactions_merkle_root((o.transactions_merkle_root) ? new block_finalize::Hash(*o.transactions_merkle_root) : nullptr),
        parent_hash((o.parent_hash) ? new block_finalize::Hash(*o.parent_hash) : nullptr),
        extra_data((o.extra_data) ? new block_finalize::ExtraData(*o.extra_data) : nullptr),
        committee_hash(o.committee_hash),
        public_key_hash(o.public_key_hash),
        encrypted_transaction_indices(o.encrypted_transaction_indices) {
}

inline BlockHeaderT &BlockHeaderT::operator=(BlockHeaderT o) FLATBUFFERS_NOEXCEPT {
  std::swap(schain_id, o.schain_id);
  std::swap(epoch_id, o.epoch_id);
  std::swap(block_id, o.block_id);
  std::swap(proposer_index, o.proposer_index);
  std::swap(transaction_count, o.transaction_count);
  std::swap(time_stamp_s, o.time_stamp_s);
  std::swap(time_stamp_ms, o.time_stamp_ms);
  std::swap(transactions_merkle_root, o.transactions_merkle_root);
  std::swap(parent_hash, o.parent_hash);
  std::swap(extra_data, o.extra_data);
  std::swap(committee_hash, o.committee_hash);
  std::swap(public_key_hash, o.public_key_hash);
  std::swap(encrypted_transaction_indices, o.encrypted_transaction_indices);
  return *this;
}

inline BlockHeaderT *BlockHeader::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<BlockHeaderT>(new BlockHeaderT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void BlockHeader::UnPackTo(BlockHeaderT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = schain_id(); _o->schain_id = _e; }
  { auto _e = epoch_id(); _o->epoch_id = _e; }
  { auto _e = block_id(); _o->block_id = _e; }
  { auto _e = proposer_index(); _o->proposer_index = _e; }
  { auto _e = transaction_count(); _o->transaction_count = _e; }
  { auto _e = time_stamp_s(); _o->time_stamp_s = _e; }
  { auto _e = time_stamp_ms(); _o->time_stamp_ms = _e; }
  { auto _e = transactions_merkle_root(); if (_e) _o->transactions_merkle_root = std::unique_ptr<block_finalize::Hash>(new block_finalize::Hash(*_e)); }
  { auto _e = parent_hash(); if (_e) _o->parent_hash = std::unique_ptr<block_finalize::Hash>(new block_finalize::Hash(*_e)); }
  { auto _e = extra_data(); if (_e) _o->extra_data = std::unique_ptr<block_finalize::ExtraData>(new block_finalize::ExtraData(*_e)); }
  { auto _e = committee_hash(); if (_e) { _o->committee_hash.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->committee_hash[_i] = *_e->Get(_i); } } else { _o->committee_hash.resize(0); } }
  { auto _e = public_key_hash(); if (_e) { _o->public_key_hash.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->public_key_hash[_i] = *_e->Get(_i); } } else { _o->public_key_hash.resize(0); } }
  { auto _e = encrypted_transaction_indices(); if (_e) { _o->encrypted_transaction_indices.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->encrypted_transaction_indices[_i] = _e->Get(_i); } } else { _o->encrypted_transaction_indices.resize(0); } }
}

inline ::flatbuffers::Offset<BlockHeader> BlockHeader::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BlockHeaderT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateBlockHeader(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<BlockHeader> CreateBlockHeader(::flatbuffers::FlatBufferBuilder &_fbb, const BlockHeaderT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const BlockHeaderT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _schain_id = _o->schain_id;
  auto _epoch_id = _o->epoch_id;
  auto _block_id = _o->block_id;
  auto _proposer_index = _o->proposer_index;
  auto _transaction_count = _o->transaction_count;
  auto _time_stamp_s = _o->time_stamp_s;
  auto _time_stamp_ms = _o->time_stamp_ms;
  auto _transactions_merkle_root = _o->transactions_merkle_root ? _o->transactions_merkle_root.get() : nullptr;
  auto _parent_hash = _o->parent_hash ? _o->parent_hash.get() : nullptr;
  auto _extra_data = _o->extra_data ? _o->extra_data.get() : nullptr;
  auto _committee_hash = _fbb.CreateVectorOfStructs(_o->committee_hash);
  auto _public_key_hash = _fbb.CreateVectorOfStructs(_o->public_key_hash);
  auto _encrypted_transaction_indices = _fbb.CreateVector(_o->encrypted_transaction_indices);
  return block_finalize::CreateBlockHeader(
      _fbb,
      _schain_id,
      _epoch_id,
      _block_id,
      _proposer_index,
      _transaction_count,
      _time_stamp_s,
      _time_stamp_ms,
      _transactions_merkle_root,
      _parent_hash,
      _extra_data,
      _committee_hash,
      _public_key_hash,
      _encrypted_transaction_indices);
}

inline BlockFragmentT *BlockFragment::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<BlockFragmentT>(new BlockFragmentT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void BlockFragment::UnPackTo(BlockFragmentT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = index(); _o->index = _e; }
  { auto _e = tx_truncated_hashes(); if (_e) { _o->tx_truncated_hashes.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->tx_truncated_hashes[_i] = *_e->Get(_i); } } else { _o->tx_truncated_hashes.resize(0); } }
  { auto _e = left_proof(); if (_e) { _o->left_proof.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->left_proof[_i] = *_e->Get(_i); } } else { _o->left_proof.resize(0); } }
  { auto _e = right_proof(); if (_e) { _o->right_proof.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->right_proof[_i] = *_e->Get(_i); } } else { _o->right_proof.resize(0); } }
}

inline ::flatbuffers::Offset<BlockFragment> BlockFragment::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BlockFragmentT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateBlockFragment(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<BlockFragment> CreateBlockFragment(::flatbuffers::FlatBufferBuilder &_fbb, const BlockFragmentT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const BlockFragmentT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _index = _o->index;
  auto _tx_truncated_hashes = _fbb.CreateVectorOfStructs(_o->tx_truncated_hashes);
  auto _left_proof = _fbb.CreateVectorOfStructs(_o->left_proof);
  auto _right_proof = _fbb.CreateVectorOfStructs(_o->right_proof);
  return block_finalize::CreateBlockFragment(
      _fbb,
      _index,
      _tx_truncated_hashes,
      _left_proof,
      _right_proof);
}

inline DecryptionShareT *DecryptionShare::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<DecryptionShareT>(new DecryptionShareT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void DecryptionShare::UnPackTo(DecryptionShareT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = transaction_index(); _o->transaction_index = _e; }
  { auto _e = data(); if (_e) { _o->data.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->data.begin()); } }
}

inline ::flatbuffers::Offset<DecryptionShare> DecryptionShare::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DecryptionShareT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateDecryptionShare(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<DecryptionShare> CreateDecryptionShare(::flatbuffers::FlatBufferBuilder &_fbb, const DecryptionShareT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const DecryptionShareT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _transaction_index = _o->transaction_index;
  auto _data = _fbb.CreateVector(_o->data);
  return block_finalize::CreateDecryptionShare(
      _fbb,
      _transaction_index,
      _data);
}

inline ErrorResponseT *ErrorResponse::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ErrorResponseT>(new ErrorResponseT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ErrorResponse::UnPackTo(ErrorResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = status(); _o->status = _e; }
  { auto _e = substatus(); _o->substatus = _e; }
  { auto _e = last_block(); _o->last_block = _e; }
  { auto _e = last_block_timestamp_s(); _o->last_block_timestamp_s = _e; }
  { auto _e = last_block_timestamp_ms(); _o->last_block_timestamp_ms = _e; }
  { auto _e = message(); if (_e) _o->message = _e->str(); }
}

inline ::flatbuffers::Offset<ErrorResponse> ErrorResponse::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ErrorResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateErrorResponse(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ErrorResponse> CreateErrorResponse(::flatbuffers::FlatBufferBuilder &_fbb, const ErrorResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ErrorResponseT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _status = _o->status;
  auto _substatus = _o->substatus;
  auto _last_block = _o->last_block;
  auto _last_block_timestamp_s = _o->last_block_timestamp_s;
  auto _last_block_timestamp_ms = _o->last_block_timestamp_ms;
  auto _message = _fbb.CreateString(_o->message);
  return block_finalize::CreateErrorResponse(
      _fbb,
      _status,
      _substatus,
      _last_block,
      _last_block_timestamp_s,
      _last_block_timestamp_ms,
      _message);
}

}  // namespace block_finalize

#endif  // FLATBUFFERS_GENERATED_BLOCKFINALIZECOMMONSTRUCTURES_BLOCK_FINALIZE_H_
