// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_BLOCKTRANSACTIONSRESPONSE_BLOCK_FINALIZE_H_
#define FLATBUFFERS_GENERATED_BLOCKTRANSACTIONSRESPONSE_BLOCK_FINALIZE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "block_finalize_common_structures_generated.h"

namespace block_finalize {

struct BlockTransactionsResponse;
struct BlockTransactionsResponseBuilder;
struct BlockTransactionsResponseT;

struct BlockTransactionsResponseT : public ::flatbuffers::NativeTable {
  typedef BlockTransactionsResponse TableType;
  std::vector<std::unique_ptr<block_finalize::TransactionT>> transactions{};
  BlockTransactionsResponseT() = default;
  BlockTransactionsResponseT(const BlockTransactionsResponseT &o);
  BlockTransactionsResponseT(BlockTransactionsResponseT&&) FLATBUFFERS_NOEXCEPT = default;
  BlockTransactionsResponseT &operator=(BlockTransactionsResponseT o) FLATBUFFERS_NOEXCEPT;
};

struct BlockTransactionsResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BlockTransactionsResponseT NativeTableType;
  typedef BlockTransactionsResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TRANSACTIONS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<block_finalize::Transaction>> *transactions() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<block_finalize::Transaction>> *>(VT_TRANSACTIONS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TRANSACTIONS) &&
           verifier.VerifyVector(transactions()) &&
           verifier.VerifyVectorOfTables(transactions()) &&
           verifier.EndTable();
  }
  BlockTransactionsResponseT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(BlockTransactionsResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<BlockTransactionsResponse> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BlockTransactionsResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct BlockTransactionsResponseBuilder {
  typedef BlockTransactionsResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_transactions(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<block_finalize::Transaction>>> transactions) {
    fbb_.AddOffset(BlockTransactionsResponse::VT_TRANSACTIONS, transactions);
  }
  explicit BlockTransactionsResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BlockTransactionsResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BlockTransactionsResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BlockTransactionsResponse> CreateBlockTransactionsResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<block_finalize::Transaction>>> transactions = 0) {
  BlockTransactionsResponseBuilder builder_(_fbb);
  builder_.add_transactions(transactions);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<BlockTransactionsResponse> CreateBlockTransactionsResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<block_finalize::Transaction>> *transactions = nullptr) {
  auto transactions__ = transactions ? _fbb.CreateVector<::flatbuffers::Offset<block_finalize::Transaction>>(*transactions) : 0;
  return block_finalize::CreateBlockTransactionsResponse(
      _fbb,
      transactions__);
}

::flatbuffers::Offset<BlockTransactionsResponse> CreateBlockTransactionsResponse(::flatbuffers::FlatBufferBuilder &_fbb, const BlockTransactionsResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline BlockTransactionsResponseT::BlockTransactionsResponseT(const BlockTransactionsResponseT &o) {
  transactions.reserve(o.transactions.size());
  for (const auto &transactions_ : o.transactions) { transactions.emplace_back((transactions_) ? new block_finalize::TransactionT(*transactions_) : nullptr); }
}

inline BlockTransactionsResponseT &BlockTransactionsResponseT::operator=(BlockTransactionsResponseT o) FLATBUFFERS_NOEXCEPT {
  std::swap(transactions, o.transactions);
  return *this;
}

inline BlockTransactionsResponseT *BlockTransactionsResponse::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<BlockTransactionsResponseT>(new BlockTransactionsResponseT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void BlockTransactionsResponse::UnPackTo(BlockTransactionsResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = transactions(); if (_e) { _o->transactions.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->transactions[_i]) { _e->Get(_i)->UnPackTo(_o->transactions[_i].get(), _resolver); } else { _o->transactions[_i] = std::unique_ptr<block_finalize::TransactionT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->transactions.resize(0); } }
}

inline ::flatbuffers::Offset<BlockTransactionsResponse> BlockTransactionsResponse::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BlockTransactionsResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateBlockTransactionsResponse(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<BlockTransactionsResponse> CreateBlockTransactionsResponse(::flatbuffers::FlatBufferBuilder &_fbb, const BlockTransactionsResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const BlockTransactionsResponseT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _transactions = _o->transactions.size() ? _fbb.CreateVector<::flatbuffers::Offset<block_finalize::Transaction>> (_o->transactions.size(), [](size_t i, _VectorArgs *__va) { return CreateTransaction(*__va->__fbb, __va->__o->transactions[i].get(), __va->__rehasher); }, &_va ) : 0;
  return block_finalize::CreateBlockTransactionsResponse(
      _fbb,
      _transactions);
}

inline const block_finalize::BlockTransactionsResponse *GetBlockTransactionsResponse(const void *buf) {
  return ::flatbuffers::GetRoot<block_finalize::BlockTransactionsResponse>(buf);
}

inline const block_finalize::BlockTransactionsResponse *GetSizePrefixedBlockTransactionsResponse(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<block_finalize::BlockTransactionsResponse>(buf);
}

inline bool VerifyBlockTransactionsResponseBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<block_finalize::BlockTransactionsResponse>(nullptr);
}

inline bool VerifySizePrefixedBlockTransactionsResponseBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<block_finalize::BlockTransactionsResponse>(nullptr);
}

inline void FinishBlockTransactionsResponseBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<block_finalize::BlockTransactionsResponse> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedBlockTransactionsResponseBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<block_finalize::BlockTransactionsResponse> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<block_finalize::BlockTransactionsResponseT> UnPackBlockTransactionsResponse(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<block_finalize::BlockTransactionsResponseT>(GetBlockTransactionsResponse(buf)->UnPack(res));
}

inline std::unique_ptr<block_finalize::BlockTransactionsResponseT> UnPackSizePrefixedBlockTransactionsResponse(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<block_finalize::BlockTransactionsResponseT>(GetSizePrefixedBlockTransactionsResponse(buf)->UnPack(res));
}

}  // namespace block_finalize

#endif  // FLATBUFFERS_GENERATED_BLOCKTRANSACTIONSRESPONSE_BLOCK_FINALIZE_H_
