// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_BLOCKFINALIZERESPONSE_BLOCK_FINALIZE_H_
#define FLATBUFFERS_GENERATED_BLOCKFINALIZERESPONSE_BLOCK_FINALIZE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "block_finalize_common_structures_generated.h"

namespace block_finalize {

struct BlockFinalizeResponse;
struct BlockFinalizeResponseBuilder;
struct BlockFinalizeResponseT;

struct BlockFinalizeResponseT : public ::flatbuffers::NativeTable {
  typedef BlockFinalizeResponse TableType;
  std::unique_ptr<block_finalize::BlockHeaderT> block_header{};
  std::vector<uint8_t> block_sig{};
  std::vector<uint8_t> da_proof_sig{};
  std::unique_ptr<block_finalize::BlockFragmentT> block_fragment{};
  std::vector<std::unique_ptr<block_finalize::DecryptionShareT>> decryption_shares{};
  BlockFinalizeResponseT() = default;
  BlockFinalizeResponseT(const BlockFinalizeResponseT &o);
  BlockFinalizeResponseT(BlockFinalizeResponseT&&) FLATBUFFERS_NOEXCEPT = default;
  BlockFinalizeResponseT &operator=(BlockFinalizeResponseT o) FLATBUFFERS_NOEXCEPT;
};

struct BlockFinalizeResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BlockFinalizeResponseT NativeTableType;
  typedef BlockFinalizeResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BLOCK_HEADER = 4,
    VT_BLOCK_SIG = 6,
    VT_DA_PROOF_SIG = 8,
    VT_BLOCK_FRAGMENT = 10,
    VT_DECRYPTION_SHARES = 12
  };
  const block_finalize::BlockHeader *block_header() const {
    return GetPointer<const block_finalize::BlockHeader *>(VT_BLOCK_HEADER);
  }
  const ::flatbuffers::Vector<uint8_t> *block_sig() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_BLOCK_SIG);
  }
  const ::flatbuffers::Vector<uint8_t> *da_proof_sig() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_DA_PROOF_SIG);
  }
  const block_finalize::BlockFragment *block_fragment() const {
    return GetPointer<const block_finalize::BlockFragment *>(VT_BLOCK_FRAGMENT);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<block_finalize::DecryptionShare>> *decryption_shares() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<block_finalize::DecryptionShare>> *>(VT_DECRYPTION_SHARES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_BLOCK_HEADER) &&
           verifier.VerifyTable(block_header()) &&
           VerifyOffsetRequired(verifier, VT_BLOCK_SIG) &&
           verifier.VerifyVector(block_sig()) &&
           VerifyOffset(verifier, VT_DA_PROOF_SIG) &&
           verifier.VerifyVector(da_proof_sig()) &&
           VerifyOffset(verifier, VT_BLOCK_FRAGMENT) &&
           verifier.VerifyTable(block_fragment()) &&
           VerifyOffset(verifier, VT_DECRYPTION_SHARES) &&
           verifier.VerifyVector(decryption_shares()) &&
           verifier.VerifyVectorOfTables(decryption_shares()) &&
           verifier.EndTable();
  }
  BlockFinalizeResponseT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(BlockFinalizeResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<BlockFinalizeResponse> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BlockFinalizeResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct BlockFinalizeResponseBuilder {
  typedef BlockFinalizeResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_block_header(::flatbuffers::Offset<block_finalize::BlockHeader> block_header) {
    fbb_.AddOffset(BlockFinalizeResponse::VT_BLOCK_HEADER, block_header);
  }
  void add_block_sig(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> block_sig) {
    fbb_.AddOffset(BlockFinalizeResponse::VT_BLOCK_SIG, block_sig);
  }
  void add_da_proof_sig(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> da_proof_sig) {
    fbb_.AddOffset(BlockFinalizeResponse::VT_DA_PROOF_SIG, da_proof_sig);
  }
  void add_block_fragment(::flatbuffers::Offset<block_finalize::BlockFragment> block_fragment) {
    fbb_.AddOffset(BlockFinalizeResponse::VT_BLOCK_FRAGMENT, block_fragment);
  }
  void add_decryption_shares(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<block_finalize::DecryptionShare>>> decryption_shares) {
    fbb_.AddOffset(BlockFinalizeResponse::VT_DECRYPTION_SHARES, decryption_shares);
  }
  explicit BlockFinalizeResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BlockFinalizeResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BlockFinalizeResponse>(end);
    fbb_.Required(o, BlockFinalizeResponse::VT_BLOCK_HEADER);
    fbb_.Required(o, BlockFinalizeResponse::VT_BLOCK_SIG);
    return o;
  }
};

inline ::flatbuffers::Offset<BlockFinalizeResponse> CreateBlockFinalizeResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<block_finalize::BlockHeader> block_header = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> block_sig = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> da_proof_sig = 0,
    ::flatbuffers::Offset<block_finalize::BlockFragment> block_fragment = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<block_finalize::DecryptionShare>>> decryption_shares = 0) {
  BlockFinalizeResponseBuilder builder_(_fbb);
  builder_.add_decryption_shares(decryption_shares);
  builder_.add_block_fragment(block_fragment);
  builder_.add_da_proof_sig(da_proof_sig);
  builder_.add_block_sig(block_sig);
  builder_.add_block_header(block_header);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<BlockFinalizeResponse> CreateBlockFinalizeResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<block_finalize::BlockHeader> block_header = 0,
    const std::vector<uint8_t> *block_sig = nullptr,
    const std::vector<uint8_t> *da_proof_sig = nullptr,
    ::flatbuffers::Offset<block_finalize::BlockFragment> block_fragment = 0,
    const std::vector<::flatbuffers::Offset<block_finalize::DecryptionShare>> *decryption_shares = nullptr) {
  auto block_sig__ = block_sig ? _fbb.CreateVector<uint8_t>(*block_sig) : 0;
  auto da_proof_sig__ = da_proof_sig ? _fbb.CreateVector<uint8_t>(*da_proof_sig) : 0;
  auto decryption_shares__ = decryption_shares ? _fbb.CreateVector<::flatbuffers::Offset<block_finalize::DecryptionShare>>(*decryption_shares) : 0;
  return block_finalize::CreateBlockFinalizeResponse(
      _fbb,
      block_header,
      block_sig__,
      da_proof_sig__,
      block_fragment,
      decryption_shares__);
}

::flatbuffers::Offset<BlockFinalizeResponse> CreateBlockFinalizeResponse(::flatbuffers::FlatBufferBuilder &_fbb, const BlockFinalizeResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline BlockFinalizeResponseT::BlockFinalizeResponseT(const BlockFinalizeResponseT &o)
      : block_header((o.block_header) ? new block_finalize::BlockHeaderT(*o.block_header) : nullptr),
        block_sig(o.block_sig),
        da_proof_sig(o.da_proof_sig),
        block_fragment((o.block_fragment) ? new block_finalize::BlockFragmentT(*o.block_fragment) : nullptr) {
  decryption_shares.reserve(o.decryption_shares.size());
  for (const auto &decryption_shares_ : o.decryption_shares) { decryption_shares.emplace_back((decryption_shares_) ? new block_finalize::DecryptionShareT(*decryption_shares_) : nullptr); }
}

inline BlockFinalizeResponseT &BlockFinalizeResponseT::operator=(BlockFinalizeResponseT o) FLATBUFFERS_NOEXCEPT {
  std::swap(block_header, o.block_header);
  std::swap(block_sig, o.block_sig);
  std::swap(da_proof_sig, o.da_proof_sig);
  std::swap(block_fragment, o.block_fragment);
  std::swap(decryption_shares, o.decryption_shares);
  return *this;
}

inline BlockFinalizeResponseT *BlockFinalizeResponse::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<BlockFinalizeResponseT>(new BlockFinalizeResponseT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void BlockFinalizeResponse::UnPackTo(BlockFinalizeResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = block_header(); if (_e) { if(_o->block_header) { _e->UnPackTo(_o->block_header.get(), _resolver); } else { _o->block_header = std::unique_ptr<block_finalize::BlockHeaderT>(_e->UnPack(_resolver)); } } else if (_o->block_header) { _o->block_header.reset(); } }
  { auto _e = block_sig(); if (_e) { _o->block_sig.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->block_sig.begin()); } }
  { auto _e = da_proof_sig(); if (_e) { _o->da_proof_sig.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->da_proof_sig.begin()); } }
  { auto _e = block_fragment(); if (_e) { if(_o->block_fragment) { _e->UnPackTo(_o->block_fragment.get(), _resolver); } else { _o->block_fragment = std::unique_ptr<block_finalize::BlockFragmentT>(_e->UnPack(_resolver)); } } else if (_o->block_fragment) { _o->block_fragment.reset(); } }
  { auto _e = decryption_shares(); if (_e) { _o->decryption_shares.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->decryption_shares[_i]) { _e->Get(_i)->UnPackTo(_o->decryption_shares[_i].get(), _resolver); } else { _o->decryption_shares[_i] = std::unique_ptr<block_finalize::DecryptionShareT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->decryption_shares.resize(0); } }
}

inline ::flatbuffers::Offset<BlockFinalizeResponse> BlockFinalizeResponse::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BlockFinalizeResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateBlockFinalizeResponse(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<BlockFinalizeResponse> CreateBlockFinalizeResponse(::flatbuffers::FlatBufferBuilder &_fbb, const BlockFinalizeResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const BlockFinalizeResponseT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _block_header = _o->block_header ? CreateBlockHeader(_fbb, _o->block_header.get(), _rehasher) : 0;
  auto _block_sig = _fbb.CreateVector(_o->block_sig);
  auto _da_proof_sig = _o->da_proof_sig.size() ? _fbb.CreateVector(_o->da_proof_sig) : 0;
  auto _block_fragment = _o->block_fragment ? CreateBlockFragment(_fbb, _o->block_fragment.get(), _rehasher) : 0;
  auto _decryption_shares = _o->decryption_shares.size() ? _fbb.CreateVector<::flatbuffers::Offset<block_finalize::DecryptionShare>> (_o->decryption_shares.size(), [](size_t i, _VectorArgs *__va) { return CreateDecryptionShare(*__va->__fbb, __va->__o->decryption_shares[i].get(), __va->__rehasher); }, &_va ) : 0;
  return block_finalize::CreateBlockFinalizeResponse(
      _fbb,
      _block_header,
      _block_sig,
      _da_proof_sig,
      _block_fragment,
      _decryption_shares);
}

inline const block_finalize::BlockFinalizeResponse *GetBlockFinalizeResponse(const void *buf) {
  return ::flatbuffers::GetRoot<block_finalize::BlockFinalizeResponse>(buf);
}

inline const block_finalize::BlockFinalizeResponse *GetSizePrefixedBlockFinalizeResponse(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<block_finalize::BlockFinalizeResponse>(buf);
}

inline bool VerifyBlockFinalizeResponseBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<block_finalize::BlockFinalizeResponse>(nullptr);
}

inline bool VerifySizePrefixedBlockFinalizeResponseBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<block_finalize::BlockFinalizeResponse>(nullptr);
}

inline void FinishBlockFinalizeResponseBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<block_finalize::BlockFinalizeResponse> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedBlockFinalizeResponseBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<block_finalize::BlockFinalizeResponse> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<block_finalize::BlockFinalizeResponseT> UnPackBlockFinalizeResponse(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<block_finalize::BlockFinalizeResponseT>(GetBlockFinalizeResponse(buf)->UnPack(res));
}

inline std::unique_ptr<block_finalize::BlockFinalizeResponseT> UnPackSizePrefixedBlockFinalizeResponse(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<block_finalize::BlockFinalizeResponseT>(GetSizePrefixedBlockFinalizeResponse(buf)->UnPack(res));
}

}  // namespace block_finalize

#endif  // FLATBUFFERS_GENERATED_BLOCKFINALIZERESPONSE_BLOCK_FINALIZE_H_
