// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_BLOCKFINALIZERESPONSE_SKALE_FB_H_
#define FLATBUFFERS_GENERATED_BLOCKFINALIZERESPONSE_SKALE_FB_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "committed_block_fragment_generated.h"
#include "common_structures_generated.h"

namespace skale_fb {

struct BlockFinalizeResponse;
struct BlockFinalizeResponseBuilder;
struct BlockFinalizeResponseT;

struct BlockFinalizeResponseT : public ::flatbuffers::NativeTable {
  typedef BlockFinalizeResponse TableType;
  std::string json_header{};
  std::unique_ptr<skale_fb::CommittedBlockFragmentT> fragment{};
  BlockFinalizeResponseT() = default;
  BlockFinalizeResponseT(const BlockFinalizeResponseT &o);
  BlockFinalizeResponseT(BlockFinalizeResponseT&&) FLATBUFFERS_NOEXCEPT = default;
  BlockFinalizeResponseT &operator=(BlockFinalizeResponseT o) FLATBUFFERS_NOEXCEPT;
};

struct BlockFinalizeResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BlockFinalizeResponseT NativeTableType;
  typedef BlockFinalizeResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_JSON_HEADER = 4,
    VT_FRAGMENT = 6
  };
  const ::flatbuffers::String *json_header() const {
    return GetPointer<const ::flatbuffers::String *>(VT_JSON_HEADER);
  }
  const skale_fb::CommittedBlockFragment *fragment() const {
    return GetPointer<const skale_fb::CommittedBlockFragment *>(VT_FRAGMENT);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_JSON_HEADER) &&
           verifier.VerifyString(json_header()) &&
           VerifyOffset(verifier, VT_FRAGMENT) &&
           verifier.VerifyTable(fragment()) &&
           verifier.EndTable();
  }
  BlockFinalizeResponseT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(BlockFinalizeResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<BlockFinalizeResponse> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BlockFinalizeResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct BlockFinalizeResponseBuilder {
  typedef BlockFinalizeResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_json_header(::flatbuffers::Offset<::flatbuffers::String> json_header) {
    fbb_.AddOffset(BlockFinalizeResponse::VT_JSON_HEADER, json_header);
  }
  void add_fragment(::flatbuffers::Offset<skale_fb::CommittedBlockFragment> fragment) {
    fbb_.AddOffset(BlockFinalizeResponse::VT_FRAGMENT, fragment);
  }
  explicit BlockFinalizeResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BlockFinalizeResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BlockFinalizeResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BlockFinalizeResponse> CreateBlockFinalizeResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> json_header = 0,
    ::flatbuffers::Offset<skale_fb::CommittedBlockFragment> fragment = 0) {
  BlockFinalizeResponseBuilder builder_(_fbb);
  builder_.add_fragment(fragment);
  builder_.add_json_header(json_header);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<BlockFinalizeResponse> CreateBlockFinalizeResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *json_header = nullptr,
    ::flatbuffers::Offset<skale_fb::CommittedBlockFragment> fragment = 0) {
  auto json_header__ = json_header ? _fbb.CreateString(json_header) : 0;
  return skale_fb::CreateBlockFinalizeResponse(
      _fbb,
      json_header__,
      fragment);
}

::flatbuffers::Offset<BlockFinalizeResponse> CreateBlockFinalizeResponse(::flatbuffers::FlatBufferBuilder &_fbb, const BlockFinalizeResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline BlockFinalizeResponseT::BlockFinalizeResponseT(const BlockFinalizeResponseT &o)
      : json_header(o.json_header),
        fragment((o.fragment) ? new skale_fb::CommittedBlockFragmentT(*o.fragment) : nullptr) {
}

inline BlockFinalizeResponseT &BlockFinalizeResponseT::operator=(BlockFinalizeResponseT o) FLATBUFFERS_NOEXCEPT {
  std::swap(json_header, o.json_header);
  std::swap(fragment, o.fragment);
  return *this;
}

inline BlockFinalizeResponseT *BlockFinalizeResponse::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<BlockFinalizeResponseT>(new BlockFinalizeResponseT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void BlockFinalizeResponse::UnPackTo(BlockFinalizeResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = json_header(); if (_e) _o->json_header = _e->str(); }
  { auto _e = fragment(); if (_e) { if(_o->fragment) { _e->UnPackTo(_o->fragment.get(), _resolver); } else { _o->fragment = std::unique_ptr<skale_fb::CommittedBlockFragmentT>(_e->UnPack(_resolver)); } } else if (_o->fragment) { _o->fragment.reset(); } }
}

inline ::flatbuffers::Offset<BlockFinalizeResponse> BlockFinalizeResponse::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BlockFinalizeResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateBlockFinalizeResponse(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<BlockFinalizeResponse> CreateBlockFinalizeResponse(::flatbuffers::FlatBufferBuilder &_fbb, const BlockFinalizeResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const BlockFinalizeResponseT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _json_header = _o->json_header.empty() ? 0 : _fbb.CreateString(_o->json_header);
  auto _fragment = _o->fragment ? CreateCommittedBlockFragment(_fbb, _o->fragment.get(), _rehasher) : 0;
  return skale_fb::CreateBlockFinalizeResponse(
      _fbb,
      _json_header,
      _fragment);
}

inline const skale_fb::BlockFinalizeResponse *GetBlockFinalizeResponse(const void *buf) {
  return ::flatbuffers::GetRoot<skale_fb::BlockFinalizeResponse>(buf);
}

inline const skale_fb::BlockFinalizeResponse *GetSizePrefixedBlockFinalizeResponse(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<skale_fb::BlockFinalizeResponse>(buf);
}

inline bool VerifyBlockFinalizeResponseBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<skale_fb::BlockFinalizeResponse>(nullptr);
}

inline bool VerifySizePrefixedBlockFinalizeResponseBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<skale_fb::BlockFinalizeResponse>(nullptr);
}

inline void FinishBlockFinalizeResponseBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<skale_fb::BlockFinalizeResponse> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedBlockFinalizeResponseBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<skale_fb::BlockFinalizeResponse> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<skale_fb::BlockFinalizeResponseT> UnPackBlockFinalizeResponse(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<skale_fb::BlockFinalizeResponseT>(GetBlockFinalizeResponse(buf)->UnPack(res));
}

inline std::unique_ptr<skale_fb::BlockFinalizeResponseT> UnPackSizePrefixedBlockFinalizeResponse(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<skale_fb::BlockFinalizeResponseT>(GetSizePrefixedBlockFinalizeResponse(buf)->UnPack(res));
}

}  // namespace skale_fb

#endif  // FLATBUFFERS_GENERATED_BLOCKFINALIZERESPONSE_SKALE_FB_H_
