// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_BLOCKFINALIZEREQUEST_SKALE_FB_H_
#define FLATBUFFERS_GENERATED_BLOCKFINALIZEREQUEST_SKALE_FB_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace skale_fb {

struct BlockFinalizeRequest;
struct BlockFinalizeRequestBuilder;
struct BlockFinalizeRequestT;

struct BlockFinalizeRequestT : public ::flatbuffers::NativeTable {
  typedef BlockFinalizeRequest TableType;
  uint64_t schain_id = 0;
  uint64_t epoch_id = 0;
  uint64_t block_id = 0;
  uint64_t node_id = 0;
  uint64_t proposer_index = 0;
  bool need_da_proof_sig = false;
  bool need_decryption_shares = false;
  bool need_fragment = false;
  uint64_t fragment_index = 0;
};

struct BlockFinalizeRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BlockFinalizeRequestT NativeTableType;
  typedef BlockFinalizeRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SCHAIN_ID = 4,
    VT_EPOCH_ID = 6,
    VT_BLOCK_ID = 8,
    VT_NODE_ID = 10,
    VT_PROPOSER_INDEX = 12,
    VT_NEED_DA_PROOF_SIG = 14,
    VT_NEED_DECRYPTION_SHARES = 16,
    VT_NEED_FRAGMENT = 18,
    VT_FRAGMENT_INDEX = 20
  };
  uint64_t schain_id() const {
    return GetField<uint64_t>(VT_SCHAIN_ID, 0);
  }
  uint64_t epoch_id() const {
    return GetField<uint64_t>(VT_EPOCH_ID, 0);
  }
  uint64_t block_id() const {
    return GetField<uint64_t>(VT_BLOCK_ID, 0);
  }
  uint64_t node_id() const {
    return GetField<uint64_t>(VT_NODE_ID, 0);
  }
  uint64_t proposer_index() const {
    return GetField<uint64_t>(VT_PROPOSER_INDEX, 0);
  }
  bool need_da_proof_sig() const {
    return GetField<uint8_t>(VT_NEED_DA_PROOF_SIG, 0) != 0;
  }
  bool need_decryption_shares() const {
    return GetField<uint8_t>(VT_NEED_DECRYPTION_SHARES, 0) != 0;
  }
  bool need_fragment() const {
    return GetField<uint8_t>(VT_NEED_FRAGMENT, 0) != 0;
  }
  uint64_t fragment_index() const {
    return GetField<uint64_t>(VT_FRAGMENT_INDEX, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_SCHAIN_ID, 8) &&
           VerifyField<uint64_t>(verifier, VT_EPOCH_ID, 8) &&
           VerifyField<uint64_t>(verifier, VT_BLOCK_ID, 8) &&
           VerifyField<uint64_t>(verifier, VT_NODE_ID, 8) &&
           VerifyField<uint64_t>(verifier, VT_PROPOSER_INDEX, 8) &&
           VerifyField<uint8_t>(verifier, VT_NEED_DA_PROOF_SIG, 1) &&
           VerifyField<uint8_t>(verifier, VT_NEED_DECRYPTION_SHARES, 1) &&
           VerifyField<uint8_t>(verifier, VT_NEED_FRAGMENT, 1) &&
           VerifyField<uint64_t>(verifier, VT_FRAGMENT_INDEX, 8) &&
           verifier.EndTable();
  }
  BlockFinalizeRequestT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(BlockFinalizeRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<BlockFinalizeRequest> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BlockFinalizeRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct BlockFinalizeRequestBuilder {
  typedef BlockFinalizeRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_schain_id(uint64_t schain_id) {
    fbb_.AddElement<uint64_t>(BlockFinalizeRequest::VT_SCHAIN_ID, schain_id, 0);
  }
  void add_epoch_id(uint64_t epoch_id) {
    fbb_.AddElement<uint64_t>(BlockFinalizeRequest::VT_EPOCH_ID, epoch_id, 0);
  }
  void add_block_id(uint64_t block_id) {
    fbb_.AddElement<uint64_t>(BlockFinalizeRequest::VT_BLOCK_ID, block_id, 0);
  }
  void add_node_id(uint64_t node_id) {
    fbb_.AddElement<uint64_t>(BlockFinalizeRequest::VT_NODE_ID, node_id, 0);
  }
  void add_proposer_index(uint64_t proposer_index) {
    fbb_.AddElement<uint64_t>(BlockFinalizeRequest::VT_PROPOSER_INDEX, proposer_index, 0);
  }
  void add_need_da_proof_sig(bool need_da_proof_sig) {
    fbb_.AddElement<uint8_t>(BlockFinalizeRequest::VT_NEED_DA_PROOF_SIG, static_cast<uint8_t>(need_da_proof_sig), 0);
  }
  void add_need_decryption_shares(bool need_decryption_shares) {
    fbb_.AddElement<uint8_t>(BlockFinalizeRequest::VT_NEED_DECRYPTION_SHARES, static_cast<uint8_t>(need_decryption_shares), 0);
  }
  void add_need_fragment(bool need_fragment) {
    fbb_.AddElement<uint8_t>(BlockFinalizeRequest::VT_NEED_FRAGMENT, static_cast<uint8_t>(need_fragment), 0);
  }
  void add_fragment_index(uint64_t fragment_index) {
    fbb_.AddElement<uint64_t>(BlockFinalizeRequest::VT_FRAGMENT_INDEX, fragment_index, 0);
  }
  explicit BlockFinalizeRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BlockFinalizeRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BlockFinalizeRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BlockFinalizeRequest> CreateBlockFinalizeRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t schain_id = 0,
    uint64_t epoch_id = 0,
    uint64_t block_id = 0,
    uint64_t node_id = 0,
    uint64_t proposer_index = 0,
    bool need_da_proof_sig = false,
    bool need_decryption_shares = false,
    bool need_fragment = false,
    uint64_t fragment_index = 0) {
  BlockFinalizeRequestBuilder builder_(_fbb);
  builder_.add_fragment_index(fragment_index);
  builder_.add_proposer_index(proposer_index);
  builder_.add_node_id(node_id);
  builder_.add_block_id(block_id);
  builder_.add_epoch_id(epoch_id);
  builder_.add_schain_id(schain_id);
  builder_.add_need_fragment(need_fragment);
  builder_.add_need_decryption_shares(need_decryption_shares);
  builder_.add_need_da_proof_sig(need_da_proof_sig);
  return builder_.Finish();
}

::flatbuffers::Offset<BlockFinalizeRequest> CreateBlockFinalizeRequest(::flatbuffers::FlatBufferBuilder &_fbb, const BlockFinalizeRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline BlockFinalizeRequestT *BlockFinalizeRequest::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<BlockFinalizeRequestT>(new BlockFinalizeRequestT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void BlockFinalizeRequest::UnPackTo(BlockFinalizeRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = schain_id(); _o->schain_id = _e; }
  { auto _e = epoch_id(); _o->epoch_id = _e; }
  { auto _e = block_id(); _o->block_id = _e; }
  { auto _e = node_id(); _o->node_id = _e; }
  { auto _e = proposer_index(); _o->proposer_index = _e; }
  { auto _e = need_da_proof_sig(); _o->need_da_proof_sig = _e; }
  { auto _e = need_decryption_shares(); _o->need_decryption_shares = _e; }
  { auto _e = need_fragment(); _o->need_fragment = _e; }
  { auto _e = fragment_index(); _o->fragment_index = _e; }
}

inline ::flatbuffers::Offset<BlockFinalizeRequest> BlockFinalizeRequest::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BlockFinalizeRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateBlockFinalizeRequest(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<BlockFinalizeRequest> CreateBlockFinalizeRequest(::flatbuffers::FlatBufferBuilder &_fbb, const BlockFinalizeRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const BlockFinalizeRequestT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _schain_id = _o->schain_id;
  auto _epoch_id = _o->epoch_id;
  auto _block_id = _o->block_id;
  auto _node_id = _o->node_id;
  auto _proposer_index = _o->proposer_index;
  auto _need_da_proof_sig = _o->need_da_proof_sig;
  auto _need_decryption_shares = _o->need_decryption_shares;
  auto _need_fragment = _o->need_fragment;
  auto _fragment_index = _o->fragment_index;
  return skale_fb::CreateBlockFinalizeRequest(
      _fbb,
      _schain_id,
      _epoch_id,
      _block_id,
      _node_id,
      _proposer_index,
      _need_da_proof_sig,
      _need_decryption_shares,
      _need_fragment,
      _fragment_index);
}

inline const skale_fb::BlockFinalizeRequest *GetBlockFinalizeRequest(const void *buf) {
  return ::flatbuffers::GetRoot<skale_fb::BlockFinalizeRequest>(buf);
}

inline const skale_fb::BlockFinalizeRequest *GetSizePrefixedBlockFinalizeRequest(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<skale_fb::BlockFinalizeRequest>(buf);
}

inline bool VerifyBlockFinalizeRequestBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<skale_fb::BlockFinalizeRequest>(nullptr);
}

inline bool VerifySizePrefixedBlockFinalizeRequestBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<skale_fb::BlockFinalizeRequest>(nullptr);
}

inline void FinishBlockFinalizeRequestBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<skale_fb::BlockFinalizeRequest> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedBlockFinalizeRequestBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<skale_fb::BlockFinalizeRequest> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<skale_fb::BlockFinalizeRequestT> UnPackBlockFinalizeRequest(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<skale_fb::BlockFinalizeRequestT>(GetBlockFinalizeRequest(buf)->UnPack(res));
}

inline std::unique_ptr<skale_fb::BlockFinalizeRequestT> UnPackSizePrefixedBlockFinalizeRequest(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<skale_fb::BlockFinalizeRequestT>(GetSizePrefixedBlockFinalizeRequest(buf)->UnPack(res));
}

}  // namespace skale_fb

#endif  // FLATBUFFERS_GENERATED_BLOCKFINALIZEREQUEST_SKALE_FB_H_
