// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_BLOCKTRANSACTIONSREQUEST_SKALE_FB_H_
#define FLATBUFFERS_GENERATED_BLOCKTRANSACTIONSREQUEST_SKALE_FB_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace skale_fb {

struct BlockTransactionsRequest;
struct BlockTransactionsRequestBuilder;
struct BlockTransactionsRequestT;

struct BlockTransactionsRequestT : public ::flatbuffers::NativeTable {
  typedef BlockTransactionsRequest TableType;
  uint64_t schain_id = 0;
  uint64_t epoch_id = 0;
  uint64_t block_id = 0;
  uint64_t node_id = 0;
  uint64_t proposer_index = 0;
  std::vector<uint32_t> transaction_indices{};
};

struct BlockTransactionsRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BlockTransactionsRequestT NativeTableType;
  typedef BlockTransactionsRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SCHAIN_ID = 4,
    VT_EPOCH_ID = 6,
    VT_BLOCK_ID = 8,
    VT_NODE_ID = 10,
    VT_PROPOSER_INDEX = 12,
    VT_TRANSACTION_INDICES = 14
  };
  uint64_t schain_id() const {
    return GetField<uint64_t>(VT_SCHAIN_ID, 0);
  }
  uint64_t epoch_id() const {
    return GetField<uint64_t>(VT_EPOCH_ID, 0);
  }
  uint64_t block_id() const {
    return GetField<uint64_t>(VT_BLOCK_ID, 0);
  }
  uint64_t node_id() const {
    return GetField<uint64_t>(VT_NODE_ID, 0);
  }
  uint64_t proposer_index() const {
    return GetField<uint64_t>(VT_PROPOSER_INDEX, 0);
  }
  const ::flatbuffers::Vector<uint32_t> *transaction_indices() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_TRANSACTION_INDICES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_SCHAIN_ID, 8) &&
           VerifyField<uint64_t>(verifier, VT_EPOCH_ID, 8) &&
           VerifyField<uint64_t>(verifier, VT_BLOCK_ID, 8) &&
           VerifyField<uint64_t>(verifier, VT_NODE_ID, 8) &&
           VerifyField<uint64_t>(verifier, VT_PROPOSER_INDEX, 8) &&
           VerifyOffset(verifier, VT_TRANSACTION_INDICES) &&
           verifier.VerifyVector(transaction_indices()) &&
           verifier.EndTable();
  }
  BlockTransactionsRequestT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(BlockTransactionsRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<BlockTransactionsRequest> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BlockTransactionsRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct BlockTransactionsRequestBuilder {
  typedef BlockTransactionsRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_schain_id(uint64_t schain_id) {
    fbb_.AddElement<uint64_t>(BlockTransactionsRequest::VT_SCHAIN_ID, schain_id, 0);
  }
  void add_epoch_id(uint64_t epoch_id) {
    fbb_.AddElement<uint64_t>(BlockTransactionsRequest::VT_EPOCH_ID, epoch_id, 0);
  }
  void add_block_id(uint64_t block_id) {
    fbb_.AddElement<uint64_t>(BlockTransactionsRequest::VT_BLOCK_ID, block_id, 0);
  }
  void add_node_id(uint64_t node_id) {
    fbb_.AddElement<uint64_t>(BlockTransactionsRequest::VT_NODE_ID, node_id, 0);
  }
  void add_proposer_index(uint64_t proposer_index) {
    fbb_.AddElement<uint64_t>(BlockTransactionsRequest::VT_PROPOSER_INDEX, proposer_index, 0);
  }
  void add_transaction_indices(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> transaction_indices) {
    fbb_.AddOffset(BlockTransactionsRequest::VT_TRANSACTION_INDICES, transaction_indices);
  }
  explicit BlockTransactionsRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BlockTransactionsRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BlockTransactionsRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BlockTransactionsRequest> CreateBlockTransactionsRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t schain_id = 0,
    uint64_t epoch_id = 0,
    uint64_t block_id = 0,
    uint64_t node_id = 0,
    uint64_t proposer_index = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> transaction_indices = 0) {
  BlockTransactionsRequestBuilder builder_(_fbb);
  builder_.add_proposer_index(proposer_index);
  builder_.add_node_id(node_id);
  builder_.add_block_id(block_id);
  builder_.add_epoch_id(epoch_id);
  builder_.add_schain_id(schain_id);
  builder_.add_transaction_indices(transaction_indices);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<BlockTransactionsRequest> CreateBlockTransactionsRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t schain_id = 0,
    uint64_t epoch_id = 0,
    uint64_t block_id = 0,
    uint64_t node_id = 0,
    uint64_t proposer_index = 0,
    const std::vector<uint32_t> *transaction_indices = nullptr) {
  auto transaction_indices__ = transaction_indices ? _fbb.CreateVector<uint32_t>(*transaction_indices) : 0;
  return skale_fb::CreateBlockTransactionsRequest(
      _fbb,
      schain_id,
      epoch_id,
      block_id,
      node_id,
      proposer_index,
      transaction_indices__);
}

::flatbuffers::Offset<BlockTransactionsRequest> CreateBlockTransactionsRequest(::flatbuffers::FlatBufferBuilder &_fbb, const BlockTransactionsRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline BlockTransactionsRequestT *BlockTransactionsRequest::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<BlockTransactionsRequestT>(new BlockTransactionsRequestT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void BlockTransactionsRequest::UnPackTo(BlockTransactionsRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = schain_id(); _o->schain_id = _e; }
  { auto _e = epoch_id(); _o->epoch_id = _e; }
  { auto _e = block_id(); _o->block_id = _e; }
  { auto _e = node_id(); _o->node_id = _e; }
  { auto _e = proposer_index(); _o->proposer_index = _e; }
  { auto _e = transaction_indices(); if (_e) { _o->transaction_indices.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->transaction_indices[_i] = _e->Get(_i); } } else { _o->transaction_indices.resize(0); } }
}

inline ::flatbuffers::Offset<BlockTransactionsRequest> BlockTransactionsRequest::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BlockTransactionsRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateBlockTransactionsRequest(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<BlockTransactionsRequest> CreateBlockTransactionsRequest(::flatbuffers::FlatBufferBuilder &_fbb, const BlockTransactionsRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const BlockTransactionsRequestT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _schain_id = _o->schain_id;
  auto _epoch_id = _o->epoch_id;
  auto _block_id = _o->block_id;
  auto _node_id = _o->node_id;
  auto _proposer_index = _o->proposer_index;
  auto _transaction_indices = _o->transaction_indices.size() ? _fbb.CreateVector(_o->transaction_indices) : 0;
  return skale_fb::CreateBlockTransactionsRequest(
      _fbb,
      _schain_id,
      _epoch_id,
      _block_id,
      _node_id,
      _proposer_index,
      _transaction_indices);
}

inline const skale_fb::BlockTransactionsRequest *GetBlockTransactionsRequest(const void *buf) {
  return ::flatbuffers::GetRoot<skale_fb::BlockTransactionsRequest>(buf);
}

inline const skale_fb::BlockTransactionsRequest *GetSizePrefixedBlockTransactionsRequest(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<skale_fb::BlockTransactionsRequest>(buf);
}

inline bool VerifyBlockTransactionsRequestBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<skale_fb::BlockTransactionsRequest>(nullptr);
}

inline bool VerifySizePrefixedBlockTransactionsRequestBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<skale_fb::BlockTransactionsRequest>(nullptr);
}

inline void FinishBlockTransactionsRequestBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<skale_fb::BlockTransactionsRequest> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedBlockTransactionsRequestBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<skale_fb::BlockTransactionsRequest> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<skale_fb::BlockTransactionsRequestT> UnPackBlockTransactionsRequest(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<skale_fb::BlockTransactionsRequestT>(GetBlockTransactionsRequest(buf)->UnPack(res));
}

inline std::unique_ptr<skale_fb::BlockTransactionsRequestT> UnPackSizePrefixedBlockTransactionsRequest(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<skale_fb::BlockTransactionsRequestT>(GetSizePrefixedBlockTransactionsRequest(buf)->UnPack(res));
}

}  // namespace skale_fb

#endif  // FLATBUFFERS_GENERATED_BLOCKTRANSACTIONSREQUEST_SKALE_FB_H_
