// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_COMMITTEDBLOC_SKALE_FB_H_
#define FLATBUFFERS_GENERATED_COMMITTEDBLOC_SKALE_FB_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "common_structures_generated.h"

namespace skale_fb {

struct CommittedBlock;
struct CommittedBlockBuilder;
struct CommittedBlockT;

struct CommittedBlockT : public ::flatbuffers::NativeTable {
  typedef CommittedBlock TableType;
  std::vector<uint8_t> block_header{};
  std::vector<std::unique_ptr<skale_fb::TransactionT>> transactions{};
  std::vector<uint8_t> da_sig{};
  std::vector<uint8_t> threshold_sig{};
  std::vector<skale_fb::AesKey> aes_keys{};
  CommittedBlockT() = default;
  CommittedBlockT(const CommittedBlockT &o);
  CommittedBlockT(CommittedBlockT&&) FLATBUFFERS_NOEXCEPT = default;
  CommittedBlockT &operator=(CommittedBlockT o) FLATBUFFERS_NOEXCEPT;
};

struct CommittedBlock FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CommittedBlockT NativeTableType;
  typedef CommittedBlockBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BLOCK_HEADER = 4,
    VT_TRANSACTIONS = 6,
    VT_DA_SIG = 8,
    VT_THRESHOLD_SIG = 10,
    VT_AES_KEYS = 12
  };
  const ::flatbuffers::Vector<uint8_t> *block_header() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_BLOCK_HEADER);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<skale_fb::Transaction>> *transactions() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<skale_fb::Transaction>> *>(VT_TRANSACTIONS);
  }
  const ::flatbuffers::Vector<uint8_t> *da_sig() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_DA_SIG);
  }
  const ::flatbuffers::Vector<uint8_t> *threshold_sig() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_THRESHOLD_SIG);
  }
  const ::flatbuffers::Vector<const skale_fb::AesKey *> *aes_keys() const {
    return GetPointer<const ::flatbuffers::Vector<const skale_fb::AesKey *> *>(VT_AES_KEYS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_BLOCK_HEADER) &&
           verifier.VerifyVector(block_header()) &&
           VerifyOffset(verifier, VT_TRANSACTIONS) &&
           verifier.VerifyVector(transactions()) &&
           verifier.VerifyVectorOfTables(transactions()) &&
           VerifyOffset(verifier, VT_DA_SIG) &&
           verifier.VerifyVector(da_sig()) &&
           VerifyOffset(verifier, VT_THRESHOLD_SIG) &&
           verifier.VerifyVector(threshold_sig()) &&
           VerifyOffset(verifier, VT_AES_KEYS) &&
           verifier.VerifyVector(aes_keys()) &&
           verifier.EndTable();
  }
  CommittedBlockT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CommittedBlockT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CommittedBlock> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CommittedBlockT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CommittedBlockBuilder {
  typedef CommittedBlock Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_block_header(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> block_header) {
    fbb_.AddOffset(CommittedBlock::VT_BLOCK_HEADER, block_header);
  }
  void add_transactions(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<skale_fb::Transaction>>> transactions) {
    fbb_.AddOffset(CommittedBlock::VT_TRANSACTIONS, transactions);
  }
  void add_da_sig(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> da_sig) {
    fbb_.AddOffset(CommittedBlock::VT_DA_SIG, da_sig);
  }
  void add_threshold_sig(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> threshold_sig) {
    fbb_.AddOffset(CommittedBlock::VT_THRESHOLD_SIG, threshold_sig);
  }
  void add_aes_keys(::flatbuffers::Offset<::flatbuffers::Vector<const skale_fb::AesKey *>> aes_keys) {
    fbb_.AddOffset(CommittedBlock::VT_AES_KEYS, aes_keys);
  }
  explicit CommittedBlockBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CommittedBlock> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CommittedBlock>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CommittedBlock> CreateCommittedBlock(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> block_header = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<skale_fb::Transaction>>> transactions = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> da_sig = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> threshold_sig = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const skale_fb::AesKey *>> aes_keys = 0) {
  CommittedBlockBuilder builder_(_fbb);
  builder_.add_aes_keys(aes_keys);
  builder_.add_threshold_sig(threshold_sig);
  builder_.add_da_sig(da_sig);
  builder_.add_transactions(transactions);
  builder_.add_block_header(block_header);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CommittedBlock> CreateCommittedBlockDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *block_header = nullptr,
    const std::vector<::flatbuffers::Offset<skale_fb::Transaction>> *transactions = nullptr,
    const std::vector<uint8_t> *da_sig = nullptr,
    const std::vector<uint8_t> *threshold_sig = nullptr,
    const std::vector<skale_fb::AesKey> *aes_keys = nullptr) {
  auto block_header__ = block_header ? _fbb.CreateVector<uint8_t>(*block_header) : 0;
  auto transactions__ = transactions ? _fbb.CreateVector<::flatbuffers::Offset<skale_fb::Transaction>>(*transactions) : 0;
  auto da_sig__ = da_sig ? _fbb.CreateVector<uint8_t>(*da_sig) : 0;
  auto threshold_sig__ = threshold_sig ? _fbb.CreateVector<uint8_t>(*threshold_sig) : 0;
  auto aes_keys__ = aes_keys ? _fbb.CreateVectorOfStructs<skale_fb::AesKey>(*aes_keys) : 0;
  return skale_fb::CreateCommittedBlock(
      _fbb,
      block_header__,
      transactions__,
      da_sig__,
      threshold_sig__,
      aes_keys__);
}

::flatbuffers::Offset<CommittedBlock> CreateCommittedBlock(::flatbuffers::FlatBufferBuilder &_fbb, const CommittedBlockT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline CommittedBlockT::CommittedBlockT(const CommittedBlockT &o)
      : block_header(o.block_header),
        da_sig(o.da_sig),
        threshold_sig(o.threshold_sig),
        aes_keys(o.aes_keys) {
  transactions.reserve(o.transactions.size());
  for (const auto &transactions_ : o.transactions) { transactions.emplace_back((transactions_) ? new skale_fb::TransactionT(*transactions_) : nullptr); }
}

inline CommittedBlockT &CommittedBlockT::operator=(CommittedBlockT o) FLATBUFFERS_NOEXCEPT {
  std::swap(block_header, o.block_header);
  std::swap(transactions, o.transactions);
  std::swap(da_sig, o.da_sig);
  std::swap(threshold_sig, o.threshold_sig);
  std::swap(aes_keys, o.aes_keys);
  return *this;
}

inline CommittedBlockT *CommittedBlock::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CommittedBlockT>(new CommittedBlockT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CommittedBlock::UnPackTo(CommittedBlockT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = block_header(); if (_e) { _o->block_header.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->block_header.begin()); } }
  { auto _e = transactions(); if (_e) { _o->transactions.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->transactions[_i]) { _e->Get(_i)->UnPackTo(_o->transactions[_i].get(), _resolver); } else { _o->transactions[_i] = std::unique_ptr<skale_fb::TransactionT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->transactions.resize(0); } }
  { auto _e = da_sig(); if (_e) { _o->da_sig.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->da_sig.begin()); } }
  { auto _e = threshold_sig(); if (_e) { _o->threshold_sig.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->threshold_sig.begin()); } }
  { auto _e = aes_keys(); if (_e) { _o->aes_keys.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->aes_keys[_i] = *_e->Get(_i); } } else { _o->aes_keys.resize(0); } }
}

inline ::flatbuffers::Offset<CommittedBlock> CommittedBlock::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CommittedBlockT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateCommittedBlock(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CommittedBlock> CreateCommittedBlock(::flatbuffers::FlatBufferBuilder &_fbb, const CommittedBlockT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CommittedBlockT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _block_header = _o->block_header.size() ? _fbb.CreateVector(_o->block_header) : 0;
  auto _transactions = _o->transactions.size() ? _fbb.CreateVector<::flatbuffers::Offset<skale_fb::Transaction>> (_o->transactions.size(), [](size_t i, _VectorArgs *__va) { return CreateTransaction(*__va->__fbb, __va->__o->transactions[i].get(), __va->__rehasher); }, &_va ) : 0;
  auto _da_sig = _o->da_sig.size() ? _fbb.CreateVector(_o->da_sig) : 0;
  auto _threshold_sig = _o->threshold_sig.size() ? _fbb.CreateVector(_o->threshold_sig) : 0;
  auto _aes_keys = _o->aes_keys.size() ? _fbb.CreateVectorOfStructs(_o->aes_keys) : 0;
  return skale_fb::CreateCommittedBlock(
      _fbb,
      _block_header,
      _transactions,
      _da_sig,
      _threshold_sig,
      _aes_keys);
}

inline const skale_fb::CommittedBlock *GetCommittedBlock(const void *buf) {
  return ::flatbuffers::GetRoot<skale_fb::CommittedBlock>(buf);
}

inline const skale_fb::CommittedBlock *GetSizePrefixedCommittedBlock(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<skale_fb::CommittedBlock>(buf);
}

inline bool VerifyCommittedBlockBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<skale_fb::CommittedBlock>(nullptr);
}

inline bool VerifySizePrefixedCommittedBlockBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<skale_fb::CommittedBlock>(nullptr);
}

inline void FinishCommittedBlockBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<skale_fb::CommittedBlock> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedCommittedBlockBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<skale_fb::CommittedBlock> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<skale_fb::CommittedBlockT> UnPackCommittedBlock(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<skale_fb::CommittedBlockT>(GetCommittedBlock(buf)->UnPack(res));
}

inline std::unique_ptr<skale_fb::CommittedBlockT> UnPackSizePrefixedCommittedBlock(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<skale_fb::CommittedBlockT>(GetSizePrefixedCommittedBlock(buf)->UnPack(res));
}

}  // namespace skale_fb

#endif  // FLATBUFFERS_GENERATED_COMMITTEDBLOC_SKALE_FB_H_
