// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_COMMITTEDBLOCKFRAGMENT_SKALE_FB_H_
#define FLATBUFFERS_GENERATED_COMMITTEDBLOCKFRAGMENT_SKALE_FB_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "common_structures_generated.h"

namespace skale_fb {

struct CommittedBlockFragment;
struct CommittedBlockFragmentBuilder;
struct CommittedBlockFragmentT;

struct CommittedBlockFragmentT : public ::flatbuffers::NativeTable {
  typedef CommittedBlockFragment TableType;
  std::vector<skale_fb::Hash> left_proof{};
  std::vector<skale_fb::Hash> right_proof{};
  std::vector<std::unique_ptr<skale_fb::DecryptionShareT>> decryption_shares{};
  std::vector<uint8_t> finalization_sig{};
  std::vector<uint8_t> data{};
  CommittedBlockFragmentT() = default;
  CommittedBlockFragmentT(const CommittedBlockFragmentT &o);
  CommittedBlockFragmentT(CommittedBlockFragmentT&&) FLATBUFFERS_NOEXCEPT = default;
  CommittedBlockFragmentT &operator=(CommittedBlockFragmentT o) FLATBUFFERS_NOEXCEPT;
};

struct CommittedBlockFragment FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CommittedBlockFragmentT NativeTableType;
  typedef CommittedBlockFragmentBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LEFT_PROOF = 4,
    VT_RIGHT_PROOF = 6,
    VT_DECRYPTION_SHARES = 8,
    VT_FINALIZATION_SIG = 10,
    VT_DATA = 12
  };
  const ::flatbuffers::Vector<const skale_fb::Hash *> *left_proof() const {
    return GetPointer<const ::flatbuffers::Vector<const skale_fb::Hash *> *>(VT_LEFT_PROOF);
  }
  const ::flatbuffers::Vector<const skale_fb::Hash *> *right_proof() const {
    return GetPointer<const ::flatbuffers::Vector<const skale_fb::Hash *> *>(VT_RIGHT_PROOF);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<skale_fb::DecryptionShare>> *decryption_shares() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<skale_fb::DecryptionShare>> *>(VT_DECRYPTION_SHARES);
  }
  const ::flatbuffers::Vector<uint8_t> *finalization_sig() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_FINALIZATION_SIG);
  }
  const ::flatbuffers::Vector<uint8_t> *data() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_DATA);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_LEFT_PROOF) &&
           verifier.VerifyVector(left_proof()) &&
           VerifyOffset(verifier, VT_RIGHT_PROOF) &&
           verifier.VerifyVector(right_proof()) &&
           VerifyOffset(verifier, VT_DECRYPTION_SHARES) &&
           verifier.VerifyVector(decryption_shares()) &&
           verifier.VerifyVectorOfTables(decryption_shares()) &&
           VerifyOffset(verifier, VT_FINALIZATION_SIG) &&
           verifier.VerifyVector(finalization_sig()) &&
           VerifyOffset(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           verifier.EndTable();
  }
  CommittedBlockFragmentT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CommittedBlockFragmentT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CommittedBlockFragment> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CommittedBlockFragmentT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CommittedBlockFragmentBuilder {
  typedef CommittedBlockFragment Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_left_proof(::flatbuffers::Offset<::flatbuffers::Vector<const skale_fb::Hash *>> left_proof) {
    fbb_.AddOffset(CommittedBlockFragment::VT_LEFT_PROOF, left_proof);
  }
  void add_right_proof(::flatbuffers::Offset<::flatbuffers::Vector<const skale_fb::Hash *>> right_proof) {
    fbb_.AddOffset(CommittedBlockFragment::VT_RIGHT_PROOF, right_proof);
  }
  void add_decryption_shares(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<skale_fb::DecryptionShare>>> decryption_shares) {
    fbb_.AddOffset(CommittedBlockFragment::VT_DECRYPTION_SHARES, decryption_shares);
  }
  void add_finalization_sig(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> finalization_sig) {
    fbb_.AddOffset(CommittedBlockFragment::VT_FINALIZATION_SIG, finalization_sig);
  }
  void add_data(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data) {
    fbb_.AddOffset(CommittedBlockFragment::VT_DATA, data);
  }
  explicit CommittedBlockFragmentBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CommittedBlockFragment> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CommittedBlockFragment>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CommittedBlockFragment> CreateCommittedBlockFragment(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<const skale_fb::Hash *>> left_proof = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const skale_fb::Hash *>> right_proof = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<skale_fb::DecryptionShare>>> decryption_shares = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> finalization_sig = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data = 0) {
  CommittedBlockFragmentBuilder builder_(_fbb);
  builder_.add_data(data);
  builder_.add_finalization_sig(finalization_sig);
  builder_.add_decryption_shares(decryption_shares);
  builder_.add_right_proof(right_proof);
  builder_.add_left_proof(left_proof);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CommittedBlockFragment> CreateCommittedBlockFragmentDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<skale_fb::Hash> *left_proof = nullptr,
    const std::vector<skale_fb::Hash> *right_proof = nullptr,
    const std::vector<::flatbuffers::Offset<skale_fb::DecryptionShare>> *decryption_shares = nullptr,
    const std::vector<uint8_t> *finalization_sig = nullptr,
    const std::vector<uint8_t> *data = nullptr) {
  auto left_proof__ = left_proof ? _fbb.CreateVectorOfStructs<skale_fb::Hash>(*left_proof) : 0;
  auto right_proof__ = right_proof ? _fbb.CreateVectorOfStructs<skale_fb::Hash>(*right_proof) : 0;
  auto decryption_shares__ = decryption_shares ? _fbb.CreateVector<::flatbuffers::Offset<skale_fb::DecryptionShare>>(*decryption_shares) : 0;
  auto finalization_sig__ = finalization_sig ? _fbb.CreateVector<uint8_t>(*finalization_sig) : 0;
  auto data__ = data ? _fbb.CreateVector<uint8_t>(*data) : 0;
  return skale_fb::CreateCommittedBlockFragment(
      _fbb,
      left_proof__,
      right_proof__,
      decryption_shares__,
      finalization_sig__,
      data__);
}

::flatbuffers::Offset<CommittedBlockFragment> CreateCommittedBlockFragment(::flatbuffers::FlatBufferBuilder &_fbb, const CommittedBlockFragmentT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline CommittedBlockFragmentT::CommittedBlockFragmentT(const CommittedBlockFragmentT &o)
      : left_proof(o.left_proof),
        right_proof(o.right_proof),
        finalization_sig(o.finalization_sig),
        data(o.data) {
  decryption_shares.reserve(o.decryption_shares.size());
  for (const auto &decryption_shares_ : o.decryption_shares) { decryption_shares.emplace_back((decryption_shares_) ? new skale_fb::DecryptionShareT(*decryption_shares_) : nullptr); }
}

inline CommittedBlockFragmentT &CommittedBlockFragmentT::operator=(CommittedBlockFragmentT o) FLATBUFFERS_NOEXCEPT {
  std::swap(left_proof, o.left_proof);
  std::swap(right_proof, o.right_proof);
  std::swap(decryption_shares, o.decryption_shares);
  std::swap(finalization_sig, o.finalization_sig);
  std::swap(data, o.data);
  return *this;
}

inline CommittedBlockFragmentT *CommittedBlockFragment::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CommittedBlockFragmentT>(new CommittedBlockFragmentT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CommittedBlockFragment::UnPackTo(CommittedBlockFragmentT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = left_proof(); if (_e) { _o->left_proof.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->left_proof[_i] = *_e->Get(_i); } } else { _o->left_proof.resize(0); } }
  { auto _e = right_proof(); if (_e) { _o->right_proof.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->right_proof[_i] = *_e->Get(_i); } } else { _o->right_proof.resize(0); } }
  { auto _e = decryption_shares(); if (_e) { _o->decryption_shares.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->decryption_shares[_i]) { _e->Get(_i)->UnPackTo(_o->decryption_shares[_i].get(), _resolver); } else { _o->decryption_shares[_i] = std::unique_ptr<skale_fb::DecryptionShareT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->decryption_shares.resize(0); } }
  { auto _e = finalization_sig(); if (_e) { _o->finalization_sig.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->finalization_sig.begin()); } }
  { auto _e = data(); if (_e) { _o->data.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->data.begin()); } }
}

inline ::flatbuffers::Offset<CommittedBlockFragment> CommittedBlockFragment::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CommittedBlockFragmentT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateCommittedBlockFragment(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CommittedBlockFragment> CreateCommittedBlockFragment(::flatbuffers::FlatBufferBuilder &_fbb, const CommittedBlockFragmentT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CommittedBlockFragmentT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _left_proof = _o->left_proof.size() ? _fbb.CreateVectorOfStructs(_o->left_proof) : 0;
  auto _right_proof = _o->right_proof.size() ? _fbb.CreateVectorOfStructs(_o->right_proof) : 0;
  auto _decryption_shares = _o->decryption_shares.size() ? _fbb.CreateVector<::flatbuffers::Offset<skale_fb::DecryptionShare>> (_o->decryption_shares.size(), [](size_t i, _VectorArgs *__va) { return CreateDecryptionShare(*__va->__fbb, __va->__o->decryption_shares[i].get(), __va->__rehasher); }, &_va ) : 0;
  auto _finalization_sig = _o->finalization_sig.size() ? _fbb.CreateVector(_o->finalization_sig) : 0;
  auto _data = _o->data.size() ? _fbb.CreateVector(_o->data) : 0;
  return skale_fb::CreateCommittedBlockFragment(
      _fbb,
      _left_proof,
      _right_proof,
      _decryption_shares,
      _finalization_sig,
      _data);
}

inline const skale_fb::CommittedBlockFragment *GetCommittedBlockFragment(const void *buf) {
  return ::flatbuffers::GetRoot<skale_fb::CommittedBlockFragment>(buf);
}

inline const skale_fb::CommittedBlockFragment *GetSizePrefixedCommittedBlockFragment(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<skale_fb::CommittedBlockFragment>(buf);
}

inline bool VerifyCommittedBlockFragmentBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<skale_fb::CommittedBlockFragment>(nullptr);
}

inline bool VerifySizePrefixedCommittedBlockFragmentBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<skale_fb::CommittedBlockFragment>(nullptr);
}

inline void FinishCommittedBlockFragmentBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<skale_fb::CommittedBlockFragment> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedCommittedBlockFragmentBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<skale_fb::CommittedBlockFragment> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<skale_fb::CommittedBlockFragmentT> UnPackCommittedBlockFragment(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<skale_fb::CommittedBlockFragmentT>(GetCommittedBlockFragment(buf)->UnPack(res));
}

inline std::unique_ptr<skale_fb::CommittedBlockFragmentT> UnPackSizePrefixedCommittedBlockFragment(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<skale_fb::CommittedBlockFragmentT>(GetSizePrefixedCommittedBlockFragment(buf)->UnPack(res));
}

}  // namespace skale_fb

#endif  // FLATBUFFERS_GENERATED_COMMITTEDBLOCKFRAGMENT_SKALE_FB_H_
