// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_DECRYPTIONSHARES_SKALE_FB_H_
#define FLATBUFFERS_GENERATED_DECRYPTIONSHARES_SKALE_FB_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "common_structures_generated.h"

namespace skale_fb {

struct DecryptionShares;
struct DecryptionSharesBuilder;
struct DecryptionSharesT;

struct DecryptionSharesT : public ::flatbuffers::NativeTable {
  typedef DecryptionShares TableType;
  uint64_t block_id = 0;
  uint64_t proposer_index = 0;
  uint64_t decryptor_index = 0;
  std::vector<std::unique_ptr<skale_fb::DecryptionShareT>> decryption_shares{};
  std::vector<uint8_t> signature{};
  DecryptionSharesT() = default;
  DecryptionSharesT(const DecryptionSharesT &o);
  DecryptionSharesT(DecryptionSharesT&&) FLATBUFFERS_NOEXCEPT = default;
  DecryptionSharesT &operator=(DecryptionSharesT o) FLATBUFFERS_NOEXCEPT;
};

struct DecryptionShares FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DecryptionSharesT NativeTableType;
  typedef DecryptionSharesBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BLOCK_ID = 4,
    VT_PROPOSER_INDEX = 6,
    VT_DECRYPTOR_INDEX = 8,
    VT_DECRYPTION_SHARES = 10,
    VT_SIGNATURE = 12
  };
  uint64_t block_id() const {
    return GetField<uint64_t>(VT_BLOCK_ID, 0);
  }
  uint64_t proposer_index() const {
    return GetField<uint64_t>(VT_PROPOSER_INDEX, 0);
  }
  uint64_t decryptor_index() const {
    return GetField<uint64_t>(VT_DECRYPTOR_INDEX, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<skale_fb::DecryptionShare>> *decryption_shares() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<skale_fb::DecryptionShare>> *>(VT_DECRYPTION_SHARES);
  }
  const ::flatbuffers::Vector<uint8_t> *signature() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_SIGNATURE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_BLOCK_ID, 8) &&
           VerifyField<uint64_t>(verifier, VT_PROPOSER_INDEX, 8) &&
           VerifyField<uint64_t>(verifier, VT_DECRYPTOR_INDEX, 8) &&
           VerifyOffset(verifier, VT_DECRYPTION_SHARES) &&
           verifier.VerifyVector(decryption_shares()) &&
           verifier.VerifyVectorOfTables(decryption_shares()) &&
           VerifyOffset(verifier, VT_SIGNATURE) &&
           verifier.VerifyVector(signature()) &&
           verifier.EndTable();
  }
  DecryptionSharesT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(DecryptionSharesT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<DecryptionShares> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DecryptionSharesT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct DecryptionSharesBuilder {
  typedef DecryptionShares Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_block_id(uint64_t block_id) {
    fbb_.AddElement<uint64_t>(DecryptionShares::VT_BLOCK_ID, block_id, 0);
  }
  void add_proposer_index(uint64_t proposer_index) {
    fbb_.AddElement<uint64_t>(DecryptionShares::VT_PROPOSER_INDEX, proposer_index, 0);
  }
  void add_decryptor_index(uint64_t decryptor_index) {
    fbb_.AddElement<uint64_t>(DecryptionShares::VT_DECRYPTOR_INDEX, decryptor_index, 0);
  }
  void add_decryption_shares(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<skale_fb::DecryptionShare>>> decryption_shares) {
    fbb_.AddOffset(DecryptionShares::VT_DECRYPTION_SHARES, decryption_shares);
  }
  void add_signature(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> signature) {
    fbb_.AddOffset(DecryptionShares::VT_SIGNATURE, signature);
  }
  explicit DecryptionSharesBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DecryptionShares> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DecryptionShares>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DecryptionShares> CreateDecryptionShares(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t block_id = 0,
    uint64_t proposer_index = 0,
    uint64_t decryptor_index = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<skale_fb::DecryptionShare>>> decryption_shares = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> signature = 0) {
  DecryptionSharesBuilder builder_(_fbb);
  builder_.add_decryptor_index(decryptor_index);
  builder_.add_proposer_index(proposer_index);
  builder_.add_block_id(block_id);
  builder_.add_signature(signature);
  builder_.add_decryption_shares(decryption_shares);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DecryptionShares> CreateDecryptionSharesDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t block_id = 0,
    uint64_t proposer_index = 0,
    uint64_t decryptor_index = 0,
    const std::vector<::flatbuffers::Offset<skale_fb::DecryptionShare>> *decryption_shares = nullptr,
    const std::vector<uint8_t> *signature = nullptr) {
  auto decryption_shares__ = decryption_shares ? _fbb.CreateVector<::flatbuffers::Offset<skale_fb::DecryptionShare>>(*decryption_shares) : 0;
  auto signature__ = signature ? _fbb.CreateVector<uint8_t>(*signature) : 0;
  return skale_fb::CreateDecryptionShares(
      _fbb,
      block_id,
      proposer_index,
      decryptor_index,
      decryption_shares__,
      signature__);
}

::flatbuffers::Offset<DecryptionShares> CreateDecryptionShares(::flatbuffers::FlatBufferBuilder &_fbb, const DecryptionSharesT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline DecryptionSharesT::DecryptionSharesT(const DecryptionSharesT &o)
      : block_id(o.block_id),
        proposer_index(o.proposer_index),
        decryptor_index(o.decryptor_index),
        signature(o.signature) {
  decryption_shares.reserve(o.decryption_shares.size());
  for (const auto &decryption_shares_ : o.decryption_shares) { decryption_shares.emplace_back((decryption_shares_) ? new skale_fb::DecryptionShareT(*decryption_shares_) : nullptr); }
}

inline DecryptionSharesT &DecryptionSharesT::operator=(DecryptionSharesT o) FLATBUFFERS_NOEXCEPT {
  std::swap(block_id, o.block_id);
  std::swap(proposer_index, o.proposer_index);
  std::swap(decryptor_index, o.decryptor_index);
  std::swap(decryption_shares, o.decryption_shares);
  std::swap(signature, o.signature);
  return *this;
}

inline DecryptionSharesT *DecryptionShares::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<DecryptionSharesT>(new DecryptionSharesT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void DecryptionShares::UnPackTo(DecryptionSharesT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = block_id(); _o->block_id = _e; }
  { auto _e = proposer_index(); _o->proposer_index = _e; }
  { auto _e = decryptor_index(); _o->decryptor_index = _e; }
  { auto _e = decryption_shares(); if (_e) { _o->decryption_shares.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->decryption_shares[_i]) { _e->Get(_i)->UnPackTo(_o->decryption_shares[_i].get(), _resolver); } else { _o->decryption_shares[_i] = std::unique_ptr<skale_fb::DecryptionShareT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->decryption_shares.resize(0); } }
  { auto _e = signature(); if (_e) { _o->signature.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->signature.begin()); } }
}

inline ::flatbuffers::Offset<DecryptionShares> DecryptionShares::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DecryptionSharesT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateDecryptionShares(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<DecryptionShares> CreateDecryptionShares(::flatbuffers::FlatBufferBuilder &_fbb, const DecryptionSharesT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const DecryptionSharesT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _block_id = _o->block_id;
  auto _proposer_index = _o->proposer_index;
  auto _decryptor_index = _o->decryptor_index;
  auto _decryption_shares = _o->decryption_shares.size() ? _fbb.CreateVector<::flatbuffers::Offset<skale_fb::DecryptionShare>> (_o->decryption_shares.size(), [](size_t i, _VectorArgs *__va) { return CreateDecryptionShare(*__va->__fbb, __va->__o->decryption_shares[i].get(), __va->__rehasher); }, &_va ) : 0;
  auto _signature = _o->signature.size() ? _fbb.CreateVector(_o->signature) : 0;
  return skale_fb::CreateDecryptionShares(
      _fbb,
      _block_id,
      _proposer_index,
      _decryptor_index,
      _decryption_shares,
      _signature);
}

inline const skale_fb::DecryptionShares *GetDecryptionShares(const void *buf) {
  return ::flatbuffers::GetRoot<skale_fb::DecryptionShares>(buf);
}

inline const skale_fb::DecryptionShares *GetSizePrefixedDecryptionShares(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<skale_fb::DecryptionShares>(buf);
}

inline bool VerifyDecryptionSharesBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<skale_fb::DecryptionShares>(nullptr);
}

inline bool VerifySizePrefixedDecryptionSharesBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<skale_fb::DecryptionShares>(nullptr);
}

inline void FinishDecryptionSharesBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<skale_fb::DecryptionShares> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedDecryptionSharesBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<skale_fb::DecryptionShares> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<skale_fb::DecryptionSharesT> UnPackDecryptionShares(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<skale_fb::DecryptionSharesT>(GetDecryptionShares(buf)->UnPack(res));
}

inline std::unique_ptr<skale_fb::DecryptionSharesT> UnPackSizePrefixedDecryptionShares(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<skale_fb::DecryptionSharesT>(GetSizePrefixedDecryptionShares(buf)->UnPack(res));
}

}  // namespace skale_fb

#endif  // FLATBUFFERS_GENERATED_DECRYPTIONSHARES_SKALE_FB_H_
