// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ERRORRESPONSE_SKALE_FB_H_
#define FLATBUFFERS_GENERATED_ERRORRESPONSE_SKALE_FB_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace skale_fb {

struct ErrorResponse;
struct ErrorResponseBuilder;
struct ErrorResponseT;

struct ErrorResponseT : public ::flatbuffers::NativeTable {
  typedef ErrorResponse TableType;
  uint32_t status = 0;
  uint32_t substatus = 0;
  uint64_t last_block = 0;
  uint64_t last_block_timestamp_s = 0;
  uint64_t last_block_timestamp_ms = 0;
  std::string message{};
};

struct ErrorResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ErrorResponseT NativeTableType;
  typedef ErrorResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_STATUS = 4,
    VT_SUBSTATUS = 6,
    VT_LAST_BLOCK = 8,
    VT_LAST_BLOCK_TIMESTAMP_S = 10,
    VT_LAST_BLOCK_TIMESTAMP_MS = 12,
    VT_MESSAGE = 14
  };
  uint32_t status() const {
    return GetField<uint32_t>(VT_STATUS, 0);
  }
  uint32_t substatus() const {
    return GetField<uint32_t>(VT_SUBSTATUS, 0);
  }
  uint64_t last_block() const {
    return GetField<uint64_t>(VT_LAST_BLOCK, 0);
  }
  uint64_t last_block_timestamp_s() const {
    return GetField<uint64_t>(VT_LAST_BLOCK_TIMESTAMP_S, 0);
  }
  uint64_t last_block_timestamp_ms() const {
    return GetField<uint64_t>(VT_LAST_BLOCK_TIMESTAMP_MS, 0);
  }
  const ::flatbuffers::String *message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MESSAGE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_STATUS, 4) &&
           VerifyField<uint32_t>(verifier, VT_SUBSTATUS, 4) &&
           VerifyField<uint64_t>(verifier, VT_LAST_BLOCK, 8) &&
           VerifyField<uint64_t>(verifier, VT_LAST_BLOCK_TIMESTAMP_S, 8) &&
           VerifyField<uint64_t>(verifier, VT_LAST_BLOCK_TIMESTAMP_MS, 8) &&
           VerifyOffsetRequired(verifier, VT_MESSAGE) &&
           verifier.VerifyString(message()) &&
           verifier.EndTable();
  }
  ErrorResponseT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ErrorResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ErrorResponse> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ErrorResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ErrorResponseBuilder {
  typedef ErrorResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_status(uint32_t status) {
    fbb_.AddElement<uint32_t>(ErrorResponse::VT_STATUS, status, 0);
  }
  void add_substatus(uint32_t substatus) {
    fbb_.AddElement<uint32_t>(ErrorResponse::VT_SUBSTATUS, substatus, 0);
  }
  void add_last_block(uint64_t last_block) {
    fbb_.AddElement<uint64_t>(ErrorResponse::VT_LAST_BLOCK, last_block, 0);
  }
  void add_last_block_timestamp_s(uint64_t last_block_timestamp_s) {
    fbb_.AddElement<uint64_t>(ErrorResponse::VT_LAST_BLOCK_TIMESTAMP_S, last_block_timestamp_s, 0);
  }
  void add_last_block_timestamp_ms(uint64_t last_block_timestamp_ms) {
    fbb_.AddElement<uint64_t>(ErrorResponse::VT_LAST_BLOCK_TIMESTAMP_MS, last_block_timestamp_ms, 0);
  }
  void add_message(::flatbuffers::Offset<::flatbuffers::String> message) {
    fbb_.AddOffset(ErrorResponse::VT_MESSAGE, message);
  }
  explicit ErrorResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ErrorResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ErrorResponse>(end);
    fbb_.Required(o, ErrorResponse::VT_MESSAGE);
    return o;
  }
};

inline ::flatbuffers::Offset<ErrorResponse> CreateErrorResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t status = 0,
    uint32_t substatus = 0,
    uint64_t last_block = 0,
    uint64_t last_block_timestamp_s = 0,
    uint64_t last_block_timestamp_ms = 0,
    ::flatbuffers::Offset<::flatbuffers::String> message = 0) {
  ErrorResponseBuilder builder_(_fbb);
  builder_.add_last_block_timestamp_ms(last_block_timestamp_ms);
  builder_.add_last_block_timestamp_s(last_block_timestamp_s);
  builder_.add_last_block(last_block);
  builder_.add_message(message);
  builder_.add_substatus(substatus);
  builder_.add_status(status);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ErrorResponse> CreateErrorResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t status = 0,
    uint32_t substatus = 0,
    uint64_t last_block = 0,
    uint64_t last_block_timestamp_s = 0,
    uint64_t last_block_timestamp_ms = 0,
    const char *message = nullptr) {
  auto message__ = message ? _fbb.CreateString(message) : 0;
  return skale_fb::CreateErrorResponse(
      _fbb,
      status,
      substatus,
      last_block,
      last_block_timestamp_s,
      last_block_timestamp_ms,
      message__);
}

::flatbuffers::Offset<ErrorResponse> CreateErrorResponse(::flatbuffers::FlatBufferBuilder &_fbb, const ErrorResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline ErrorResponseT *ErrorResponse::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ErrorResponseT>(new ErrorResponseT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ErrorResponse::UnPackTo(ErrorResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = status(); _o->status = _e; }
  { auto _e = substatus(); _o->substatus = _e; }
  { auto _e = last_block(); _o->last_block = _e; }
  { auto _e = last_block_timestamp_s(); _o->last_block_timestamp_s = _e; }
  { auto _e = last_block_timestamp_ms(); _o->last_block_timestamp_ms = _e; }
  { auto _e = message(); if (_e) _o->message = _e->str(); }
}

inline ::flatbuffers::Offset<ErrorResponse> ErrorResponse::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ErrorResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateErrorResponse(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ErrorResponse> CreateErrorResponse(::flatbuffers::FlatBufferBuilder &_fbb, const ErrorResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ErrorResponseT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _status = _o->status;
  auto _substatus = _o->substatus;
  auto _last_block = _o->last_block;
  auto _last_block_timestamp_s = _o->last_block_timestamp_s;
  auto _last_block_timestamp_ms = _o->last_block_timestamp_ms;
  auto _message = _fbb.CreateString(_o->message);
  return skale_fb::CreateErrorResponse(
      _fbb,
      _status,
      _substatus,
      _last_block,
      _last_block_timestamp_s,
      _last_block_timestamp_ms,
      _message);
}

inline const skale_fb::ErrorResponse *GetErrorResponse(const void *buf) {
  return ::flatbuffers::GetRoot<skale_fb::ErrorResponse>(buf);
}

inline const skale_fb::ErrorResponse *GetSizePrefixedErrorResponse(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<skale_fb::ErrorResponse>(buf);
}

inline bool VerifyErrorResponseBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<skale_fb::ErrorResponse>(nullptr);
}

inline bool VerifySizePrefixedErrorResponseBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<skale_fb::ErrorResponse>(nullptr);
}

inline void FinishErrorResponseBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<skale_fb::ErrorResponse> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedErrorResponseBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<skale_fb::ErrorResponse> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<skale_fb::ErrorResponseT> UnPackErrorResponse(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<skale_fb::ErrorResponseT>(GetErrorResponse(buf)->UnPack(res));
}

inline std::unique_ptr<skale_fb::ErrorResponseT> UnPackSizePrefixedErrorResponse(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<skale_fb::ErrorResponseT>(GetSizePrefixedErrorResponse(buf)->UnPack(res));
}

}  // namespace skale_fb

#endif  // FLATBUFFERS_GENERATED_ERRORRESPONSE_SKALE_FB_H_
