name: Build and test skale-consensus
on: [push]

jobs:
  build:
    name: build (${{ matrix.flavor.name }})
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        flavor:
          - name: standard
            flags: ""
          - name: fair
            flags: "-buildFAIR"
          - name: bite
            flags: "-buildBITE"
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 1

      - name: Setup build environment
        uses: ./.github/actions/setup-build-env
        with:
          cache-prefix: "skale-consensus-${{ matrix.flavor.name }}"

      - name: build dependencies
        run: |
          sudo apt-get install -y nettle-dev gnutls-dev
          cd deps && ./build.sh BUILD_LIBSEC256K1=1 && cd ..

      - name: build consensus (${{ matrix.flavor.name }})
        run: |
          cd scripts && ./build.py Debug ${{ matrix.flavor.flags }}

      - name: run tests (block sizes)
        env:
          CI_BUILD: "1"
          TEST_TRANSACTIONS_PER_BLOCK: "1000"
        run: |
          cd scripts
          ./tests.py && cd ..

