name: clang-format Check
on: [push]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.14
      with:
        source: '.'
        exclude: |
          './CMakeFiles ./cmake ./cppzmq ./cget ./deps ./docs ./jsoncpp ./libBLS 
          ./libjson-rpc-cpp ./spdlog  ./sgxwallet ./scripts ./run_sgx_test ./libzmq ./thirdparty 
          ./cppzmq'
        extensions: 'h,hpp,hxx,cpp,cxx,cc,ipp'
        clangFormatVersion: 11
        inplace: True